package.json
=> Reference correct file when attempt to import g6

src/mixin/query.js
=> fix(query): fix code comment

demos/gallery-webIndex.html, demos/gallery-worldcup-tree.html, plugins/tool.d3.mapper/index.js
=> fix invert d3.mapper mapping function

demos/gallery-graphanalyzer.html, demos/plugin-max-spanning-forest.html, plugins/template.maxSpanningForest/index.js, plugins/tool.mapper/index.js
=> refactor isolate calculated data from origin data model

demos/gallery-graphanalyzer.html, demos/plugin-max-spanning-forest.html, plugins/layout.forceAtlas2/layout.js, plugins/template.maxSpanningForest/index.js, plugins/tool.mapper/index.js, src/item/edge.js
=> Improve arrow

src/item/edge.js, src/shape/edges/common.js
=> fix arrow opacity

src/shape/edges/common.js
=> update arrow path from design

demos/gallery-graphanalyzer.html, package.json, plugins/template.maxSpanningForest/index.js, plugins/tool.mapper/index.js, src/graph.js, src/mixin/mode.js, src/version.js
=> dev gallery graph analyzer

package.json, plugins/tool.tooltip/index.js, src/version.js, test/unit/plugins/tool.tooltip-spec.js
=> improve tooltip

.babelrc, .torch.compile.opts.js, demos/custom-html.html, demos/gallery-graphanalyzer.html, demos/gallery-xiaomi.html, demos/plugin-minimap-has-html.html, package.json, plugins/template.maxSpanningForest/index.js, src/extend/g/dom.js, src/graph.js, src/util/graph.js
=> Minimapsolution

package.json, plugins/layout.forceAtlas2/layout.js, plugins/template.maxSpanningForest/index.js, plugins/template.maxSpanningForest/menu.js, plugins/tool.mapper/index.js, src/graph.js, test/unit/plugins/layout.forceAtlas2-spec.js, test/unit/plugins/template.maxSpanningForest-spec.js, test/unit/plugins/tool.mapper-spec.js, test/unit/plugins/tool.minimap-spec.js
=> test:maxSpanningForest test

package.json, plugins/template.maxSpanningForest/menu.js, plugins/tool.highlightSubgraph/index.js, plugins/tool.minimap/minimap.js, plugins/util.extractSubgraph/index.js, src/item/item.js, src/version.js
=> improve graph performance

demos/text.html, package.json, plugins/template.maxSpanningForest/index.js, src/controller/mapper.js, src/item/item.js
=> fix: mapper bug.Closes #433

demos/assets/data/g6-actived-system.json, demos/custom-html.html, demos/text.html, package.json, src/item/edge.js, src/item/group.js, src/shape/edges/common.js, src/shape/groups/common.js, src/shape/nodes/html.js, src/shape/nodes/index.js, src/track.js, src/version.js
=> rename arrow shorten

plugins/behaviour.analysis/index.js
修正了使用分析行为(behaviour.analysis)插件，并同时开启动画时，会引起拖拽起始时卡顿的问题。
在开始拖拽时，会发生卡顿。数据量大时表现明显。
通过在相应事件中控制动画暂时关闭来修复。
=> fix plugin.behaviour.analysis panCanvas bug

demos/assets/index.js
=> chore: demo index to es5 that ie can run

src/controller/event.js
=> 火狐不支持mousewheel,添加标准的wheel事件.

demos/test.html, src/animation/index.js
=> fix: fadeIn aniamtion

src/global.js, src/shape/index.js, src/shape/node.js, src/shape/shape.js, src/util/base.js, test/unit/shape/node-spec.js, test/unit/shape/shape-spec.js
* 添加 shape 工厂方法类
* 添加自定义 Node 代码
=> feat(shape):add shape and register node

src/item/edge.js, src/item/item.js, src/item/node.js, src/util/graphic.js, src/util/math.js, test/unit/item/edge-spec.js, test/unit/item/item-spec.js, test/unit/util/math-spec.js
=> feat(item): get intersection point

src/behavior/behavior.js, src/behavior/click-select.js, src/behavior/drag-canvas.js, src/behavior/drag-node.js, src/behavior/zoom-canvas.js, src/graph/controller/event.js, src/graph/controller/index.js, src/graph/controller/item.js, src/graph/graph.js, src/item/item.js, test/unit/graph/controller/event-spec.js
- 改写registerBehavior基类逻辑，简化逻辑
- 修复item的mouseenter & mouseleave问题
- 抽itemController
=> Daily 19 01 03

src/item/edge.js, src/item/item.js, src/item/node.js, src/shape/shape.js, test/unit/item/edge-spec.js, test/unit/item/node-spec.js
=> Daily 0103

src/item/edge.js, src/shape/edge.js, src/shape/node.js, src/util/path.js, test/unit/graph/controller/event-spec.js, test/unit/item/edge-spec.js, test/unit/item/item-spec.js, test/unit/shape/edge-spec.js, test/unit/shape/shape-spec.js
=> feat(test): add test case

package.json, src/global.js, src/graph/controller/item.js, src/graph/graph.js, test/unit/graph/graph-spec.js
=> Daily 19 01 08

src/item/node.js, src/util/math.js, test/unit/item/edge-spec.js
=> fix(node): fixed bug of node nesting

src/behavior/drag-node.js, src/global.js, src/graph/controller/event.js, src/item/item.js, test/unit/behavior/drag-node-spec.js
=> Daily 19 01 10

src/item/item.js, test/bugs/issue-601-spec.js, test/unit/item/node-spec.js
* 如果未定义 update 仅仅移动节点时不进行更新， #601 
* 修复 update 后状态丢失的问题
=> Daily 0111

src/global.js, src/graph/controller/event.js, src/graph/controller/item.js, src/graph/controller/view.js, src/graph/graph.js, src/shape/edge.js, src/shape/node.js, test/unit/graph/controller/item-spec.js, test/unit/graph/graph-spec.js, test/unit/item/edge-spec.js, test/unit/item/node-spec.js, test/unit/shape/node-spec.js
- refreshPositions
- defaultNode & defaultEdge
=> Daily 19 01 16

demos/dagre-graph.html, package.json, src/behavior/drag-node.js, src/behavior/index.js, src/behavior/tooltip.js, src/graph/controller/event.js, src/graph/controller/mode.js, src/shape/node.js, src/util/base.js, test/mocha.opts, test/support/preload.css, test/unit/behavior/drag-node-spec.js, test/unit/behavior/drag-spec.js, test/unit/behavior/tooltip-spec.js
=> Daily 19 01 18

demos/cubic-edges.html, demos/edge-animate.html, demos/force-layout.html, demos/hover-animate.html, demos/node-animate.html, demos/nodes-edges.html, src/shape/shape.js, test/unit/shape/shape-spec.js
=> feat(demos): add demos

src/graph/controller/event.js
=> fix(wheel): fix wheel event doesn't work in firefox

src/item/edge.js, src/item/item.js, test/unit/item/edge-spec.js
* 增加 bbox 的缓存
* 自定义边上存在控制点时，计算边的起点存在问题
=> fix(edge):fixed bug of link point

src/graph/controller/item.js, src/graph/graph.js, src/item/edge.js, test/unit/graph/graph-spec.js, test/unit/item/edge-spec.js
=> Daily 0226

package.json, src/global.js, src/graph/controller/event.js, src/graph/controller/item.js, src/graph/controller/mode.js, src/graph/controller/view.js, src/graph/graph.js, src/item/edge.js, src/item/item.js, src/shape/single-shape-mixin.js, test/unit/graph/controller/view-spec.js, test/unit/graph/graph-spec.js, test/unit/item/node-spec.js, test/unit/shape/node-spec.js
=> Daily 190305

package.json, src/global.js, src/graph/tree-graph.js, src/item/item.js, test/unit/item/node-spec.js
=> Daily 190306

demos/tree-graph.html, src/behavior/collapse-expand.js, src/item/node.js, src/shape/edge.js, test/unit/shape/edge-spec.js
=> chore(edge): adjust default curve control points

src/global.js, src/graph/graph.js, src/item/edge.js, src/item/item.js, src/util/graphic.js, test/unit/graph/controller/animate-spec.js, test/unit/graph/controller/item-spec.js, test/unit/graph/graph-spec.js
=> Daily 190308

demos/custom-tree-graph.html, demos/force-layout.html, demos/radial-tree.html, demos/tree-graph.html, package.json, src/behavior/drag-node.js, src/graph/controller/item.js, src/graph/graph.js, src/util/base.js, test/unit/graph/graph-spec.js
=> Daily 190315

.torch.compile.opts.js, demos/custom-tree-graph.html, demos/default-shapes.html, demos/er-diagram.html, demos/force-layout.html, demos/node-animate.html, demos/sankey-diagram.html, demos/setState.html, package.json, plugins/base.js, plugins/index.js, plugins/minimap/index.js, src/behavior/edge-tooltip.js, src/behavior/index.js, src/behavior/tooltip-base.js, src/behavior/tooltip.js, src/global.js, src/graph/graph.js, test/unit/behavior/tooltip-spec.js, test/unit/graph/graph-spec.js, test/unit/plugins/minimap-spec.js, webpack.config.js
=> Daily 190317

src/behavior/tooltip-base.js, src/graph/controller/event.js, src/item/item.js, test/unit/behavior/tooltip-spec.js, test/unit/graph/controller/event-spec.js
=> fix(event): fix event x & y, fix tooltip x & y, add capture

demos/custom-tree-graph.html, demos/force-layout.html, demos/radial-tree.html, package.json, plugins/minimap/index.js, src/behavior/collapse-expand.js, src/behavior/drag-canvas.js, src/behavior/drag-node.js, src/graph/controller/event.js, src/item/item.js, test/bugs/issue-659-spec.js, test/unit/behavior/drag-node-spec.js, test/unit/plugins/minimap-spec.js
=> Daily 190325

plugins/base.js, plugins/grid/index.js, plugins/index.js, plugins/minimap/index.js, src/behavior/activate-relations.js, src/behavior/index.js, src/graph/graph.js, test/unit/behavior/activate-relations-spec.js, test/unit/graph/graph-spec.js, test/unit/plugins/grid-spec.js, test/unit/plugins/minimap-spec.js
=> Daily 190328

src/util/path.js
=> chore: fix a typo

demos/dagre-graph.html, demos/dynamic-add.html, src/behavior/collapse-expand.js, src/behavior/drag-canvas.js, src/behavior/drag-node.js, src/behavior/tooltip-base.js, src/graph/controller/index.js, src/graph/controller/item.js, src/graph/controller/state.js, src/graph/graph.js, src/item/edge.js, src/shape/single-shape-mixin.js, test/unit/behavior/drag-node-spec.js, test/unit/graph/controller/state-spec.js, test/unit/graph/graph-spec.js
=> Graph states

demos/er-diagram.html, src/graph/graph.js, src/shape/edge.js, src/util/graphic.js, test/unit/behavior/drag-node-spec.js
=> feat(util): add util to measure text position with refX, refY & rotate

package.json, plugins/minimap/index.js, src/graph/controller/state.js
=> Daily 190423

src/graph/controller/item.js
修改一个拼写错误，保持和文档叙述一致：https://www.yuque.com/antv/g6/graph#409a77b5
=> fix: afteradditem 拼写错误

package.json, src/global.js
=>  update package version

demos/area-chart-node.html, demos/bar-chart-node.html, demos/chart-node.html, demos/collapse-expand-group.html, demos/custom-tree-interactive.html, demos/front-edge.html, demos/line-chart-node.html, demos/point-chart-node.html, demos/stacked-bar-chart-node.html, package.json, src/behavior/drag-group.js, src/behavior/drag-node-with-group.js, src/behavior/drag-node.js, src/graph/controller/customGroup.js, src/graph/graph.js, test/unit/graph/controller/custom-group-spec.js
=> fix: drag group node

CHANGELOG.md, package.json, src/global.js
=> update package version

src/graph/tree-graph.js
=> getModel is undefined

CHANGELOG.md, package.json, src/global.js, src/util/groupData.js, test/unit/graph/controller/custom-group-spec.js, test/unit/index-spec.js, test/unit/util/groupdata-spec.js
=> fix group data not support es5

src/global.js, src/shape/nodes/circle.js, src/shape/nodes/diamond.js, src/shape/nodes/ellipse.js, src/shape/nodes/rect.js, src/shape/nodes/star.js, src/shape/nodes/triangle.js, test/bugs/issue-659-spec.js
=> change shape color

plugins/grid/index.js
=> 修复fitView网格空白问题

CONTRIBUTING.md, CONTRIBUTING.zh-CN.md
修复 CONTRIBUTING.md 和 CONTRIBUTING.zh-CN.md 文档中错误的链接及文案。
=> fix: replace g2 to g6 for contributing.md

package.json, types/g.d.ts, types/index.d.ts
This pr include the g6 type definition file, it's friendly for TypeScript.
=> feat: add g6 type definition

.browserslistrc, package.json
=> fix not support ie11

types/index.d.ts
The definition updated, passed all the demo page
=> feat: update definition file

CHANGELOG.md, demos/group-rect.html, demos/internal-node-rect.html, demos/internal-node-star.html, demos/system-graph-demo.html, src/behavior/brush-select.js, src/behavior/drag-group.js, src/shape/edge.js, src/shape/edges/polyline.js
* fix: set brush-select trigger param to ctrl not work
* fix: when set fitView to true, drag-group Behavior not get desired positon
=> fix brush-select and drag-group behavior

demos/internal-node-rect.html, src/behavior/drag-node.js
=> fix drag-node close autoPaint

package.json, src/global.js
=> fix: update package version

docs/api/GlobalAPI.md, docs/api/Graph.md
=> 添加GlobalAPI.md、Graph.md

types/g.d.ts, types/index.d.ts
optimize the interface declarations
=> fix: optimize the interface declarations

demos/case-simplify.html, demos/layout-dagre.html, demos/layout-force.html, package.json, src/global.js, src/layout/dagre.js, src/layout/force.js, src/layout/fruchterman-group.js, src/layout/fruchterman.js, src/layout/radial/radial.js, src/layout/radial/radialNonoverlapForce.js
=> feat: layout parameters support function type

src/shape/edges/polyline.js
fix: merge custom label config
=> fix: merge custom label config

examples/scatter/default/demo/default.js, examples/scatter/default/demo/meta.json, examples/scatter/default/index.zh.md, examples/scatter/hover/demo/hover.js, examples/scatter/hover/demo/meta.json, examples/scatter/hover/index.zh.md, examples/scatter/node/demo/meta.json, examples/scatter/node/demo/node.js, examples/scatter/node/index.zh.md, examples/scatter/position/demo/meta.json, examples/scatter/position/demo/position.js, examples/scatter/position/index.zh.md, site/pages/index.zh.tsx
=> docs: scatter demos

types/index.d.ts
fix: fix the interface of the `on` method
=> fix: fix the interface of the `on` method

package.json, src/behavior/brush-select.js, src/global.js, src/graph/controller/customGroup.js, src/graph/controller/event.js, src/graph/graph.js, src/layout/circular.js, src/layout/concentric.js, src/layout/fruchterman-group.js, src/layout/fruchterman.js, src/layout/grid.js, src/layout/radial/radial.js, src/layout/random.js
=> fix: version number

.npmignore, package.json, src/global.js
=> fix: G6 package delete public and .cache file

package.json, plugins/minimap/index.js
主要fix以下三个问题：
1. minimap viewport边界溢出问题
2. graph超过minimap可视区域后偏移问题
3. minimap不能准确控制显示范围问题
=> Minimap 优化

.eslintignore, src/behavior/drag-node.js, src/graph/controller/state.js, src/shape/nodes/circle.js, src/shape/nodes/diamond.js, src/shape/nodes/ellipse.js, src/shape/nodes/modelRect.js, src/shape/nodes/rect.js
- eslint排除site、cache和public；
- drag-node 不支持 shape中 linkPoints ；
- fix state bug：[#924 ];
- shape 中增加 isAnchorPoint 标识。
=> Fix minimap state 20191120

src/shape/shape.js
ucfirst 开销过大，进行缓存,   确定这个是认真的吗？
=> fix:missing cache ucfirst

gatsby-config.js, package.json
https://github.com/antvis/antvis.github.io/issues/18
=> 🚀 g6.antv.vision

docs/manual/getting-started.en.md, docs/manual/getting-started.zh.md, gatsby-config.js
=> fix: update docs url

.babelrc, .babelrc.js, package.json, src/global.js
=> fix: not include corejs

examples/case/simplifyCluster/demo/index.js, gatsby-browser.js
=> fix: webworker for case simplify

.babelrc.js, package.json
=> fix: babelrc support gatsby

site/pages/index.zh.tsx
=> fix: G6 home page add titlesuffix

docs/manual/cases/relations.en.md, docs/manual/cases/relations.zh.md, docs/manual/cases/sequenceTime.en.md, docs/manual/cases/sequenceTime.zh.md, types/antvUtil.d.ts, types/index.d.ts
- 修复类型文件导致的编译失败 https://github.com/antvis/g6/issues/943 
- 修改官网链接。
=> fix: g6 type files

types/antvUtil.d.ts, types/index.d.ts
declare module '@antv/util/*', fix build error in TypeScript projects.
=> feat: declare antv/util typings

package.json, src/global.js
=> fix: update package version number

CHANGELOG.md, package.json, src/global.js, src/graph/graph.js
=> fix: group position error

docs/api/TreeGraph.en.md
=> fix: small error of english version of treegraph

types/antvUtil.d.ts, types/index.d.ts
=> fix typescript compile error

docs/manual/getting-started.zh.md
=> fix: update g6 version

README-zh_CN.md, README.md, docs/manual/introduction.en.md, docs/manual/introduction.zh.md
=> feat: update introduction docs

package.json, types/antvUtil.d.ts, types/index.d.ts
=> fix: g6 site demos

src/graph/controller/item.js, src/util/base.js, types/antvUtil.d.ts, types/index.d.ts
=> fix: g6 site error

gatsby-browser.js
=> fix: delete sanky lib

docs/manual/FAQ/build-error.en.md, docs/manual/FAQ/build-error.zh.md, docs/manual/FAQ/front-edge.en.md, docs/manual/FAQ/front-edge.zh.md, docs/manual/FAQ/multi-line.en.md, docs/manual/FAQ/multi-line.zh.md
=> Update g6 site

docs/api/Group.en.md, docs/manual/middle/elements/edgeVisible.en.md, docs/manual/middle/elements/edgeVisible.zh.md, docs/manual/middle/elements/elementIndex.en.md, docs/manual/middle/elements/elementIndex.zh.md, docs/manual/middle/elements/nodes/circle.en.md, docs/manual/middle/elements/nodes/circle.zh.md, docs/manual/middle/elements/nodes/defaultNode.en.md, docs/manual/middle/elements/nodes/defaultNode.zh.md, docs/manual/middle/elements/nodes/diamond.en.md, docs/manual/middle/elements/nodes/diamond.zh.md, docs/manual/middle/elements/nodes/ellipse.en.md, docs/manual/middle/elements/nodes/ellipse.zh.md, docs/manual/middle/elements/nodes/image.en.md, docs/manual/middle/elements/nodes/image.zh.md, docs/manual/middle/elements/nodes/modelRect.en.md, docs/manual/middle/elements/nodes/modelRect.zh.md, docs/manual/middle/elements/nodes/rect.en.md, docs/manual/middle/elements/nodes/rect.zh.md, docs/manual/middle/elements/nodes/star.en.md, docs/manual/middle/elements/nodes/star.zh.md, docs/manual/middle/elements/nodes/traingle.en.md, docs/manual/middle/elements/nodes/traingle.zh.md, docs/manual/middle/keyConcept.en.md, docs/manual/middle/keyConcept.zh.md
=> Internat step3

types/antvUtil.d.ts, types/index.d.ts
=> fix: g6 types file

demos/internal-edge-loop.html, demos/internal-node-rect.html, demos/layout-circular.html, src/util/graphic.js
=> fix: loop for rect node

docs/manual/FAQ/build-error.en.md, docs/manual/FAQ/build-error.zh.md, docs/manual/FAQ/front-edge.en.md, docs/manual/FAQ/front-edge.zh.md, docs/manual/FAQ/multi-line.zh.md, docs/manual/FAQ/supportIE.en.md, docs/manual/FAQ/supportIE.zh.md, docs/manual/FAQ/updateElement.en.md, docs/manual/FAQ/updateElement.zh.md, docs/manual/FAQ/updateText.en.md, docs/manual/FAQ/updateText.zh.md, docs/manual/cases/edgeBundling.en.md, docs/manual/cases/edgeBundling.zh.md, docs/manual/cases/relations.en.md, docs/manual/cases/relations.zh.md, docs/manual/cases/sequenceTime.en.md, docs/manual/cases/sequenceTime.zh.md
=> fix: review for cases and FAQ. closes: #1018.

jest.config.js, package.json, src/behavior/behavior.ts, src/behavior/behaviorOption.ts, src/behavior/drag-canvas.ts, src/graph/controller/index.ts, src/graph/controller/mode.ts, src/graph/graph.ts, src/interface/behavior.ts, src/interface/graph.ts, src/interface/item.ts, src/item/edge.ts, src/item/item.ts, src/item/node.ts, src/util/base.ts, src/util/graphic.ts, src/util/group.ts, src/util/math.ts, src/util/path.ts, tests/unit/behavior/index-spec.ts, tests/unit/graph/controller/mode-spec.ts, tsconfig.json, types/index.ts
- 类型及接口文件定义、类型定义文件；
- Behavior 实现机制；
- Util 模块重构。
=> feat: update types file

src/graph/controller/state.ts, src/graph/graph.ts, src/interface/graph.ts
- refactor states controller;
- update graph types file.
=> feat: refactor states controller

docs/manual/introduction.zh.md
=> docs: Update introduction.zh.md

src/graph/controller/item.ts, src/graph/graph.ts, src/interface/behavior.ts, src/interface/graph.ts, src/interface/item.ts, src/item/edge.ts, src/item/node.ts, tsconfig.json, types/index.ts
=> feat: Refactoring item controller and graph

docs/api/Plugins.en.md, docs/api/Plugins.zh.md
=> docs: update Plugins.zh.md & Plugins.en.md

src/behavior/behavior.ts, src/behavior/behaviorOption.ts, src/graph/graph.ts, src/interface/graph.ts, src/util/math.ts, tests/unit/graph/graph-spec.ts, webpack.config.js
=> feat: update graph file

CHANGELOG.md, package.json, src/graph/controller/event.ts, src/graph/controller/item.ts, src/graph/graph.ts, src/index.ts, src/interface/graph.ts, src/item/edge.ts, src/item/item.ts, src/shape/shapeBase.ts, src/util/graphic.ts, src/util/math.ts, tests/unit/graph/controller/event-spec.ts, tests/unit/graph/controller/item-spec.ts, tests/unit/graph/controller/state-spec.ts, tests/unit/graph/controller/view-spec.ts, tests/unit/graph/graph-spec.ts, webpack.config.js
- 增加 item 和 event controller 的单测。
=> feat: add  event and item controller unit test

package.json
=> fix: 修复G6官网搜索问题

src/layout/grid.js, test/unit/layout/grid-spec.js
=> fix: 修复grid布局指定行列参数(cols/rows)不生效的问题

.eslintignore, package.json, src/graph/graph.ts, src/interface/graph.ts, src/shape/nodes/circle.ts, tests/unit/graph/tree-graph-spec.ts
=> feat: add tree graph unit test

src/behavior/drag-node-with-group.js, src/graph/controller/customGroup.js
=> feat: 节点拖动group随着节点的位置更新大小

CHANGELOG.md, package.json, src/behavior/drag-node-with-group.js, src/behavior/drag-node.js, src/global.js, src/graph/controller/customGroup.js, types/index.d.ts
* feat: supports create the group without nodes in node-group;
* fix: supports destoryed properties and fix issue [1094](https://github.com/antvis/G6/issues/1094);
=> feat: supports create the group without nodes in node-group

src/graph/controller/event.js, src/graph/controller/view.js, src/util/base.js
=> fix: empty data event tigger error

src/behavior/brush-select.ts, src/behavior/click-select.ts, tests/unit/behavior/select-spec.ts
=> Select emit

src/graph/controller/customGroup.js
=> Feat/empty group position：新增空节点可拖动

package.json, src/global.js
=> feat: update package version

package.json, src/behavior/collapse-expand.ts, src/behavior/drag-node-with-group.ts, src/behavior/drag-node.ts, src/graph/controller/item.ts, src/graph/graph.ts, src/graph/tree-graph.ts, src/item/item.ts, src/shape/edge.ts, src/shape/nodes/image.ts, src/shape/nodes/modelRect.ts, src/shape/nodes/rect.ts, src/shape/shapeBase.ts, tests/unit/state/edge-state-spec.ts, tests/unit/state/node-state-spec.ts, types/index.ts
=> Ts state test

package.json, src/graph/controller/item.ts, src/graph/controller/state.ts, src/graph/graph.ts, src/interface/graph.ts, src/plugins/bundling/index.ts, src/plugins/menu/index.ts, src/plugins/minimap/index.ts, src/util/math.ts, src/util/path.ts, tests/unit/graph/controller/customGroup-spec.ts, tests/unit/graph/controller/state-spec.ts, tests/unit/graph/graph-spec.ts, tests/unit/graph/tree-graph-spec.ts, tests/unit/layout/circular-spec.ts, tests/unit/layout/circular-web-worker-spec.ts, tests/unit/layout/force-web-worker-spec.ts, tests/unit/layout/grid-spec.ts, tests/unit/layout/mds-spec.ts, tests/unit/layout/preset-spec.ts, tests/unit/layout/random-spec.ts, tests/unit/layout/web-worker-spec.ts, tests/unit/plugins/bundling-spec.ts, tests/unit/plugins/menu-spec.ts, tests/unit/plugins/minimap-spec.ts, tests/unit/util/base-spec.ts, tests/unit/util/math-spec.ts, tests/unit/util/path-spec.ts, tests/unit/util/timeOut.ts, types/index.ts
=> fix：增加plugins、util及graph等模块的单测

package.json, src/graph/controller/state.ts, src/item/item.ts, src/plugins/minimap/index.ts, stories/Shape/component/default-shape.tsx, tests/unit/plugins/minimap-spec.ts
=> fix：修复Minimap问题

package.json, src/global.js
=> feat: update package version number

src/layout/dagre.ts, src/plugins/menu/index.ts, src/shape/edge.ts, src/shape/edges/polyline.ts, src/shape/node.ts, src/shape/nodes/circle.ts, src/shape/nodes/star.ts, src/util/index.ts, tests/unit/behavior/drag-canvas-spec.ts, tests/unit/layout/dagre-spec.ts, tests/unit/shape/edges/polyline-spec.ts
=> fix: polyline problem

package.json, src/behavior/drag-canvas.ts, src/behavior/drag-node.ts, tests/unit/behavior/drag-node-spec.ts, tests/unit/behavior/index-spec.ts
=> fix: update g version number

package.json, src/graph/tree-graph.ts
=> fix: treegraph updatelayout

package.json, src/global.ts
=> fix: update main path

src/item/item.ts
=> fix: change group.attr into group.set in item.ts

package.json, src/behavior/brush-select.ts, src/global.ts, src/interface/graph.ts, tests/unit/behavior/brush-select-spec.ts
=> fix: brush-select bug

package.json, src/global.ts, src/interface/graph.ts
=> fix: 修复 IGraph 中find 和 findall 第二个参数为可选

package.json, src/global.ts, src/interface/graph.ts
=> Fix types file

src/graph/controller/item.js
=> fix: ensure do not expand dom Node in updateItem

package.json, src/global.js
=> fix: filter html node

.eslintrc.js, gatsby-browser.js, package.json, src/interface/behavior.ts, src/interface/graph.ts, src/interface/item.ts, src/interface/layout.ts, src/interface/shape.ts, src/item/edge.ts, src/item/item.ts, src/item/node.ts, src/layout/circular.ts, src/layout/concentric.ts, src/layout/dagre.ts, src/layout/force.ts, src/layout/fruchterman.ts, src/layout/grid.ts, src/layout/layout.ts, src/layout/mds.ts, src/layout/radial/mds.ts, src/layout/radial/radial.ts, src/layout/radial/radialNonoverlapForce.ts, src/layout/random.ts, src/types/index.ts, src/util/math.ts, tests/unit/layout/random-spec.ts, tests/unit/layout/web-worker-spec.ts, tsconfig.json
=> Ts refactor

src/graph/controller/state.ts, src/interface/shape.ts, src/plugins/base.ts, src/plugins/bundling/index.ts, src/plugins/menu/index.ts, src/plugins/minimap/index.ts, src/shape/edge.ts, src/shape/edges/polyline-util.ts, src/shape/edges/polyline.ts, src/shape/node.ts, src/shape/nodes/circle.ts, src/shape/nodes/diamond.ts, src/shape/nodes/ellipse.ts, src/shape/nodes/image.ts, src/shape/nodes/modelRect.ts, src/shape/nodes/rect.ts, src/shape/nodes/star.ts, src/shape/nodes/triangle.ts, src/shape/shape.ts, src/shape/shapeBase.ts, src/types/index.ts, src/util/base.ts, src/util/group.ts, src/util/math.ts, stories/Shape/component/default-shape.tsx
=> fix: 修复 strict src/plugins, src/shape 及 src/util 

README-zh_CN.md, README.md, package.json, src/global.ts, tests/unit/graph/graph-spec.ts, tests/unit/layout/circular-web-worker-spec.ts, tests/unit/plugins/bundling-spec.ts, webpack.config.js
=> update: version number to beta.7

package.json, src/index.ts, tests/unit/plugins/bundling-spec.ts, tests/unit/plugins/grid-spec.ts, tests/unit/plugins/menu-spec.ts, tests/unit/plugins/minimap-spec.ts
=> fix: export plugins and they can be called by G6.Minimap and so on.

package.json, src/graph/graph.ts, src/graph/tree-graph.ts, src/interface/graph.ts, src/interface/shape.ts, src/shape/edge.ts, src/shape/edges/polyline.ts, src/shape/node.ts, src/shape/nodes/circle.ts, src/shape/nodes/diamond.ts, src/shape/nodes/ellipse.ts, src/shape/nodes/modelRect.ts, src/shape/nodes/rect.ts, src/shape/nodes/star.ts, src/shape/nodes/triangle.ts, src/shape/shapeBase.ts, src/types/index.ts, stories/Performance/component/complex-tree.tsx, stories/Performance/component/erdos.tsx, stories/Performance/component/eva.tsx, stories/Performance/component/netscience.tsx, stories/Performance/component/rt-occupy.tsx, stories/Performance/performance.stories.tsx, tests/unit/graph/tree-graph-spec.ts, tests/unit/shape/nodes/modelRect-spec.ts, tests/unit/shape/nodes/star-spec.ts
=> fix: optimize the performance

.eslintrc.js, src/item/edge.ts, src/item/item.ts, src/layout/mds.ts, src/plugins/bundling/index.ts, src/plugins/menu/index.ts, src/plugins/minimap/index.ts, src/shape/shapeBase.ts, src/util/group.ts, src/util/math.ts, src/util/path.ts
=> fix: refactor eslint

.eslintrc.js, src/layout/circular.ts, src/layout/force.ts, src/layout/grid.ts, src/layout/layout.ts, src/layout/radial/radial.ts, src/util/math.ts
=> fix: ts eslint error

gatsby-config.js, package.json
=> feat: multiple version of sites

.travis.yml, package.json
=> feat: support coverage

README-zh_CN.md, README.md
=> feat: readme show coverage info

tests/unit/graph/controller/mode-spec.ts
=> fix: 修正拼写错误

docs/api/Plugins.en.md, docs/api/Plugins.zh.md, docs/manual/FAQ/upgradeGuide.en.md, docs/manual/FAQ/upgradeGuide.zh.md, docs/manual/tutorial/plugins.en.md, docs/manual/tutorial/plugins.zh.md, docs/manual/tutorial/preface.en.md, docs/manual/tutorial/preface.zh.md, package.json, src/graph/graph.ts, tests/unit/graph/graph-spec.ts
…rror about cannot read property 6 of null when update data frequently.
=> fix: compatibility problem and docs

docs/manual/FAQ/upgradeGuide.en.md, docs/manual/FAQ/upgradeGuide.zh.md
=> fix: 更新升级文档

src/shape/edge.ts, src/shape/shapeBase.ts, tests/unit/graph/graph-spec.ts, tests/unit/shape/edge-spec.ts
- fix: edge label auto rotate with endArrow bug;
- test: edge label auto rotate with zooming and moving.
=> fix: edge label auto rotate with endArrow bug.

CHANGELOG.md, docs/manual/advanced/custom-node.en.md, docs/manual/advanced/custom-node.zh.md, examples/tree/indented/demo/filesystem.js, package.json, src/global.ts, src/layout/fruchterman.ts, src/shape/edge.ts, src/shape/edges/polyline.ts, tests/unit/layout/fruchterman-spec.ts
- fix: line with control points bug;
- doc: draggable for custom node doc;
- doc: CHANGELOG updated;
- update package version
=> fix: line with control points bug.

src/behavior/behavior.ts, src/behavior/click-select.ts, src/behavior/collapse-expand-group.ts, src/behavior/collapse-expand.ts, src/graph/controller/customGroup.ts, src/graph/controller/view.ts, src/graph/graph.ts, src/graph/tree-graph.ts, src/item/node.ts, src/layout/mds.ts, src/plugins/bundling/index.ts, src/plugins/grid/index.ts, src/plugins/minimap/index.ts, src/types/index.ts, src/util/math.ts, tests/unit/graph/controller/item-spec.ts, tests/unit/graph/graph-spec.ts, tests/unit/graph/tree-graph-spec.ts, tests/unit/util/math-spec.ts
=> fix: fix wrong spell and eslint

CHANGELOG.md, package.json, src/global.ts, src/graph/controller/view.ts, src/plugins/grid/index.ts, src/plugins/minimap/index.ts, src/util/graphic.ts, stories/Case/component/tutorial.tsx, tests/unit/plugins/minimap-spec.ts
=> Ts minimap

src/layout/dagre.ts
add weight field for dagre layout
dagrejs Wiki https://github.com/dagrejs/dagre/wiki#configuring-the-layout
=> feat: add weight field for dagre layout

src/behavior/behavior.ts, src/graph/graph.ts, src/interface/behavior.ts, src/interface/graph.ts, src/interface/item.ts, src/interface/shape.ts, src/types/index.ts
=> feat: optimize the interfaces of g6

.travis.yml, docs/api/Graph.en.md, docs/api/Graph.zh.md, docs/api/shapeProperties.en.md, docs/api/shapeProperties.zh.md, docs/manual/advanced/custom-node.en.md, docs/manual/advanced/custom-node.zh.md, docs/manual/advanced/keyconcept/shape-and-properties.en.md, docs/manual/advanced/keyconcept/shape-and-properties.zh.md, docs/manual/middle/g6InReact.en.md, docs/manual/middle/g6InReact.zh.md, docs/manual/middle/states/state-new.en.md, docs/manual/middle/states/state-new.zh.md, docs/manual/middle/svg.en.md, docs/manual/middle/svg.zh.md, examples/shape/customNode/demo/meta.json, examples/shape/customNode/demo/svgDom.js
=> docs: svg demo

.travis.yml, CHANGELOG.md, docs/api/shapeProperties.en.md, docs/api/shapeProperties.zh.md, docs/manual/middle/elements/edges/defaultEdge.en.md, docs/manual/middle/elements/edges/defaultEdge.zh.md, docs/manual/middle/elements/nodes/defaultNode.en.md, docs/manual/middle/elements/nodes/defaultNode.zh.md
=> docs: complete the missing CHANGELOG for 3.2.3 to 3.2.7.

src/layout/dagre.ts, src/layout/radial/radial.ts
=> chore: fix typo

package.json, src/shape/edges/polyline.ts, tests/unit/layout/dagre-spec.ts
=> fix: empty path string when startpoint and endpoint is nan in polyline

gatsby-browser.js, src/layout/dagre.ts, src/shape/edge.ts, src/shape/edges/polyline-util.ts, src/shape/edges/polyline.ts, stories/Shape/component/polyline.tsx, stories/Shape/shape.stories.tsx
=> Polyline dagre

src/graph/controller/customGroup.ts, src/interface/graph.ts, src/util/group.ts, tests/unit/behavior/drag-group-spec.ts
修复多与 2 层嵌套时候的问题 https://github.com/antvis/G6/issues/1346
=> fix: 修复 group 多层级时的bug

src/global.ts, src/graph/graph.ts, src/shape/combo.ts, src/shape/combos/circle.ts, src/shape/combos/rect.ts, src/types/index.ts, stories/Combo/component/default-combo.tsx, tests/unit/shape/combo-spec.ts
=> feat: config the paddings and smallest size for rect and circle.

CHANGELOG.md, docs/api/Graph.en.md, docs/api/Graph.zh.md, package.json, src/global.ts, src/graph/graph.ts, src/interface/graph.ts, src/layout/fruchterman.ts, src/shape/nodes/image.ts, src/types/index.ts, stories/Layout/component/dagre-layout.tsx, stories/Shape/component/image2.tsx, stories/Shape/shape.stories.tsx, tests/unit/shape/nodes/image-spec.ts
=> Download image

package.json, src/global.ts, src/shape/shapeBase.ts
fix https://github.com/antvis/G6/issues/1387
=> fix: register shape do not support states

examples/gallery/index.en.md, examples/gallery/index.zh.md, gatsby-browser.js, gatsby-config.js
close https://github.com/antvis/gatsby-theme-antv/issues/121
=> docs: Add gallery page

docs/api/Group.en.md, docs/api/Group.zh.md, docs/manual/FAQ/transform.en.md, docs/manual/FAQ/transform.zh.md, docs/manual/advanced/custom-node.en.md, docs/manual/advanced/custom-node.zh.md, docs/manual/middle/states/state.zh.md, examples/scatter/edge/index.en.md, examples/scatter/edge/index.zh.md, examples/scatter/node/demo/node.js
=> docs: update the docs about state, custom node and urls of animate docs.

src/graph/controller/item.ts, src/graph/controller/layout.ts, src/graph/graph.ts, src/item/combo.ts, src/layout/comboForce.ts, src/layout/fruchterman.ts, src/layout/g6force.ts, src/layout/index.ts, src/layout/layout.ts, src/shape/combos/circle.ts, src/shape/combos/rect.ts, src/types/index.ts, src/util/graphic.ts, stories/Combo/component/default-combo.tsx, stories/Layout/component/g6force-layout.tsx, stories/Layout/layout.stories.tsx
=> Combo render and layout

src/graph/graph.ts, src/interface/item.ts, src/item/item.ts, src/item/node.ts, src/util/graphic.ts, stories/Combo/component/default-combo.tsx
=> Combo update tree

package.json, src/graph/graph.ts, src/item/item.ts, src/plugins/minimap/index.ts, src/shape/shapeBase.ts, src/types/index.ts, stories/Case/component/decision-tree.tsx, stories/Case/component/flow.tsx, stories/Tree/component/flow-tree.tsx, stories/Tree/tree.stories.tsx, tests/unit/issues-spec.ts, tests/unit/plugins/minimap-spec.ts, tests/unit/state/update-element-states-spec.ts
1. changeData 时清除已有状态： https://github.com/antvis/G6/issues/1357 ;
2.修复 states 状态取消后，updateItem 效果不起作用的问题：https://g6.antv.vision/zh/examples/interaction/label
=> fix: changeData clear states & refactor states

CHANGELOG.md
=> 3.4.5 changelog

docs/manual/advanced/custom-node.en.md, docs/manual/advanced/custom-node.zh.md, examples/shape/customNode/demo/svgDom.js, stories/Issues/component/dom-click.tsx, stories/Issues/issues.stories.tsx
=> docs: update the docs for DOM listener.

src/shape/nodes/modelRect.ts
=> fix: dragging is not supported by clicking the label in the modelrect node

src/graph/controller/layout.ts, src/shape/edge.ts, stories/Layout/component/addNodeLayout.tsx, stories/Layout/component/changeData.tsx, stories/Layout/layout.stories.tsx, stories/Shape/component/quadratic.tsx, stories/Shape/shape.stories.tsx
=> Curve offset

CHANGELOG.md, src/plugins/minimap/index.ts, stories/Plugins/component/minimap-force.tsx, stories/Plugins/component/minimap.tsx
=> fix: removeItem to update the minimap.

demos/case-voucher-transfer.html, examples/case/decisionTree/demo/index.ts, stories/Issues/attrs/index.tsx, stories/Issues/changeData/data.js, stories/Issues/changeData/index.tsx, stories/Issues/component/dagre-arrow.tsx, stories/Layout/component/dagre-layout.tsx, stories/Shape/component/issue-1.tsx, stories/Shape/component/polyline.tsx, stories/Shape/component/quadratic.tsx, stories/Tree/component/flow-tree.tsx
=> fix: 修复数据问题

.github/workflows/gitleaks.yml
=> fix: add security check file.

src/behavior/drag-combo.ts, src/graph/graph.ts, src/util/graphic.ts, stories/Combo/combo.stories.tsx, stories/Combo/component/collapse-expand-vedge.tsx, stories/Combo/component/combo-drag-collapse-expand.tsx, stories/Combo/component/combo-layout-collapse-expand.tsx
=> fix: reconstructTree without parentId.

src/graph/graph.ts
=> fix: expand combo with dulplicate virtual edges bug.

src/behavior/click-select.ts, src/behavior/drag-combo.ts, src/behavior/drag-node.ts, src/graph/controller/item.ts, src/graph/graph.ts, src/item/item.ts, src/types/index.ts, tests/unit/behavior/drag-combo-spec.ts
删除：
✅删除分组，与分组相连的边同步删除；
✅删除分组，删除分组中的节点；
✅删除分组中的图元素。
✅支持渲染默认收起的分组：需要提供配置项配置是否默认收起。
✅修复拆分嵌套 combo 时报错的问题；
✅drag-node 和 drag-combo behaviors 中增加 activeState，用于指定拖动时目标 combo 的状态样式；
✅删除 Item 中defaultConfig字段；
=> fix: test combo & fix uncombo

docs/manual/middle/states/defaultBehavior.en.md, docs/manual/middle/states/defaultBehavior.zh.md
=> fix: Combo Behavior docs

docs/api/Algorithm.en.md, docs/api/Algorithm.zh.md, src/algorithm/bfs.ts, src/algorithm/comparator.ts, src/algorithm/detect-cycle.ts, src/algorithm/dfs.ts, src/algorithm/index.ts, src/algorithm/structs/linked-list/index.ts, src/algorithm/structs/queue/index.ts, src/graph/graph.ts, src/index.ts, src/interface/graph.ts, src/interface/item.ts, src/item/item.ts, src/item/node.ts, src/types/index.ts, tests/unit/algorithm/bfs-spec.ts, tests/unit/algorithm/detect-cycle-spec.ts, tests/unit/algorithm/dfs-spec.ts, tests/unit/algorithm/linkedList-spec.ts, tests/unit/algorithm/queue-spec.ts
1. 增加 BFS、DFS 及 圈检测算法；
2. Graph 中增加 getNeighbors、getSourceNeighbors 和 getTargetNeighbors 三个方法；
3. Node 中增加 getNeighbors、getSourceNeighbors 和 getTargetNeighbors 三个方法；
4. Item 中增加 getID() 方法；
5. 增加图算法文档。
=> feat: graph algorithm & docs

CHANGELOG.md, docs/api/Algorithm.zh.md, tests/unit/graph/graph-spec.ts
=> fix: update changelog file & add neighbors unit test

package.json, src/shape/shapeBase.ts, tests/unit/combo-issue-spec.ts, tests/unit/state/update-element-states-spec.ts
=> fix: combo states

src/behavior/zoom-canvas.ts, tests/unit/behavior/zoom-spec.ts
fix zoom-canvas 无视 shouldUpdate 的配置，一律都 preventDefault 的行为
=> chore: zoom-canvas shouldUpdate

package.json, src/graph/controller/item.ts, tests/unit/behavior/activate-relations-spec.ts, tests/unit/behavior/brush-select-spec.ts, tests/unit/behavior/select-spec.ts, tests/unit/combo-issue-spec.ts, tests/unit/graph/controller/item-spec.ts, tests/unit/graph/controller/state-spec.ts, tests/unit/graph/graph-spec.ts, tests/unit/graph/svg-spec.ts, tests/unit/issues-spec.ts
修复  https://github.com/antvis/G6/issues/1625 问题
=> fix: 不能设置不存在的状态

.eslintignore, .eslintrc.js, CHANGELOG.md, docs/manual/advanced/custom-node.en.md, docs/manual/advanced/custom-node.zh.md, package.json, src/behavior/click-select.ts, src/behavior/drag-combo.ts, src/behavior/drag-node.ts, src/global.ts, src/graph/controller/customGroup.ts, src/graph/controller/item.ts, src/graph/graph.ts, src/item/combo.ts, src/item/item.ts, src/layout/comboForce.ts, src/layout/g6force.ts, src/plugins/minimap/index.ts, src/shape/combos/rect.ts, src/shape/edges/polyline.ts, src/shape/nodes/circle.ts, src/shape/nodes/rect.ts, src/shape/shapeBase.ts, src/util/graphic.ts, src/util/math.ts
=> Drag combo bug

src/graph/controller/layout.ts
feat: rerender on each tick for custom layout
graph rendered just after layout execute synchronously. If a custom layout executing is time cunsuming and should be resolved to some ticks synchronously，the layout should contains a member property named enableTick, and this change would support for rerendering on each tick.
Document change on antvis/g6#12
Closes #1653
=> Custom layout ticking

docs/manual/tutorial/elements.zh.md
=> docs: opt?-->edge

package.json
https://github.com/antvis/gatsby-theme-antv/releases/tag/0.10.66
=> docs: fix gallery demo url

src/shape/shapeBase.ts, stories/Shape/component/loseStateStyle.tsx, stories/Shape/shape.stories.tsx
修复设置状态过程中会导致原始样式丢失的问题 https://github.com/antvis/G6/issues/1741
=> fix: lose the state style

package.json, src/graph/graph.ts, stories/Issues/changeData/index.tsx, stories/Issues/ggeditorNode/baseNode.ts, tests/unit/graph/controller/customGroup-spec.ts
=> fix: remove lodash dependencies

src/index.ts, src/interface/shape.ts, src/shape/shape.ts, src/shape/xml.ts, stories/Shape/component/xml.tsx, stories/Shape/shape.stories.tsx, tests/unit/shape/nodes/xml-spec.ts
=> feat: register node from xml description

examples/interaction/customBehavior/demo/dragCanvasTwoFingers.js, examples/interaction/customBehavior/index.en.md, examples/interaction/customBehavior/index.zh.md
=> docs: fix customBehavior demo

examples/tool/contextMenu/demo/contextMenu.js
修复上下文菜单demo中，拖动画布后菜单位置问题 #1801
=> docs: fix contextmenu demo

CHANGELOG.md, examples/interaction/partialResponse/demo/partialNode.js, package.json, src/global.ts, src/graph/controller/event.ts, src/graph/controller/item.ts, src/graph/graph.ts, src/interface/graph.ts, tests/unit/graph/controller/event-spec.ts
1、增加 graph.priorityState API，用于提升状态的优先级；
2、G6 Event 支持 name:eventType 形式。
=> feat: graph.priorityState & event mode

.travis.yml, src/behavior/behaviorOption.ts, src/behavior/index.ts, src/behavior/lasso-select.ts, src/util/path.ts, stories/Interaction/component/lasso-select.tsx, stories/Interaction/interaction.stories.tsx, tests/unit/behavior/lasso-select-spec.ts
Add lasso behavior. Test and demo are included.
=> feat: add lasso behavior

docs/api/Event.en.md, docs/api/Event.zh.md, docs/manual/middle/states/defaultBehavior.en.md, docs/manual/middle/states/defaultBehavior.zh.md
Add docs for lasso behavior.
增加拉索选框的文档。
=> docs: add docs for lasso behavior

.travis.yml, docs/api/Plugins.en.md, docs/api/Plugins.zh.md, docs/manual/middle/Plugins.en.md, docs/manual/middle/Plugins.zh.md, examples/tool/fisheye/demo/fisheye.js, examples/tool/fisheye/demo/fisheyeStyle.js, examples/tool/fisheye/demo/meta.json, examples/tool/fisheye/index.en.md, examples/tool/fisheye/index.zh.md, examples/tool/tooltip/index.en.md, gatsby-browser.js, src/graph/controller/item.ts, src/plugins/fisheye/index.ts
=> docs: add fisheye demos, docs, and API.

docs/api/Graph.en.md, docs/api/Graph.zh.md, docs/api/nodeEdge/Node.en.md, docs/api/nodeEdge/Node.zh.md
=> docs: add docs for getNeighbors

src/graph/graph.ts
=> fix: clear not clean combos.

src/algorithm/detect-cycle.ts
=> fix: self-loop / root node cycle detection in undirected graph

package.json, src/plugins/grid/index.ts
=> fix: grid plugin dom class name.

examples/item/customNode/demo/cardNode.js, examples/item/customNode/demo/intervalChartNode.js, examples/item/customNode/demo/lineChartNode.js, examples/item/customNode/demo/meta.json, examples/item/customNode/demo/pointChartNode.js, examples/item/customNode/index.en.md, examples/item/customNode/index.zh.md, gatsby-browser.js, package.json, stories/Shape/component/interval-chart.tsx, stories/Shape/component/line-chart.tsx, stories/Shape/component/multi-chart.tsx, stories/Shape/component/pie-chart.tsx, stories/Shape/component/point-chart.tsx, stories/Shape/shape.stories.tsx
=> feat: add statistical chart nodes

src/plugins/menu/index.ts
=> fix: menu plugin clickHandler problem 

package.json, src/behavior/click-select.ts, src/behavior/collapse-expand-combo.ts, src/behavior/drag-combo.ts, src/behavior/drag-node.ts, src/behavior/tooltip-base.ts, src/shape/nodes/circle.ts, src/shape/nodes/diamond.ts, src/shape/nodes/ellipse.ts, src/shape/nodes/modelRect.ts, src/shape/nodes/rect.ts, src/shape/nodes/star.ts, src/shape/nodes/triangle.ts, src/shape/shapeBase.ts, stories/Shape/component/polyline.tsx, tests/unit/state/update-element-states-spec.ts
1、状态支持修改箭头样式：https://github.com/antvis/G6/issues/1917
2、Behavior 中增加了元素 destroy 的判断：https://github.com/antvis/G6/issues/1918
3、修复 option 为 null 导致的错误：https://github.com/antvis/G6/issues/1910
=> fix: arrow state & linkpoint

src/shape/shape.ts, src/shape/xml.ts, stories/Shape/component/xml.tsx, tests/unit/shape/nodes/xml-spec.ts
=> fix: xml node state style not correct

CHANGELOG.md, package.json, src/global.ts
=> docs: update changelog & version number

package.json, webpack.config.js
=> chore: 🆙 upgrade worker-loader to 3.x

.github/workflows/preview.yml
支持 PR 预览服务：https://github.com/afc163/surge-preview
=> test: add surge-preview action

.github/workflows/rebase.yml
=> chore: add rebase action

package.json, src/algorithm/layoutProbMap.ts, src/graph/graph.ts, src/interface/graph.ts, stories/Layout/component/auto-layout.tsx, stories/Layout/layout.stories.tsx, tests/unit/graph/auto-layout-spec.ts, tests/unit/graph/data/auto-layout-test0.ts, tests/unit/graph/data/auto-layout-test1.ts, tests/unit/graph/data/auto-layout-test2.ts, tests/unit/graph/data/auto-layout-test3.ts, tests/unit/graph/data/auto-layout-test4.ts, tests/unit/graph/data/auto-layout-test5.ts, tests/unit/graph/data/auto-layout-test6.ts, tests/unit/graph/data/auto-layout-test7.ts, tests/unit/graph/data/auto-layout-test8.ts
=> feat: auto-layout

src/graph/graph.ts, src/shape/hull/bubbleset.ts, src/util/math.ts, src/util/path.ts, tests/unit/graph/graph-hull-spec.ts, tests/unit/shape/hull/bubble-spec.ts, tests/unit/util/math-spec.ts
- 补充增加 hull 单元测试
- 修正 pointRectSquareDist 函数
=> test: graph-hull-spec, math-spec

api-extractor.json, src/api.ts
=> feat: add smart tip for g6 code

package.json, src/index.ts, src/interface/shape.ts, src/shape/shape.ts, src/shape/xml.ts, stories/Shape/component/xml.tsx, stories/Shape/shape.stories.tsx, tests/unit/shape/nodes/xml-spec.ts
=> Feat：Node xml

package.json, src/index.ts, src/interface/shape.ts, src/item/item.ts, src/shape/shape.ts, src/shape/xml.ts, stories/Shape/component/xml.tsx, stories/Shape/shape.stories.tsx, tests/unit/shape/nodes/xml-spec.ts
=> feat: Support for defining nodes using JSX-like syntax 

package.json, src/item/item.ts
修复 https://github.com/antvis/G6/issues/1963 问题
=> fix: img state

docs/api/Algorithm.en.md, docs/api/Algorithm.zh.md, docs/api/Graph.en.md, docs/api/Graph.zh.md, examples/interaction/hull/demo/changeMembers.js, examples/interaction/hull/demo/hull.js, examples/interaction/hull/demo/meta.json, examples/interaction/hull/index.en.md, examples/interaction/hull/index.zh.md
=> docs: add api docs for algorithms and hull

api-extractor.json, docs/manual/middle/jsx-node.en.md, docs/manual/middle/jsx-node.zh.md, examples/item/customNode/demo/meta.json, examples/item/customNode/demo/pieChartNode.js, examples/item/customNode/demo/pointChart.js, src/api.ts, stories/Shape/component/interval-chart.tsx, stories/Shape/component/line-chart.tsx, stories/Shape/component/multi-chart.tsx, stories/Shape/component/pie-chart.tsx, stories/Shape/component/point-chart.tsx, stories/Shape/component/xml.tsx
1. 使用类 JSX 语法定义节点的说明文档；
2. 节点中嵌入饼图的案例。
=> feat: docs & demos of chart node

docs/manual/middle/jsx-node.en.md, docs/manual/middle/jsx-node.zh.md
docs: update the english version of jsx-node doc.
=> docs: update the english version of jsx-node doc.

docs/api/Algorithm.en.md, docs/api/Algorithm.zh.md, examples/interaction/createEdge/index.en.md
- 订正 getConnectedComponents  文档，issue #1986
- 订正 create edge demo 标题
=> fix: docs for getConnectedComponents;fix:example title for create edge

docs/api/Algorithm.en.md, docs/api/Algorithm.zh.md, src/algorithm/index.ts, src/algorithm/pagerank.ts, src/interface/graph.ts, stories/Algorithm/algo.stories.tsx, stories/Algorithm/component/pagerank.tsx, tests/unit/algorithm/pagerank-spec.ts
=> feat: pagerank algorithm

docs/api/Graph.en.md, docs/api/Graph.zh.md, src/behavior/create-edge.ts, tests/unit/behavior/create-edge-spec.ts
修复 create-edge Behavior 问题： https://github.com/antvis/G6/issues/1976
添加 stack 操作相关的方法的文档。
=> fix: create-edge behavior & stack docs

CHANGELOG.md, src/behavior/drag-node.ts, src/graph/controller/item.ts, src/graph/graph.ts, src/plugins/toolBar/index.ts, stories/Plugins/component/toolbar.tsx, tests/unit/graph/graph-spec.ts, tests/unit/plugins/toolbar-spec.ts
=> fix: redo & undo state

examples/tool/tooltip/demo/meta.json, examples/tool/tooltip/demo/tooltipLocal.js, examples/tool/tooltip/demo/tooltipLocalCustom.js, examples/tool/tooltip/demo/tooltipPluginLocal.js, gatsby-config.js
=> docs: update tooltip demos.

docs/manual/getting-started.en.md, docs/manual/getting-started.zh.md
用 basement 上提供的 cdn 地址，格式比较标准。
=> docs: update g6 cdn link

CHANGELOG.md, package.json, src/global.ts, src/plugins/menu/index.ts
fix: the position of the context menu before showing up
=> fix: the position of the context menu before showing up

docs/manual/middle/overview.en.md
Chinese to English translation
=> Chinese to English translation

src/plugins/timeBar/timeBarSlice.ts, src/plugins/timeBar/timeBarTooltip.ts, stories/Plugins/component/timebar-slice.tsx, stories/Plugins/component/timebar.tsx, stories/Plugins/plugins.stories.tsx
feat: slice type timebar and tooltp for timebar.
=> feat: slice type timebar and tooltp for timebar.

CHANGELOG.md, docs/api/Event.en.md, docs/api/Event.zh.md, docs/api/Plugins.en.md, docs/api/Plugins.zh.md, docs/manual/middle/Plugins.en.md, docs/manual/middle/Plugins.zh.md, examples/tool/edgeFilterLens/demo/edgeFilter.js, examples/tool/edgeFilterLens/demo/edgeFilterConfig.js, examples/tool/edgeFilterLens/demo/meta.json, examples/tool/edgeFilterLens/index.en.md, examples/tool/edgeFilterLens/index.zh.md, examples/tool/fisheye/index.en.md, examples/tree/customItemTree/demo/customEdgeTree.js, package.json, src/behavior/create-edge.ts, src/global.ts, src/graph/controller/event.ts, src/index.ts, src/plugins/edgeFilterLens/index.ts, src/plugins/fisheye/index.ts, src/plugins/index.ts, stories/Plugins/component/edge-filter.tsx, stories/Plugins/plugins.stories.tsx, tests/unit/plugins/edge-filter-lens-spec.ts
=> feat: edge filter lens.

src/shape/edges/polyline-util.ts, src/shape/edges/polyline.ts, src/shape/edges/router.ts, stories/Layout/component/dagre-layout.tsx, stories/Shape/component/polyline-combo.tsx, stories/Shape/component/polyline.tsx, stories/Shape/shape.stories.tsx, tests/unit/shape/edges/polyline-spec.ts
- 改进 polyline 边类型，通过配置支持避障、支持设置允许方向和转角（默认直角）；(在 options 中新增了routeCfg属性)
一般使用默认配置即可，不需要进行额外设置。
```
interface RouterCfg {
gridSize?: number;
obstacles?: Item[];
maxAllowedDirectionChange?: number; // 允许的最大转角
directions?: any[]; // 允许的边的方向
startDirections?: string[]; // 边从点出发的方向（e.g. 从上拐 / 从下拐）
penalties?: {}; // 附加的分数
distFunc?: (p1: PolyPoint, p2: PolyPoint) => number;
fallbackRoute?: (p1: PolyPoint, p2: PolyPoint) => PolyPoint[]; // 若找不到符合要求的路径时的退化路径方案
maximumLoops?: number;
}
```
- 修复了 原 Polyline 在 Combo 变化时的问题 https://stackblitz.com/edit/react-4bddqk?file=index.js
=> fix: polyline 

CHANGELOG.md, examples/tool/timebar/demo/simple-timebar.js, examples/tool/timebar/demo/slice-timebar.js, examples/tool/timebar/demo/timebar.js, gatsby-browser.js, src/plugins/timeBar/controllerBtn.ts, src/plugins/timeBar/handler.ts, src/plugins/timeBar/index.ts, src/plugins/timeBar/timeBarSlice.ts, src/plugins/timeBar/timeBarTooltip.ts, src/plugins/timeBar/timeButton.ts, src/plugins/timeBar/trend.ts, src/plugins/timeBar/trendTimeBar.ts, src/shape/nodes/modelRect.ts, tests/unit/plugins/edge-filter-lens-spec.ts, tests/unit/shape/nodes/modelRect-spec.ts
1、更新 changelog；
2、修复刻度时间轴播放报错问题；
3、处理合并上个pr出现的问题。
=> fix: slice time error

docs/api/nodeEdge/Item.zh.md, gatsby-config.js, site/pages/graphmarker.en.tsx, site/pages/graphmarker.zh.tsx, site/pages/index.zh.tsx
=> feat: add graphmarker nav

docs/api/Event.en.md, docs/api/Event.zh.md, docs/manual/introduction.en.md, docs/manual/introduction.zh.md, gatsby-config.js, site/pages/graphmarker.zh.tsx, src/behavior/drag-node.ts
1、拖动节点结束后，emit dragendnode 事件：https://github.com/antvis/G6/issues/2150
2、文档中增加基于 G6 & Angular 的编辑器链接：https://github.com/antvis/G6/issues/2137
=> Update doc 0925

src/behavior/drag-canvas.ts, src/types/index.ts, tests/unit/behavior/index-spec.ts
fix the below issue:
https://github.com/antvis/G6/issues/816
=> fix(behavior): support the drag-canvas behavior on the mobile device

package.json, src/global.ts, src/graph/graph.ts, src/shape/edges/router.ts, tests/unit/behavior/create-edge-spec.ts
1. create-edge 创建 polyline 类型边时不报错 https://github.com/antvis/G6/issues/2165
2. 创建节点、边或 combo，当存在重复的 ID 时，提示信息中突出显示重复的 ID。
=> fix: create-edge polyline

CHANGELOG.md, src/item/edge.ts, stories/Issues/edgeStatus/index.tsx, stories/Issues/issues.stories.tsx, tests/unit/state/edge-state-spec.ts
1、bugFix：https://github.com/antvis/G6/issues/2142
2、TimeBar Docs；
=> fix: bug fix & timebar docs

docs/api/Plugins.zh.md, examples/tool/timebar/demo/slice-timebar.js, examples/tool/timebar/index.zh.md, site/pages/graphmarker.zh.tsx, src/plugins/timeBar/index.ts, src/plugins/timeBar/timeBarSlice.ts, src/plugins/timeBar/trend.ts, src/plugins/timeBar/trendTimeBar.ts, src/types/index.ts
1、补充 TimeBar 的中文文档；
2、刻度 TimeBar 的配置项和类型由 slice 改成 tick；
3、GraphMarker 嵌入到 ifream 中允许导出文件。
=> fix: timebar docs

docs/api/Plugins.zh.md, docs/manual/middle/Plugins.zh.md, examples/tool/timebar/demo/simple-timebar.js, examples/tool/timebar/demo/slice-timebar.js, examples/tool/timebar/demo/timebar.js
=> fix: 同步文档及demo

src/graph/graph.ts
=> fix: add watermarker cros

CHANGELOG.md, package.json, src/global.ts
=> fix: Upgrade g-canvas

src/behavior/collapse-expand.ts, src/behavior/zoom-canvas.ts
修复移动端下 node click 和 zoom-canvas behaviors 冲突的问题 https://github.com/antvis/G6/issues/2255
=> fix: node click conflict with zoom-canvas

src/layout/gpu/graphinForce.ts, src/layout/gpu/graphinForceShader.ts, src/util/layout.ts
kernel1 输出每个节点数据时，压缩 offset 和边数目到一个 float32 分量中
=> fix: 修改 aveMovement kernel

docs/api/Event.zh.md
=> fix: 修改文档错误

CHANGELOG.md, package.json, src/global.ts
=> chore: update the version number; docs: update the CHANGELOG

docs/api/Algorithm.en.md, docs/api/Algorithm.zh.md, examples/algorithm/shortestPath/demo/colorSets.js, examples/algorithm/shortestPath/demo/labelPropagation.js, examples/algorithm/shortestPath/demo/louvain.js, examples/algorithm/shortestPath/demo/meta.json, package.json, src/algorithm/label-propagation.ts, src/global.ts, src/item/node.ts, stories/Algorithm/algo.stories.tsx, stories/Algorithm/component/colors.tsx
=> docs: add louvain, lp, and colorset demos

gatsby-node.js, package.json
bugfix：https://github.com/antvis/G6/issues/2329
=> fix: update g-webgpu version

gatsby-node.js, package.json, src/global.ts
=> Fix webgpu

examples/case/largeGraph/demo/index.js
codesandbox does not support optional chaining operator.
=> fix: run error in codesandbox

docs/design/case.en.md, docs/design/component/componentOverview.en.md, docs/design/component/timebar.en.md, docs/design/component/viewToolbar.en.md, docs/design/global/interactive.en.md, docs/design/global/style.en.md, docs/design/overview.en.md, docs/design/overview.zh.md, docs/design/principles.en.md, docs/design/template.en.md
- docs: english version of design overview
=> docs: english version of design overview

packages/core/package.json, packages/core/src/index.ts, packages/core/src/interface/graph.ts, packages/core/src/interface/index.ts, packages/core/src/types/index.ts, packages/core/tests/unit/graph/graph-spec.ts, packages/pc/tsconfig.json
=> Sprint unpack 1215

packages/core/src/shape/shapeBase.ts, packages/core/src/types/index.ts, packages/pc/package.json, packages/pc/src/behavior/click-select.ts, packages/pc/src/behavior/drag-node.ts, packages/pc/src/index.ts, packages/pc/src/util/layout.ts, packages/pc/stories/Hull/component/hull.tsx, packages/pc/tests/unit/algorithm/adjacent-matrix-spec.ts, packages/pc/tests/unit/algorithm/connected-component-spec.ts, packages/pc/tests/unit/behavior/active-relations-spec.ts, packages/pc/tests/unit/behavior/brush-select-spec.ts, packages/pc/tests/unit/behavior/collapse-expand-combo-spec.ts, packages/pc/tests/unit/behavior/collapse-expand-spec.ts, packages/pc/tests/unit/behavior/create-edge-spec.ts, packages/pc/tests/unit/behavior/drag-canvas-spec.ts, packages/pc/tests/unit/behavior/drag-combo-spec.ts, packages/pc/tests/unit/behavior/drag-node-spec.ts, packages/pc/tests/unit/behavior/lasso-select-spec.ts, packages/pc/tests/unit/behavior/select-spec.ts, packages/pc/tests/unit/behavior/shortcuts-call-spec.ts, packages/pc/tests/unit/behavior/tooltip-spec.ts, packages/pc/tests/unit/behavior/zoom-spec.ts, packages/pc/tsconfig.json
=> test: behaviors; fix: combo state size problem

src/algorithm/structs/queue/index.ts, src/graph/controller/mode.ts, src/graph/graph.ts, tsconfig.json
修复当实例化 Graph 时不设置 modes，直接使用 graph.addBehaviors 增加 Behavior 不生效的问题。
=> Sprint 1211

src/interface/graph.ts
=> fix: eslint

packages/core/package.json
Fix es entry for G6-core build
=> fix: g6-core es module entry

src/plugins/toolBar/index.ts
for issue [#2315 ](https://github.com/antvis/G6/issues/2315)
=> fix(toolbar): support the use of toolbar in firefox and other browsers

packages/core/src/index.ts, packages/element/package.json, packages/element/src/edges/polyline-util.ts, packages/element/src/edges/polyline.ts, packages/element/src/edges/router.ts, packages/element/src/nodes/circle.ts, packages/element/src/nodes/diamond.ts, packages/element/src/nodes/ellipse.ts, packages/element/src/nodes/image.ts, packages/element/src/nodes/modelRect.ts, packages/element/src/nodes/rect.ts, packages/element/src/nodes/star.ts, packages/element/src/nodes/triangle.ts, packages/pc-plugins/package.json
=> fix: element package use g6-core

packages/core/package.json, packages/core/src/global.ts, packages/element/package.json, packages/g6/package.json, packages/pc/package.json, packages/pc/src/global.ts, packages/plugin/package.json
=> chore: version numbers

packages/g6/webpack.config.js, packages/pc/package.json, packages/pc/src/graph/controller/layout.ts, packages/pc/src/layout/worker/layout.worker.ts, packages/pc/src/layout/worker/work.ts, packages/pc/webpack.config.js
=> feat: 嵌入式 worker

packages/g6/package.json, packages/g6/src/index.ts
=> fix: update g6 package version

packages/core/package.json, packages/core/src/global.ts, packages/core/src/graph/graph.ts, packages/core/src/types/index.ts, packages/core/tests/unit/graph/graph-spec.ts, packages/pc/src/behavior/drag-node.ts, packages/pc/src/graph/controller/layout.ts, packages/pc/src/layout/worker/layout.worker.ts, packages/pc/src/layout/worker/work.ts, packages/pc/tests/unit/behavior/drag-node-spec.ts, packages/pc/tests/unit/layout/circular-web-worker-spec.ts, packages/plugin/src/toolBar/index.ts
1、修复通过 graph.addItem 添加节点后，调用 graph. getNodeDegree 报错的问题： https://github.com/antvis/G6/issues/2679
2、webworker 布局支持用户配置脚本路径： https://github.com/antvis/G6/issues/2678
3、修复 drag-node 时设置 onlyChangeComboSize 为true，放置到 node 上时不生效的问题：https://github.com/antvis/G6/issues/2676
4、Toolbar 组件 undo 初始点击问题：https://github.com/antvis/G6/issues/2635
=> fix：getNodeDegree & webworker support custom script url

packages/core/src/graph/graph.ts
=> fix: code fix "degees" -> "degress"

packages/core/package.json, packages/core/src/global.ts
g6-core 中增加 tslib 依赖，解决该问题 https://github.com/antvis/G6/issues/2702
=> fix: add tslib dependencies

README-zh_CN.md, README.md, packages/core/README-zh_CN.md, packages/core/README.md, packages/core/src/types/index.ts, packages/core/src/util/base.ts, packages/core/tests/unit/graph/svg-spec.ts, packages/core/tests/unit/util/path-spec.ts, packages/element/README-zh_CN.md, packages/element/README.md, packages/g6/README-zh_CN.md, packages/g6/README.md, packages/pc/README-zh_CN.md, packages/pc/README.md, packages/pc/tests/unit/algorithm/adjacent-matrix-spec.ts, packages/pc/tests/unit/behavior/drag-node-spec.ts, packages/pc/tests/unit/issues-spec.ts, packages/pc/tests/unit/layout/dagre-spec.ts, packages/pc/tests/unit/layout/destroy-layout-spec.ts, packages/pc/tests/unit/layout/random-spec.ts, packages/pc/tests/unit/layout/web-worker-spec.ts, packages/pc/tests/unit/state/image-node-spec.ts, packages/plugin/tests/unit/bundling-spec.ts, packages/plugin/tests/unit/menu-spec.ts, packages/plugin/tests/unit/timebar-spec.ts
- remove deprecated docs
- remove unused codes
- codes releated with `ShapeStyle` not changed, it will work after `core` released
=> fix(tests): fix some untyped codes and unused descriptions

packages/site/docs/manual/FAQ/angular-support.en.md, packages/site/docs/manual/FAQ/angular-support.zh.md
- [x ] commit message follows commit guidelines
Add Angular Support Document and error solution
添加Angular支持文档
=> Angular support doc

packages/core/src/graph/controller/layout.ts, packages/core/src/graph/graph.ts, packages/core/src/types/index.ts, packages/pc/package.json, packages/pc/src/graph/controller/layout.ts, packages/pc/src/layout/worker/layout.worker.ts, packages/pc/tests/unit/graph/fitView-spec.ts, packages/pc/tests/unit/graph/svg-spec.ts, packages/pc/tests/unit/layout/circular-spec.ts, packages/pc/tests/unit/layout/circular-web-worker-spec.ts, packages/pc/tests/unit/layout/combo-force-spec.ts, packages/pc/tests/unit/layout/concentric-spec.ts, packages/pc/tests/unit/layout/dagre-spec.ts, packages/pc/tests/unit/layout/destroy-layout-spec.ts, packages/pc/tests/unit/layout/force-spec.ts, packages/pc/tests/unit/layout/fruchterman-spec.ts, packages/pc/tests/unit/layout/gpu-spec.ts, packages/pc/tests/unit/layout/grid-spec.ts, packages/pc/tests/unit/layout/layout-mechanism-spec.ts, packages/pc/tests/unit/layout/mds-spec.ts, packages/pc/tests/unit/layout/pipes-spec.ts, packages/pc/tests/unit/layout/preset-spec.ts, packages/pc/tests/unit/layout/radial-spec.ts, packages/pc/tests/unit/layout/random-spec.ts, packages/pc/tests/unit/state/state-update-spec.ts, packages/plugin/tests/unit/bundling-spec.ts, packages/plugin/tests/unit/minimap-spec.ts
=> add feature: layout pipes

CHANGELOG.md, packages/core/package.json, packages/core/src/global.ts, packages/core/src/graph/controller/layout.ts, packages/element/package.json, packages/g6/package.json, packages/g6/src/index.ts, packages/pc/package.json, packages/pc/src/global.ts, packages/pc/src/graph/controller/layout.ts, packages/plugin/package.json, packages/site/package.json
fix: layout with fitView after pipes refactor
=> fix: layout with fitView after pipes refactor

packages/core/src/graph/graph.ts, packages/core/src/util/path.ts, packages/core/src/util/validation.ts, packages/core/tests/unit/graph/controller/item-spec.ts, packages/core/tests/unit/graph/graph-spec.ts, packages/core/tests/unit/graph/svg-spec.ts, packages/core/tests/unit/util/validation-spec.ts, packages/pc/src/graph/tree-graph.ts, packages/pc/tests/unit/behavior/drag-node-spec.ts, packages/pc/tests/unit/graph/graph-spec.ts, packages/pc/tests/unit/graph/svg-spec.ts, packages/pc/tests/unit/graph/tree-graph-spec.ts
=> fix: validation graph data

packages/site/docs/manual/middle/elements/combos/defaultCombo.zh.md
=> fix: doc type

packages/core/src/graph/graph.ts, packages/core/src/util/validation.ts, packages/core/tests/unit/util/validation-spec.ts, packages/pc/tests/unit/behavior/create-edge-spec.ts
https://github.com/antvis/G6/issues/2786
修复 https://github.com/antvis/G6/issues/2788 中提示信息问题
=> fix: The error message of create edge behavior is getmodel is not a function

CHANGELOG.md, packages/core/src/element/edge.ts, packages/core/src/graph/graph.ts, packages/core/tests/unit/issues-spec.ts
1、修复更新 startArrow 为 false 的问题 #2814 
2、修复 createCombo 时候没有给相关节点和 combo 添加 comoId 或 parentId 的问题 #2815
=> fix: faild to update startArrow & createCombo bug

packages/mobile/src/behavior/zoom-canvas.ts
- [√ ] `npm test` passes
- [√] tests and/or benchmarks are included
- [√ ] commit message follows commit guidelines
优化mobile的zoom-canvas behavior，降低缩放速度，修改缩放相对的点为两个缩放坐标中间。
=> refactor(mobile): modify zoom point & speed

packages/mobile/src/behavior/zoom-canvas.ts
- [√ ] `npm test` passes
- [√ ] tests and/or benchmarks are included
- [√] commit message follows commit guidelines
修复第一次缩放时，缩放比例不正确问题
=> fix(mobile): fix first zoom problem

packages/mobile/src/behavior/zoom-canvas.ts
- [√ ] `npm test` passes
- [√ ] tests and/or benchmarks are included
- [√ ] commit message follows commit guidelines
使用透传的scale计算缩放
=> fix: 每次使用实时的zoom计算缩放

README-zh_CN.md, README.md, packages/core/README-zh_CN.md, packages/core/package.json, packages/element/README-zh_CN.md, packages/g6/README-zh_CN.md, packages/pc/README-zh_CN.md, packages/pc/package.json, packages/pc/tests/unit/organization-spec.ts, packages/site/docs/manual/introduction.zh.md, packages/site/docs/manual/middle/layout/ai-layout.en.md, packages/site/docs/manual/middle/layout/ai-layout.zh.md, packages/site/examples/net/aiLayout/API.en.md, packages/site/examples/net/aiLayout/API.zh.md, packages/site/examples/net/aiLayout/demo/layoutPrediction.js, packages/site/examples/net/aiLayout/demo/meta.json, packages/site/examples/net/aiLayout/index.en.md, packages/site/examples/net/aiLayout/index.zh.md, packages/site/examples/tool/snapline/demo/meta.json, packages/site/gatsby-browser.js, packages/site/package.json
=> fix: add AI Layout Prediction demo and docs

packages/core/src/types/index.ts, packages/pc/src/behavior/activate-relations.ts, packages/pc/src/behavior/drag-node.ts
Add G6Event types references to [#2629](https://github.com/antvis/G6/issues/2629#issuecomment-780999876)
Add touch event listeners for activate-relations & drag-node behavior
=> fix(behavior): touch support for activate-relations & drag-node

packages/site/examples/case/simpleCase/demo/mindmap.js
fix mindmap interaction bug cause add children failed
=> fix: mindmap example bug

packages/pc/src/graph/graph.ts
=> fix(graph/fitView): add container width and height without config

packages/core/src/types/index.ts, packages/pc/src/behavior/activate-relations.ts, packages/pc/src/behavior/drag-canvas.ts, packages/pc/src/behavior/drag-node.ts, packages/pc/tests/unit/behavior/active-relations-spec.ts, packages/pc/tests/unit/behavior/drag-node-spec.ts
=> Add test touch behavior

packages/core/src/graph/controller/view.ts, packages/plugin/src/grid/index.ts
- [?] commit message follows commit guidelines
修复flex布局下grid错位的问题
添加网格跟随画布移动
=> feat: grid follow

packages/site/docs/api/Event.en.md
=> fix(docs): English Event docs typo

packages/plugin/src/imageMinimap/index.ts
=> fix(image-minimap): user-select style

packages/pc/src/graph/tree-graph.ts
=> fix: treeGraph.removeChild should not generate an undo record

packages/react-node/src/Animation/animate.ts, packages/react-node/src/Animation/animateFunc.ts, packages/react-node/src/Example/animate.md, packages/react-node/src/ReactNode/Group.tsx, packages/react-node/src/Register/event.ts, packages/react-node/src/Register/register.tsx, packages/site/docs/manual/middle/elements/nodes/react-node.en.md, packages/site/docs/manual/middle/elements/nodes/react-node.zh.md
Add react custom node doc in site;
站点新增react定义节点文档
=> docs: add react custom node doc

packages/plugin/src/menu/index.ts, packages/plugin/src/toolBar/index.ts, packages/plugin/src/tooltip/index.ts
add document checking
related issue https://github.com/antvis/G6/issues/2891
related pr https://github.com/antvis/algorithm/pull/32
=> feat: support ssr detecting

packages/site/docs/manual/FAQ/faq.en.md, packages/site/docs/manual/FAQ/faq.zh.md
ref: https://g6.antv.vision/zh/docs/manual/FAQ/faq
---
It seems that another submission is also automatically merged into this PR. . . just fixed some type definition errors
=> docs(site): Fix the error of the FAQ reference link on the site

CHANGELOG.md, packages/core/src/graph/graph.ts, packages/core/src/interface/graph.ts, packages/pc/tests/unit/graph/updateLayout-align-spec.ts
=> feat: updateLayout with align and alignPoint;

packages/plugin/src/bundling/index.ts, packages/plugin/src/edgeFilterLens/index.ts, packages/plugin/src/fisheye/index.ts, packages/plugin/src/grid/index.ts, packages/plugin/src/imageMinimap/index.ts, packages/plugin/src/legend/index.ts, packages/plugin/src/menu/index.ts, packages/plugin/src/minimap/index.ts, packages/plugin/src/timeBar/index.ts, packages/plugin/src/toolBar/index.ts, packages/plugin/src/tooltip/index.ts
=> fix(plugin): Fix the bug that the constructor of each plugin under the plugin package did not declare the type correctly

packages/site/docs/api/graphFunc/state.en.md, packages/site/docs/api/graphFunc/state.zh.md
=> docs(site): 修复 G6 状态管理最佳实践引用链接错误

packages/core/src/graph/controller/view.ts, packages/core/src/graph/graph.ts, packages/core/src/util/math.ts, packages/core/tests/unit/graph/matrix-related-spec.ts
=> feat: matrix transform related functions for g-migrate

packages/core/src/graph/controller/view.ts, packages/core/src/graph/graph.ts, packages/core/src/interface/graph.ts
fitView在设置minZoom时,较小分辨率下缩放失败,添加提示告知.
=> style: fitView 缩放失败,添加日志;

packages/react-node/src/Register/event.ts
onDBClick 需要绑定到正确的事件名`dblclick`
=> react-node onDBClick 绑定的事件名 dbclick 不正确，修改为 dblclick

CHANGELOG.md, packages/core/package.json, packages/core/src/element/shapeBase.ts, packages/core/src/global.ts, packages/element/package.json, packages/g6/package.json, packages/g6/src/index.ts, packages/pc/package.json, packages/pc/src/global.ts, packages/plugin/package.json, packages/site/package.json
fix: update edge to be horizontal and the label is on wrong position;
=> fix: update edge to be horizontal and the label is on wrong position;

CHANGELOG.md, packages/core/src/types/index.ts, packages/site/docs/api/Items/comboMethods.en.md, packages/site/docs/api/Items/comboMethods.zh.md, packages/site/docs/api/graphFunc/combo.en.md, packages/site/docs/api/graphFunc/combo.zh.md, packages/site/docs/api/graphFunc/hull.en.md, packages/site/docs/api/graphFunc/hull.zh.md, packages/site/docs/manual/middle/elements/combos/defaultCombo.en.md, packages/site/docs/manual/middle/elements/combos/defaultCombo.zh.md
=> docs: refine docs

CHANGELOG.md, packages/g6/package.json, packages/g6/src/index.ts
=> fix: version refine

packages/core/src/graph/controller/view.ts, packages/core/src/graph/graph.ts, packages/core/src/interface/graph.ts, packages/core/src/types/index.ts, packages/core/tests/unit/graph/controller/view-spec.ts, packages/pc/src/behavior/drag-canvas.ts, packages/site/docs/api/graphFunc/transform.en.md, packages/site/docs/api/graphFunc/transform.zh.md
=> perf drag canvas behavior, add view api fitViewByRule

packages/site/docs/api/TreeGraph.en.md, packages/site/docs/api/TreeGraph.zh.md, packages/site/docs/api/graphLayout/guide.en.md, packages/site/docs/api/graphLayout/guide.zh.md, packages/site/docs/manual/middle/layout/graph-layout.zh.md
=> docs: fix 404 url

packages/core/src/graph/graph.ts, packages/core/src/interface/graph.ts, packages/pc/src/behavior/zoom-canvas.ts
This is to support animation in the zoomTo function (quite easy at this point)
Additionally, I updated the zoom-canvas behavior to support the new animation
=> feat: add animated zoomTo

.github/ISSUE_TEMPLATE/bug_report_chinese.yml
docs: update chinese version bug report template
=> docs: update chinese version bug report template

packages/site/docs/api/Plugins.zh.md, packages/site/docs/manual/middle/plugins/Plugins.zh.md
=> docs: update chinese docs bug

packages/plugin/src/tooltip/index.ts
=> feat: tooltip 支持动态dom

packages/plugin/src/menu/index.ts
=> fix:  support touchend event  menu插件适配移动端，支持touchend事件

packages/pc/src/behavior/click-select.ts
feat: onCanvasClick in 'click-select' supports 'shouldBegin' option
=> feat: onCanvasClick in click-select supports 'shouldBegin' option

CHANGELOG.md, packages/core/package.json, packages/core/src/global.ts, packages/element/package.json, packages/g6/package.json, packages/g6/src/index.ts, packages/pc/package.json, packages/pc/src/global.ts, packages/pc/src/graph/graph.ts, packages/plugin/package.json, packages/plugin/src/tooltip/index.ts, packages/plugin/tests/unit/tooltip-spec.ts, packages/site/package.json
fix: tooltip with wrong duplicated child DOM nodes;
=> fix: tooltip with wrong duplicated child DOM nodes;

packages/core/src/graph/controller/layout.ts
=> fix: fix the hidden combos not set correctly

packages/pc/src/layout/index.ts, packages/pc/src/layout/worker/layout.worker.ts
=> chore: register dagreCompound layout

packages/core/src/element/node.ts
=> fix：#3513 切换节点文字位置，文字位置出现错误

CHANGELOG.md, packages/core/package.json, packages/core/src/global.ts, packages/core/src/graph/graph.ts, packages/element/package.json, packages/g6/package.json, packages/g6/src/index.ts, packages/pc/package.json, packages/pc/src/global.ts, packages/plugin/package.json
fix: layoutController is null problem;
=> fix: layoutController is null problem;

packages/core/src/types/index.ts, packages/pc/src/behavior/scroll-canvas.ts, packages/site/docs/manual/middle/states/defaultBehavior.en.md, packages/site/docs/manual/middle/states/defaultBehavior.zh.md
…vas behavior
- support meta and key combination to trigger zoom for scroll-canvas behavior
=> feat: support meta and key combination to trigger zoom for scroll-canvas behavior

packages/core/src/graph/graph.ts
- Consider the origin attributes for position animation
https://user-images.githubusercontent.com/7285903/158567977-99ea5860-1c23-4828-aa59-e0ed2f3117ce.mp4
https://user-images.githubusercontent.com/7285903/158567965-d0f6a6f7-2586-4644-b6a7-edcb9589a31d.mp4
=> fix: position animate considers origin attributes

packages/core/src/graph/graph.ts, packages/core/src/interface/graph.ts, packages/core/src/types/index.ts, packages/core/tests/unit/behavior/select-spec.ts, packages/pc/src/behavior/brush-select.ts, packages/pc/src/behavior/drag-canvas.ts, packages/plugin/src/timeBar/timeBarSlice.ts, packages/plugin/src/timeBar/trendTimeBar.ts
Added types for graph event names. Using `types` instead of `enums`  ([enum usage currently](https://github.com/antvis/G6/blob/master/packages/core/src/types/index.ts#L586))
Why `types` over `enum`s? 
- With types, user's of G6 do not need to import an enum into their file for type safety.
- `types` are "zero-cost", they do not produce JS code during build time/production. `enum`s produce JS code which makes the JS bundle bigger. More details in "References" section below.
- using enums would make it easier for users of typescript to read the documentation and copy/paste examples of using event handlers because the event name is just a string, whereas if we used enum's it gets a little more complicated
**1. While using `graph.on` , I am not getting autocompletion in my IDE for the event …
=> enhancement: add types for graph event names

packages/core/tests/unit/graph/svg-spec.ts
=> test: add node label test cases

CHANGELOG.md, packages/core/package.json, packages/core/src/global.ts, packages/core/src/graph/graph.ts, packages/core/src/interface/graph.ts, packages/core/src/types/index.ts, packages/core/tests/unit/graph/svg-spec.ts, packages/element/package.json, packages/g6/package.json, packages/g6/src/index.ts, packages/pc/package.json, packages/pc/src/behavior/brush-select.ts, packages/pc/src/behavior/drag-canvas.ts, packages/pc/src/global.ts, packages/plugin/package.json, packages/plugin/src/timeBar/timeBarSlice.ts, packages/plugin/src/timeBar/trendTimeBar.ts
=> chore: update versions

packages/pc/src/behavior/zoom-canvas.ts, packages/pc/tests/unit/behavior/zoom-spec.ts
=> fix: zoom-canvas take the maximum and minimum values

packages/site/docs/api/graphFunc/render.en.md, packages/site/docs/api/graphFunc/render.zh.md
=> docs: 修复graph.addItem，graph.removeItem和graph.changeData超链接错误

packages/site/docs/manual/middle/elements/advanced-style/set-label-bg.en.md, packages/site/docs/manual/middle/elements/advanced-style/set-label-bg.zh.md, packages/site/package.json
=> docs: docs refine

CHANGELOG.md, packages/core/package.json, packages/core/src/global.ts, packages/core/src/graph/graph.ts, packages/element/package.json, packages/g6/package.json, packages/g6/src/index.ts, packages/pc/package.json, packages/pc/src/global.ts, packages/plugin/package.json
perf: optimize the performance of combo graph first rendering;
=> perf: optimize the performance of combo graph first rendering;

packages/core/src/graph/controller/view.ts, packages/core/src/graph/graph.ts, packages/core/src/util/graphic.ts, packages/core/src/util/math.ts
With this PR I'm reimplementing the animated fitView function. As pointed out in https://github.com/antvis/G6/pull/3770 there were some issues with the sequence of animations.
With this change, the function will do a single smooth animation including both the translate and zoom operations
https://user-images.githubusercontent.com/2861371/179204002-a715b979-aaa7-4de7-b5d5-31fb753db801.mp4
=> feat: rework animated fitView

CHANGELOG.md, packages/core/package.json, packages/core/src/global.ts, packages/element/package.json, packages/g6/package.json, packages/g6/src/index.ts, packages/pc/package.json, packages/pc/src/global.ts, packages/plugin/package.json, packages/site/package.json
=> docs: update CHANGELOG

packages/core/src/element/combos/circle.ts
Adds missing logic for using fixCollapseSize for circle combo
Fixes https://github.com/antvis/G6/issues/3798
=> fix: fixCollapseSize for circle combo

packages/pc/src/graph/controller/layout.ts
=> fix:Add success call in layoutWithWorker

CHANGELOG.md, packages/core/package.json, packages/core/src/global.ts, packages/core/src/graph/controller/layout.ts, packages/core/src/graph/controller/view.ts, packages/core/src/graph/graph.ts, packages/core/src/interface/graph.ts, packages/core/tests/unit/graph/controller/view-spec.ts, packages/element/package.json, packages/g6/package.json, packages/g6/src/index.ts, packages/pc/package.json, packages/pc/src/global.ts, packages/pc/src/graph/controller/layout.ts, packages/pc/tests/unit/layout/dagre-spec.ts, packages/pc/tsconfig.json, packages/plugin/package.json, packages/site/docs/api/graphFunc/transform.en.md, packages/site/docs/api/graphFunc/transform.zh.md, packages/site/docs/manual/middle/elements/nodes/jsx-node.en.md, packages/site/examples/item/customNode/demo/card.js
fix: combo collapsed edge problems, closes: #3839;
=> fix: combo collapsed edge problems, closes: #3839;

packages/site/docs/api/registerLayout.en.md, packages/site/docs/api/registerLayout.zh.md
=> doc: fix custom-layout url broken

packages/site/docs/api/Items/itemProperties.en.md, packages/site/docs/api/Items/itemProperties.zh.md, packages/site/docs/api/graphFunc/on_off.en.md, packages/site/docs/api/graphFunc/on_off.zh.md
=> docs: fix the wrong path

packages/core/src/graph/graph.ts, packages/site/docs/api/Event.en.md
With this change, the user is able to react to stackevent changes triggered by specific operations
=> feat: more descriptive stackchange events

packages/core/src/graph/controller/item.ts, packages/core/src/graph/graph.ts, packages/pc/src/behavior/drag-node.ts
I tried to optimize a little the performances by removing unnecessary operations and comparisons. 
The commits should be self-explanatory
=> feat: performance tweaks

CHANGELOG.md, packages/core/package.json, packages/core/src/global.ts, packages/core/src/graph/controller/item.ts, packages/core/src/graph/graph.ts, packages/element/package.json, packages/g6/package.json, packages/g6/src/index.ts, packages/pc/package.json, packages/pc/src/behavior/drag-node.ts, packages/pc/src/global.ts, packages/plugin/package.json, packages/plugin/src/annotation/index.ts, packages/site/package.json
- fix: Annotation readData with inexistent item;
=> fix: Annotation readData with inexistent item;

CHANGELOG.md, packages/core/package.json, packages/core/src/global.ts, packages/element/package.json, packages/g6/package.json, packages/g6/src/index.ts, packages/pc/package.json, packages/pc/src/global.ts, packages/plugin/package.json, packages/plugin/src/annotation/index.ts, packages/site/package.json
feat: getPlaceholder for Annotation plugin;
=> feat: getPlaceholder for Annotation plugin;

CHANGELOG.md, packages/core/package.json, packages/core/src/element/shapeBase.ts, packages/core/src/global.ts, packages/core/src/types/index.ts, packages/core/src/util/graphic.ts, packages/element/package.json, packages/g6/package.json, packages/g6/src/index.ts, packages/pc/package.json, packages/pc/src/global.ts, packages/pc/tests/unit/issues-loop-spec.ts, packages/plugin/package.json, packages/site/docs/manual/middle/elements/edges/built-in/loop.en.md, packages/site/docs/manual/middle/elements/edges/built-in/loop.zh.md, packages/site/package.json
- feat: pointPadding config for loop edges with non-circle nodes, closes: #3974;
- fix: image lost while updating the size for an image node, closes: #3938;
=> fix: image lost while updating the size for an image node, closes: #3938;

packages/plugin/package.json, packages/site/gatsby-browser.js, packages/site/package.json
=> chore: refine

README.en-US.md, README.md
chore: update dingtalk group code img
=> chore: update dingtalk group code img

README.en-US.md, README.md, packages/core/README.en-US.md, packages/core/README.md, packages/element/README-zh_CN.md, packages/element/README.md, packages/g6/README.en-US.md, packages/g6/README.md, packages/pc/README-zh_CN.md, packages/pc/README.md
docs: update the website urls in readme to antgroup
=> docs: update the website urls in readme to antgroup

CHANGELOG.md, packages/core/package.json, packages/core/src/global.ts, packages/element/package.json, packages/g6/package.json, packages/g6/src/index.ts, packages/pc/package.json, packages/pc/src/behavior/drag-node.ts, packages/pc/src/global.ts, packages/plugin/package.json, packages/site/.dumirc.ts, packages/site/package.json
- fix: error occurs while dragging combo with drag-node behavior;
=> fix: error occurs while dragging combo with drag-node behavior;

packages/site/.dumirc.ts
=> docs: update site advertises

packages/site/docs/api/graphFunc/download.en.md, packages/site/docs/api/graphFunc/download.zh.md
docs: update error docs for downloadFullImage API
=> docs: update error docs for downloadFullImage API

packages/site/docs/api/Plugins.en.md, packages/site/docs/api/Plugins.zh.md, packages/site/docs/manual/middle/plugins/Plugins.en.md, packages/site/docs/manual/middle/plugins/Plugins.zh.md
docs: update minimap doc with hideEdge config
=> docs: update minimap doc with hideEdge config

packages/site/docs/manual/middle/states/defaultBehavior.zh.md
=> docs:修正drag-canvas说明文档

packages/site/docs/manual/middle/elements/edges/custom-edge.en.md, packages/site/docs/manual/middle/elements/edges/custom-edge.zh.md, packages/site/docs/manual/middle/elements/nodes/custom-node.en.md, packages/site/docs/manual/middle/elements/nodes/custom-node.zh.md, packages/site/docs/manual/middle/states/defaultBehavior.en.md, packages/site/docs/manual/middle/states/defaultBehavior.zh.md, packages/site/examples/case/graphDemos/demo/sequence.js
docs: perf deocs for custom node and custom edge
=> docs: perf deocs for custom node and custom edge

packages/site/docs/api/graphFunc/transform.zh.md, packages/site/docs/manual/middle/layout/graph-layout.en.md, packages/site/docs/manual/middle/layout/graph-layout.zh.md
=> docs: perf doc table

packages/site/docs/manual/middle/elements/edges/defaultEdge.zh.md
=> fix: fix edge doc bug

packages/site/docs/manual/FAQ/vite-support.en.md, packages/site/docs/manual/FAQ/vite-support.zh.md, packages/site/examples/case/treeDemos/demo/decisionTree2.js, packages/site/examples/case/treeDemos/demo/meta.json, packages/site/examples/item/customNode/demo/cardNode.js
docs: add a decision tree demo
=> docs: add a decision tree demo

packages/core/package.json, packages/core/src/interface/index.ts, packages/core/src/types/animate.ts, packages/core/src/types/combo.ts, packages/core/src/types/common.ts, packages/core/src/types/data.ts, packages/core/src/types/edge.ts, packages/core/src/types/graph.ts, packages/core/src/types/index.ts, packages/core/src/types/item.ts, packages/core/src/types/layout.ts, packages/core/src/types/node.ts, packages/core/src/types/spec.ts, packages/core/src/types/view.ts
=> feat: add necessary types

packages/site/.dumirc.ts
=> chore: fix homepage url

packages/core/package.json, packages/core/src/index.ts, packages/core/src/item/item.ts, packages/core/src/runtime/controller/data.ts, packages/core/src/runtime/controller/extension.ts, packages/core/src/runtime/controller/interaction.ts, packages/core/src/runtime/controller/item.ts, packages/core/src/runtime/controller/layout.ts, packages/core/src/runtime/controller/theme.ts, packages/core/src/runtime/graph.ts, packages/core/src/runtime/hooks.ts, packages/core/src/stdlib/behavior/drag-canvas.ts, packages/core/src/stdlib/index.ts, packages/core/src/types/behavior.ts, packages/core/src/types/graph.ts, packages/core/src/types/hook.ts, packages/core/src/types/item.ts, packages/core/src/types/spec.ts, packages/core/src/types/stdlib.ts, packages/core/src/util/extend.ts, packages/core/src/util/extension.ts, packages/core/tests/unit/behavior-spec.ts
chore: behavior type generic and test;
chore: update notes;
=> chore: behavior type generic and test; chore: update notes;

packages/g6/docs/api-ts/classes/_graph_.graph.md, packages/g6/docs/api-ts/globals.md, packages/g6/docs/api-ts/index.md, packages/g6/docs/api-ts/modules/_graph_.md, packages/g6/package.json, packages/g6/sidebars.js, packages/g6/src/runtime/controller/data.ts, packages/g6/src/runtime/graph.ts, packages/g6/src/types/graph.ts, packages/g6/src/types/hook.ts, packages/g6/src/util/extension.ts
feat: implement add remove and update API for graph data module
=> feat: implement add remove and update API for graph data module

packages/site/.dumirc.ts, packages/site/package.json
=> fix: doc search for site

CHANGELOG.md, packages/core/package.json, packages/core/src/global.ts, packages/core/src/util/graphic.ts, packages/element/package.json, packages/g6/package.json, packages/g6/src/index.ts, packages/pc/package.json, packages/pc/src/behavior/drag-node.ts, packages/pc/src/global.ts, packages/plugin/package.json, packages/site/package.json
fix: loop edge position for custom rect node, closes: #4236;
=> fix: loop edge position for custom rect node, closes: #4236;

packages/site/docs/manual/middle/elements/nodes/custom-node.en.md, packages/site/docs/manual/middle/elements/nodes/custom-node.zh.md, packages/site/examples/item/customNode/demo/svgDom.js
=> fix: docs error

packages/site/.dumi/pages/largegraph.en.tsx, packages/site/.dumi/pages/largegraph.zh.tsx, packages/site/package.json, packages/site/pages/canvas-menu.tsx, packages/site/pages/large-graph-register.tsx, packages/site/pages/largegraph.tsx, packages/site/pages/legend-panel.tsx
=> fix: large graph demo page

packages/g6/package.json, packages/g6/src/item/edge.ts, packages/g6/src/item/item.ts, packages/g6/src/item/node.ts, packages/g6/src/runtime/controller/interaction.ts, packages/g6/src/runtime/controller/item.ts, packages/g6/src/runtime/graph.ts, packages/g6/src/stdlib/behavior/click-select.ts, packages/g6/src/stdlib/behavior/drag-canvas.ts, packages/g6/src/stdlib/index.ts, packages/g6/src/types/behavior.ts, packages/g6/src/types/event.ts, packages/g6/src/util/canvas.ts, packages/g6/src/util/event.ts, packages/g6/tests/unit/click-select-spec.ts
add behavior controller and click-select:
=> feat: add behavior controller and click-select

packages/g6/src/item/edge.ts, packages/g6/src/item/item.ts, packages/g6/src/runtime/controller/item.ts, packages/g6/tests/unit/item-spec.ts
=> feat: edge state styles

packages/g6/src/item/item.ts, packages/g6/src/item/node.ts, packages/g6/src/runtime/controller/data.ts, packages/g6/src/runtime/controller/interaction.ts, packages/g6/src/runtime/controller/item.ts, packages/g6/src/runtime/graph.ts, packages/g6/src/stdlib/behavior/brush-select.ts, packages/g6/src/stdlib/behavior/click-select.ts, packages/g6/src/stdlib/behavior/lasso-select.ts, packages/g6/src/stdlib/index.ts, packages/g6/src/stdlib/selector/lasso.ts, packages/g6/src/stdlib/selector/rect.ts, packages/g6/src/types/graph.ts, packages/g6/src/types/hook.ts, packages/g6/src/types/item.ts, packages/g6/src/util/array.ts, packages/g6/src/util/item.ts, packages/g6/src/util/shape.ts, packages/g6/tests/unit/behaviors/brush-select-spec.ts, packages/g6/tests/unit/behaviors/lasso-select-spec.ts
feat: add brush select behavior and its test spec
=> feat: add brush select behavior and its test spec

packages/site/examples/interaction/treeBehavior/demo/changeData.js
docs: tree changeData demo problem
=> docs: tree changeData demo problem

packages/site/docs/manual/tutorial/plugins.en.md
Replace Chinese words to English in English version docs
=> docs: Fix a typo in plugins.en.md

packages/plugin/src/tooltip/index.ts
=> fix: tooltip top position error   #4410

CHANGELOG.md, packages/core/package.json, packages/core/src/global.ts, packages/core/src/interface/shape.ts, packages/element/package.json, packages/g6/package.json, packages/g6/src/index.ts, packages/pc/package.json, packages/pc/src/global.ts, packages/pc/src/graph/tree-graph.ts, packages/pc/src/layout/worker/layout.ts, packages/plugin/package.json, packages/plugin/src/timeBar/index.ts, packages/plugin/src/tooltip/index.ts, packages/site/docs/manual/middle/elements/combos/custom-combo.en.md, packages/site/docs/manual/middle/elements/combos/custom-combo.zh.md, packages/site/examples/interaction/combo/demo/cRect.js, packages/site/examples/item/customCombo/demo/cRect.js
fix: type for draw function in elements, closes: #4395
=> fix: type for draw function in elements, closes: #4395

package.json, packages/g6/package.json, packages/g6/src/runtime/controller/data.ts, packages/g6/src/stdlib/behavior/activate-relations.ts, packages/g6/src/stdlib/index.ts, packages/g6/src/types/index.ts, packages/g6/tests/datasets/const.ts, packages/g6/tests/index.html, packages/g6/tests/intergration/behaviors/activate-relations.ts, packages/g6/tests/intergration/behaviors/brush-select.ts, packages/g6/tests/intergration/behaviors/click-select.ts, packages/g6/tests/intergration/index.ts, packages/g6/tests/intergration/layouts/circular.ts, packages/g6/tests/main.ts, packages/g6/vite.config.js
- add activate-relations behavior
- add demo：  `npm run dev`
=> feat: activate relations

CHANGELOG.md, packages/core/package.json, packages/core/src/global.ts, packages/element/package.json, packages/g6/package.json, packages/g6/src/index.ts, packages/pc/package.json, packages/pc/src/global.ts, packages/pc/src/graph/controller/layout.ts, packages/plugin/package.json
fix: update layout from animate false to true;
=> fix: update layout from animate false to true;

packages/g6/package.json, packages/g6/src/item/edge.ts, packages/g6/src/item/item.ts, packages/g6/src/item/node.ts, packages/g6/src/runtime/controller/item.ts, packages/g6/src/runtime/graph.ts, packages/g6/src/stdlib/behavior/drag-canvas.ts, packages/g6/src/stdlib/behavior/zoom-canvas.ts, packages/g6/src/stdlib/index.ts, packages/g6/src/util/item.ts, packages/g6/tests/unit/behaviors/drag-canvas-spec.ts, packages/g6/tests/unit/behaviors/zoom-canvas-spec.ts
=> feat: drag-canvas behavior

packages/plugin/package.json, packages/plugin/src/timeBar/index.ts, packages/plugin/tests/unit/timebar-spec.ts
timebar 新增了 `putInGraphContainer` 参数
默认为 true ，即与当前行为保持一致，将 timebar 置于 Graph Container 中
为 false 时，会将 timebar 置于给定 container 中
=> feat: timebar 新增putInGraphContainer属性决定是否将timebar置于graph container 中

packages/core/src/element/shapeBase.ts
=> fix: remove label if no longer present

CHANGELOG.md
=> perf: update changelog

.github/ISSUE_TEMPLATE/issue_hunt.yml, .github/ISSUE_TEMPLATE/issue_hunt_chinese.yml
=> chore: fix issue hunt template errors

CHANGELOG.md, packages/core/package.json, packages/core/src/global.ts, packages/element/package.json, packages/g6/package.json, packages/g6/src/index.ts, packages/pc/package.json, packages/pc/src/global.ts, packages/plugin/package.json
=> chore: upgrade layout for umd

packages/site/.dumi/pages/g6v5.en.tsx, packages/site/.dumirc.ts, packages/site/pages/g6v5-demo-controller.tsx, packages/site/pages/g6v5-demo-small.tsx, packages/site/pages/g6v5-demo-utils.tsx, packages/site/pages/g6v5-demo.less, packages/site/pages/g6v5-demo.tsx
docs: add small v5 demo to site
=> docs: add small v5 demo to site

packages/site/package.json, packages/site/pages/g6v5-demo-controller.tsx, packages/site/pages/g6v5-demo-utils.tsx, packages/site/pages/g6v5-demo.less, packages/site/pages/g6v5-demo.tsx
=> chore: g6 v5 demo update

README.en-US.md, README.md
=> docs: add readme to v5

packages/pc/src/layout/worker/layout.ts, packages/site/docs/api/Event.en.md, packages/site/docs/api/Event.zh.md, packages/site/docs/api/graphLayout/guide.en.md, packages/site/docs/api/graphLayout/guide.zh.md, packages/site/docs/manual/middle/layout/webworker.en.md, packages/site/docs/manual/middle/layout/webworker.zh.md
=> fix: layout url

packages/g6/src/stdlib/item/node/base.ts
大幅提升交互（hover）时 Circle 和 Text 的渲染性能：
https://github.com/antvis/G/issues/1356
更新 `g-webgl` 即可。
=> fix: enhance performance with batch key

README.md
=> docs: update readme for 66

packages/site/package.json
=> chore: update g6 v5 for site

packages/site/.dumirc.ts, packages/site/pages/g6v5-demo-controller.tsx
=> docs: update site

README.en-US.md, README.md, packages/g6/package.json, packages/g6/src/item/edge.ts
=> fix: drag-node error

packages/site/.dumi/pages/g6v5.zh.tsx, packages/site/pages/g6v5-demo-controller.tsx, packages/site/pages/g6v5-demo.less
=> docs: v5 demo add star link

CHANGELOG.md, packages/core/package.json, packages/core/src/global.ts, packages/element/package.json, packages/g6/package.json, packages/g6/src/index.ts, packages/pc/package.json, packages/pc/src/behavior/zoom-canvas.ts, packages/pc/src/global.ts, packages/plugin/package.json, packages/site/package.json, packages/site/pages/g6v5-demo-small.tsx
fix: scroll delta for old version of firefox;
=> fix: scroll delta for old version of firefox;

packages/g6/package.json, packages/pc/package.json, packages/plugin/package.json
=> chore: update version num

README.en-US.md, README.md, packages/g6/package.json, packages/g6/src/item/node.ts, packages/g6/src/runtime/controller/item.ts, packages/g6/src/stdlib/item/node/base.ts, packages/g6/src/stdlib/theme/dark.ts, packages/g6/src/stdlib/theme/light.ts, packages/g6/src/types/node.ts, packages/g6/tests/intergration/index.ts, packages/g6/tests/intergration/performance/performance.ts, packages/g6/tests/intergration/visual/visual.ts
chore: upgrade styles for node
根据设计师走查，更新色板和视觉规范
=> chore: upgrade styles for node

README.en-US.md, README.md, packages/g6/package.json, packages/g6/src/stdlib/item/node/base3d.ts, packages/g6/src/stdlib/item/node/index.ts, packages/g6/src/stdlib/item/node/rect.ts, packages/g6/tests/intergration/index.ts
fix: implement onZoom as empty function for 3d node
=> fix: implement onZoom as empty function for 3d node

packages/site/docs/manual/tutorial/plugins.zh.md
=> docs: update plugins.zh.md

packages/g6/src/runtime/controller/interaction.ts, packages/g6/src/util/event.ts
feat: add contextmenu event for graph canvas, node, and edge
=> feat: add contextmenu event for graph canvas, node, and edge

packages/site/.dumirc.ts
=> chore: update ga to v4

packages/core/src/graph/graph.ts, packages/core/src/types/index.ts, packages/site/docs/api/Event.en.md, packages/site/docs/api/Event.zh.md
改动内容，如题描述。项目中需要监听 beforedestroy，去做一些外部的事件监听移除~
=> feat(events): `graph.destroy` 增加 beforedestroy and afterdestroy lifecycle events

CHANGELOG.md, packages/core/package.json, packages/core/src/global.ts, packages/element/package.json, packages/g6/package.json, packages/g6/src/index.ts, packages/pc/package.json, packages/pc/src/global.ts, packages/plugin/package.json, packages/site/package.json
chore: unify the version num for sub packages
=> chore: unify the version num for sub packages

packages/g6/src/stdlib/index.ts, packages/g6/src/stdlib/plugin/fisheye/index.ts, packages/g6/src/stdlib/plugin/menu/index.ts, packages/g6/src/stdlib/plugin/tooltip/index.ts, packages/g6/tests/intergration/plugins/fisheye.ts
fix: fisheye restore problem and code style
=> fix: fisheye restore problem and code style

CHANGELOG.md, packages/core/package.json, packages/core/src/global.ts, packages/core/src/graph/graph.ts, packages/core/src/item/combo.ts, packages/element/package.json, packages/g6/package.json, packages/g6/src/index.ts, packages/pc/package.json, packages/pc/src/global.ts, packages/plugin/package.json, packages/site/docs/manual/middle/elements/methods/lock-node.en.md, packages/site/docs/manual/middle/elements/methods/lock-node.zh.md, packages/site/package.json
fix: parent combo size problem, closes: #4734
=> fix: parent combo size problem, closes: #4734

packages/site/.dumi/pages/v5combo.en.tsx, packages/site/.dumi/pages/v5combo.zh.tsx, packages/site/package.json
=> docs: add combo demo to site

packages/pc/src/index.ts
FYI, `npm test` failed on master as well.
Fix the type of `IAlgorithm`
For type A and type B:
`A & B` extends `A` extends `A | B`
=> fix: type of `IAlgorithm`

packages/g6/src/stdlib/plugin/menu/index.ts, packages/g6/src/stdlib/plugin/tooltip/index.ts
=> fix: fix tooltip and menu position

packages/g6/src/api-doc/item.ts, packages/g6/src/stdlib/item/node/base3d.ts
export BaseNode3D as CustomNode3D
=> v5 docs base3d

packages/g6/package.json, packages/site/docs/manual/getting-started.zh.md, packages/site/docs/manual/introduction.en.md, packages/site/docs/manual/introduction.zh.md, packages/site/docs/manual/tutorial/behavior.en.md, packages/site/docs/manual/tutorial/behavior.zh.md, packages/site/docs/manual/tutorial/elements.en.md, packages/site/docs/manual/tutorial/elements.zh.md, packages/site/docs/manual/tutorial/example.en.md, packages/site/docs/manual/tutorial/example.zh.md, packages/site/docs/manual/tutorial/layout.en.md, packages/site/docs/manual/tutorial/layout.zh.md, packages/site/docs/manual/tutorial/preface.en.md, packages/site/docs/manual/tutorial/preface.zh.md
chore: update beta version url
=> chore: update beta version url

packages/site/examples/interaction/customBehavior/demo/meta.json, packages/site/examples/interaction/dragCanvasHideItem/demo/meta.json, packages/site/examples/interaction/highlight/demo/meta.json, packages/site/examples/interaction/label/demo/meta.json, packages/site/examples/interaction/partialResponse/demo/meta.json, packages/site/examples/interaction/position/demo/meta.json, packages/site/examples/interaction/treeBehavior/demo/meta.json, packages/site/examples/net/forceDirected/demo/basicForce.js, packages/site/examples/scatter/changePosition/demo/meta.json
chore: update site screenshots
=> chore: update site screenshots

packages/site/docs/manual/tutorial/behavior.en.md, packages/site/docs/manual/tutorial/behavior.zh.md, packages/site/docs/manual/tutorial/elements.en.md, packages/site/docs/manual/tutorial/elements.zh.md, packages/site/docs/manual/tutorial/example.en.md, packages/site/docs/manual/tutorial/example.zh.md, packages/site/docs/manual/tutorial/layout.en.md, packages/site/docs/manual/tutorial/layout.zh.md, packages/site/docs/manual/tutorial/plugins.en.md, packages/site/docs/manual/tutorial/plugins.zh.md, packages/site/examples/feature/features/demo/webgl3d.js
=> chore: update data urls

packages/site/docs/manual/new-features.en.md, packages/site/docs/manual/new-features.zh.md, packages/site/docs/manual/upgrade.en.md, packages/site/docs/manual/upgrade.zh.md, packages/site/examples/interaction/hull/demo/hull.js, packages/site/examples/interaction/hull/demo/meta.json, packages/site/examples/item/defaultEdges/demo/meta.json, packages/site/examples/item/label/demo/labelLen.js, packages/site/examples/item/label/demo/labelLen1.js, packages/site/examples/item/label/demo/meta.json, packages/site/examples/tool/legend/demo/legend.ts, packages/site/examples/tool/legend/demo/legendCustomMarker.ts, packages/site/examples/tool/legend/demo/legendSVG.ts, packages/site/examples/tool/legend/demo/meta.json
=> docs: update

packages/site/docs/manual/introduction.en.md, packages/site/docs/manual/introduction.zh.md, packages/site/docs/manual/new-features.en.md, packages/site/docs/manual/new-features.zh.md, packages/site/examples/item/defaultNodes/demo/ellipse.js
=> chore: refine doc

packages/site/.dumirc.ts
=> docs: update news for site

packages/site/docs/manual/tutorial/preface.en.md, packages/site/docs/manual/tutorial/preface.zh.md
=> docs: fix doc url problem

README.md, README.zh-US.md
docs: update readme for v5 beta
=> docs: update readme for v5 beta

packages/plugin/src/menu/index.ts
=> fix: menu overflow

packages/pc/src/graph/tree-graph.ts, packages/pc/src/util/deepClone.ts
=> fix(tree-graph): 修复树图在大数据量情况下，使用 JSON.parse(JSON.stringify(()) 导致浏览器崩溃

packages/pc/src/graph/graph.ts
修复问题关联 [issue](https://github.com/antvis/G6/issues/4913#issuecomment-1704522837)
=> fix: 修正下载图片文件名与格式拼接不正确的问题

CHANGELOG.md, packages/core/package.json, packages/core/src/global.ts, packages/element/package.json, packages/g6/package.json, packages/g6/src/index.ts, packages/pc/package.json, packages/pc/src/global.ts, packages/plugin/package.json
=> chore: update version numbers

packages/g6/src/runtime/graph.ts, packages/g6/src/stdlib/behavior/drag-canvas.ts, packages/g6/src/stdlib/behavior/scroll-canvas.ts, packages/g6/src/stdlib/behavior/zoom-canvas.ts
feat: scroll-canvas support tile updating
=> feat: scroll-canvas support tile updating

packages/g6/src/runtime/graph.ts, packages/g6/src/stdlib/behavior/drag-canvas.ts, packages/g6/src/stdlib/behavior/scroll-canvas.ts, packages/g6/src/stdlib/behavior/zoom-canvas.ts, packages/g6/src/types/graph.ts, packages/g6/tests/integration/behaviors-scroll-canvas.spec.ts, packages/g6/tests/main.ts
feat: beforeitemchange timing events; fix: minimap update problems
=> feat: beforeitemchange timing events; fix: minimap update problems

packages/g6/src/stdlib/item/edge/base.ts, packages/g6/tests/demo/item/edge/line-edge.ts, packages/g6/tests/demo/layouts/force.ts
fix: edge label balance size problem
=> fix: edge label balance size problem

packages/site/docs/manual/getting-started.zh.md
=> [Doc]: Update getting-started.zh.md

packages/pc/src/behavior/activate-relations.ts
允许用户配置第二次点击的时候取消选中状态，参考[issue4917](https://github.com/antvis/G6/issues/4917)
=> feat:  add a node for the second click and uncheck it

packages/pc/src/behavior/brush-select.ts
修复在combo内无法框选，参考[issue4999](https://github.com/antvis/G6/issues/4999)
=> feat: fix inability to implement box selection within combo

packages/plugin/src/timeBar/handler.ts
=> fix: 设置简单模式下高亮颜色，避免事件穿透

CHANGELOG.md, packages/core/package.json, packages/core/src/global.ts, packages/element/package.json, packages/g6/package.json, packages/g6/src/index.ts, packages/pc/package.json, packages/pc/src/global.ts, packages/plugin/package.json
docs: update changelog and version nums
=> docs: update changelog and version nums

packages/site/.dumirc.ts
=> docs: update docs

packages/g6/src/stdlib/plugin/lodController/index.ts, packages/g6/src/types/index.ts, packages/site/examples/case/graphDemos/demo/edgeBundling.js, packages/site/examples/feature/features/demo/wasmLayouts.js
[fix: fix issue that lodController options.debounce may not exists](https://github.com/antvis/G6/commit/b6c85c1170ca99a8b47a77c9c6f56ad6c3eb73e5)
[fix: fix issue that Behavior be exported as type](https://github.com/antvis/G6/commit/878f8d9b1f42bd80a0dc935b4ff2d9109744706a)
[fix: fix issue that wasm layout demo cannot find graph](https://github.com/antvis/G6/commit/125335fe9377ff4c6f46520fae43b1bc1f4dcabe)
[fix: fix typo](https://github.com/antvis/G6/commit/176457cfa471698ae016aea4fefd598bdb793a18)
=> fix: fix issues about examples

packages/site/.dumirc.ts, packages/site/package.json
=> chore: update dumi-theme-antv

packages/g6/src/item/item.ts, packages/g6/src/util/data.ts, packages/g6/tests/demo/item/node/donut-node.ts
bugfix:
1. 完善 encode mapper 局部更新机制
encode 类型的 mapper 对应的某一 shape，如果没有在 inner data 中初始化即 `[shapeId: string] = {}`，更新时会被丢弃
2. 修复 show 元素时异步更新导致缓存丢失的问题
3. 修改数据处理器默认激活的生命周期。从 read 更新为 all
```ts
const AVAILABLE_DATA_LIFECYCLE = [
'read',
'changeData',
'updateData',
'addData',
'removeData',
];
```
=> fix: Improve local update mechanism of encode mapper

packages/site/.dumirc.ts
=> docs: image position

packages/g6/src/runtime/controller/data.ts, packages/g6/src/runtime/controller/item.ts, packages/g6/src/runtime/graph.ts, packages/g6/src/types/data.ts, packages/g6/src/util/data.ts, packages/site/examples/feature/features/demo/lodLevels.js, packages/site/examples/feature/features/demo/rendererSwitch.js
fix: transforms should not be executed when update positions
=> fix: transforms should not be executed when update positions

packages/g6/src/item/combo.ts, packages/g6/src/runtime/controller/item.ts, packages/g6/src/runtime/controller/plugin.ts, packages/g6/src/stdlib/data/transformV4Data.ts, packages/site/examples/net/arcDiagram/demo/basicArcDiagram.js, packages/site/examples/net/arcDiagram/demo/circularArcDiagram.js, packages/site/examples/net/compactBox/demo/compactBoxLeftAlign.js, packages/site/examples/net/concentricLayout/demo/basicConcentric.js, packages/site/examples/net/gridLayout/demo/grid.js, packages/site/examples/net/indented/demo/filesystem.js
fix: combo ancestor update problem
=> fix: combo ancestor update problem

.github/workflows/deploy.yml, README.en-US.md, README.md
=> docs: update readme

packages/site/docs/design/global/interactive.en.md
=> fix: fix docs embed link

packages/site/docs/design/global/interactive.en.md
=> fix: fix embed link error

packages/g6/src/runtime/controller/interaction.ts, packages/g6/src/stdlib/theme/dark.ts, packages/g6/src/stdlib/theme/light.ts
=> feat: remove default image

.github/workflows/deploy.yml, package.json, packages/g6-plugin-map-view/.eslintrc, packages/g6-plugin-map-view/package.json, packages/g6-plugin-map-view/tsconfig.json, packages/site/.dumirc.ts, packages/site/CNAME, pnpm-lock.yaml
创建 v5 分支 deploy workflow
* react-node 暂未加入构建队列，待 https://github.com/antvis/G6/pull/5079 合并后加入
=> chore: config v5 deploy workflow

packages/site/examples/feature/features/demo/layerTopology.js, packages/site/examples/feature/features/demo/meta.json, packages/site/examples/feature/features/demo/tournament.js
#5094 feat: 新增比赛流程图demo
[screenity.webm](https://github.com/antvis/G6/assets/39400058/7ede8b60-28b2-433e-a315-7260af14e534)
=> feat: add tournament demo

packages/site/examples/net/gpuLayout/demo/fruchtermanComplexData.js
=> fix(site): fix site demo of fruchterman complex data

.github/ISSUE_TEMPLATE/oscp.yml
=> chore: add oscp template

.github/workflows/auto_close_issue.yml
=> chore: add auto close issue workflow on master branch

.github/ISSUE_TEMPLATE/oscp.yml
=> chore: add oscp template to master branch

packages/site/CNAME
=> chore: update CNAME of master branch

README.md, README.zh-CN.md
=> chore: fix readme typo

packages/g6-plugin-map-view/package.json
=> chore: update map view peer dependencies version

.npmrc, packages/react-node/package.json, pnpm-lock.yaml
=> chore: remove npmrc

.husky/pre-commit, package.json, packages/g6-plugin-map-view/package.json, packages/g6/package.json, packages/site/package.json, pnpm-lock.yaml
=> chore: update project lint staged config

packages/site/docs/manual/tutorial/behavior.en.md, packages/site/docs/manual/tutorial/behavior.zh.md, packages/site/docs/manual/tutorial/elements.en.md, packages/site/docs/manual/tutorial/elements.zh.md, packages/site/docs/manual/tutorial/layout.en.md, packages/site/docs/manual/tutorial/layout.zh.md, packages/site/docs/manual/tutorial/preface.en.md, packages/site/docs/manual/tutorial/preface.zh.md, packages/site/docs/manual/tutorial/quick-start.en.md, packages/site/docs/manual/tutorial/quick-start.zh.md
relative issue: https://github.com/antvis/G6/issues/5229
正式版暂未发布
=> docs: update g6 umd link

README.en-US.md, README.md, packages/react-node/README.md, packages/site/docs/manual/tutorial/quick-start.en.md, packages/site/docs/manual/tutorial/quick-start.zh.md
=> docs: update g6 version and react-node usage

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/bug_report_chinese.yml, .github/ISSUE_TEMPLATE/issue_hunt_chinese.yml
=> chore: update issue template

packages/site/.dumi/global.less, packages/site/.dumirc.ts, packages/site/docs/manual/upgrade.en.md, packages/site/docs/manual/upgrade.zh.md, packages/site/package.json, pnpm-lock.yaml
* 更新 v4 升级 v5 文档中的错误
* 修复无法正常显示的图片
* 右侧导航支持滚动
=> docs: update upgrade docs

.vscode/settings.json, package.json, packages/react-node/package.json, packages/react-node/src/ReactNode/Shape/Text.tsx, packages/react-node/src/ReactNode/Shape/common.ts, pnpm-lock.yaml
修复 导致 `1.4.x` 版本 React Node 构建失败的问题
=> fix: fix react node issues

packages/site/examples/feature/features/demo/meta.json, packages/site/examples/feature/features/demo/tournament.js
=> chore: add screenshot for tournament

README.en-US.md, README.md
=> docs: add v5 tips in readme

packages/pc/src/behavior/tooltip-base.ts
=> fix tooltip-base.ts 返回值兼容

packages/g6/src/runtime/graph.ts, packages/g6/src/types/spec.ts, packages/g6/src/utils/dom.ts, packages/g6/tests/integration/auto-resize.spec.ts, packages/g6/tests/integration/snapshots/auto-resize/auto-resize.svg
- add autoResize options, default is `False`
=> feat: add autoResize option on graph

packages/g6/src/index.ts, packages/g6/src/spec/index.ts, packages/g6/src/spec/spec.ts
=> refactor(spec): adjust spec exports

packages/g6/__tests__/unit/runtime/data.spec.ts, packages/g6/__tests__/unit/utils/data.spec.ts, packages/g6/__tests__/unit/utils/diff.spec.ts, packages/g6/__tests__/unit/utils/graphlib.spec.ts, packages/g6/__tests__/unit/utils/id.spec.ts, packages/g6/__tests__/unit/utils/is.spec.ts, packages/g6/__tests__/unit/utils/traverse.spec.ts, packages/g6/src/elements/shapes/base-shape.ts, packages/g6/src/runtime/canvas.ts, packages/g6/src/runtime/data.ts, packages/g6/src/runtime/graph.ts, packages/g6/src/spec/data.ts, packages/g6/src/spec/index.ts, packages/g6/src/types/data.ts, packages/g6/src/types/edge.ts, packages/g6/src/types/element.ts, packages/g6/src/utils/animation.ts, packages/g6/src/utils/data.ts, packages/g6/src/utils/diff.ts, packages/g6/src/utils/graphlib.ts, packages/g6/src/utils/id.ts, packages/g6/src/utils/is.ts, packages/g6/src/utils/prefix.ts, packages/g6/src/utils/traverse.ts, packages/g6/tsconfig.json
* 新增 data controller，用于数据处理及更新
* 打开了 `strict` 模式
---
* Added a data controller for data processing and updating
* `strict` mode is enabled
=> feat: add data controller

packages/g6/__tests__/unit/registry.spec.ts, packages/g6/src/index.ts, packages/g6/src/preset.ts, packages/g6/src/registry/constants.ts, packages/g6/src/registry/index.ts, packages/g6/src/registry/types.ts
* 添加注册机制，目前只提供了大概框架，具体需要到每个部分可注册插件定义完成后调整
--- 
* Add registration mechanism. At present, only the general framework is provided, and the specific needs to be adjusted after each part can be registered plug-in definition
=> feat: add register mechanism

.github/workflows/build.yml, README.en-US.md, README.md, packages/g6/package.json
=> test: add coverage

packages/g6/__tests__/integration/snapshots/static/node-circle.svg, packages/g6/src/elements/nodes/base-node.ts, packages/g6/src/elements/nodes/circle.ts, packages/g6/src/elements/nodes/index.ts, packages/g6/src/elements/shapes/badge.ts, packages/g6/src/elements/shapes/base-shape.ts, packages/g6/src/elements/shapes/icon.ts, packages/g6/src/elements/shapes/label.ts, packages/g6/src/registry/types.ts
=> refactor: add node base class

packages/g6/src/runtime/controller/interaction.ts
=> fix: contextmenu event emit

.vscode/settings.json, packages/g6/__tests__/demo/static/controller-viewport.ts, packages/g6/__tests__/demo/static/index.ts, packages/g6/__tests__/demo/utils/assert.ts, packages/g6/__tests__/demo/utils/index.ts, packages/g6/__tests__/integration/snapshots/static/controller-viewport.svg, packages/g6/src/constants/events.ts, packages/g6/src/runtime/viewport.ts, packages/g6/src/types/index.ts, packages/g6/src/types/viewport.ts
* 新增 Viewport Controller，用于提供视图变换（平移、旋转、缩放）
---
* Add Viewport Controller to provide view transformations (pan, rotate, zoom)
=> feat: add viewport controller

packages/g6/__tests__/demo/static/index.ts, packages/g6/__tests__/demo/static/node-rect.ts, packages/g6/__tests__/integration/snapshots/static/node-rect.svg, packages/g6/src/elements/nodes/index.ts, packages/g6/src/elements/nodes/rect.ts, packages/g6/src/utils/element.ts
=> feat(v5): add rect node

packages/g6/__tests__/unit/spec/data.spec.ts, packages/g6/src/runtime/data.ts, packages/g6/src/runtime/element.ts, packages/g6/src/spec/data.ts, packages/g6/src/spec/index.ts, packages/g6/src/spec/spec.ts, packages/g6/src/types/data.ts
* 将 `DataOptions` 类型重命名为 `GraphData`
---
* Rename `DataOptions` to `GraphData`
=> refactor(spec): rename DataOptions to GraphData

packages/g6/__tests__/integration/snapshots/animation/controller-element-1000(3_3).svg, packages/g6/__tests__/integration/snapshots/animation/controller-element-200(2_3).svg, packages/g6/__tests__/integration/snapshots/animation/controller-element-50(1_3).svg, packages/g6/__tests__/integration/snapshots/animation/controller-element-state-0(1_2).svg, packages/g6/__tests__/integration/snapshots/animation/controller-element-state-1000(2_2).svg, packages/g6/__tests__/integration/snapshots/static/controller-element.svg, packages/g6/src/utils/element.ts
fix `isSameNode` function and update ut snapshots
=> fix: fix `isSameNode` function

packages/g6/src/elements/edges/base-edge.ts, packages/g6/src/elements/nodes/base-node.ts, packages/g6/src/elements/shapes/base-shape.ts, packages/g6/src/runtime/element.ts
* 简化元素类型定义
---
* Simplify element type definition
=> refactor(elements): simplify element type definition

packages/g6/__tests__/demo/case/element-change-type.ts, packages/g6/__tests__/demo/case/index.ts, packages/g6/__tests__/demo/static/node-diamond.ts, packages/g6/__tests__/integration/snapshots/static/node-diamond.svg, packages/g6/__tests__/snapshots/elements/change-type/change-type.svg, packages/g6/__tests__/snapshots/elements/change-type/change-type__change_type.svg, packages/g6/__tests__/unit/elements/change-type.spec.ts, packages/g6/__tests__/unit/elements/combo.spec.ts, packages/g6/__tests__/unit/runtime/element.spec.ts, packages/g6/src/elements/nodes/diamond.ts, packages/g6/src/runtime/element.ts
* 修复当元素类型变化时，没有按照预期重新绘制的问题
* 调整了 Dimond 节点
---
* Fix to not redrawing as expected when element type changes 
* Adjusted Dimond nodes
=> fix: fix element cannot re-create when type changed

packages/g6/__tests__/demo/case/index.ts, packages/g6/__tests__/demo/case/layout-mds.ts, packages/g6/__tests__/snapshots/layouts/mds/mds__ld100.svg, packages/g6/__tests__/unit/layouts/mds.spec.ts, packages/g6/src/elements/shapes/label.ts, packages/site/examples/net/mdsLayout/demo/basicMDS.ts, packages/site/examples/net/mdsLayout/demo/meta.json
=> docs: add layout mds demo and test case

README.en-US.md, README.md
=> docs: fix readme typo

packages/g6/__tests__/unit/runtime/graph/graph.spec.ts, packages/g6/src/registry/extension/types.ts, packages/g6/src/runtime/graph.ts, packages/g6/src/spec/behavior.ts, packages/g6/src/spec/plugin.ts
* 新增 `updateBehavior` `updatePlugin` API
---
* Add `updateBehavior` `updatePlugin` API
=> feat(runtime): add updateBehavior/ updatePlugin api

packages/g6/src/behaviors/collapse-expand.ts, packages/g6/src/behaviors/drag-canvas.ts, packages/g6/src/behaviors/drag-element.ts, packages/g6/src/behaviors/zoom-canvas.ts
* 调整交互扩展，统一回调方法命名规则
---
* Adjust interactive extensions and unify callback method naming rules
=> refactor(behaviors): adjust behaviors

packages/g6/__tests__/unit/behaviors/collapse-expand.spec.ts, packages/g6/__tests__/unit/runtime/element/event.spec.ts, packages/g6/__tests__/unit/utils/element.spec.ts, packages/g6/__tests__/utils/to-match-svg-snapshot.ts, packages/g6/src/behaviors/collapse-expand.ts, packages/g6/src/behaviors/create-edge.ts, packages/g6/src/behaviors/drag-element.ts, packages/g6/src/behaviors/focus-element.ts, packages/g6/src/behaviors/hover-element.ts, packages/g6/src/exports.ts, packages/g6/src/plugins/contextmenu.ts, packages/g6/src/plugins/tooltip.ts, packages/g6/src/registry/extension/index.ts, packages/g6/src/runtime/behavior.ts, packages/g6/src/runtime/graph.ts, packages/g6/src/types/event.ts, packages/g6/src/utils/element.ts, packages/g6/src/utils/event/events.ts
* 导出 G6 事件类型
* 具有目标的事件添加原始目标
---
* Export G6 event type
* Carry original target in targeted event
related issue: https://github.com/antvis/G6/issues/5619
=> refactor: define and export event

packages/g6/__tests__/unit/runtime/graph/graph.spec.ts, packages/g6/src/constants/change.ts, packages/g6/src/constants/events/graph.ts, packages/g6/src/constants/registry.ts, packages/g6/src/exports.ts, packages/g6/src/registry/build-in.ts, packages/g6/src/registry/extension/index.ts, packages/g6/src/registry/extension/types.ts, packages/g6/src/registry/index.ts, packages/g6/src/registry/types.ts, packages/g6/src/runtime/behavior.ts, packages/g6/src/runtime/data.ts, packages/g6/src/runtime/element.ts, packages/g6/src/runtime/graph.ts, packages/g6/src/runtime/plugin.ts, packages/g6/src/runtime/transform.ts, packages/g6/src/runtime/types.ts, packages/g6/src/spec/index.ts, packages/g6/src/spec/spec.ts, packages/g6/src/spec/transform.ts, packages/g6/src/transforms/arrange-draw-order.ts, packages/g6/src/transforms/base-transform.ts, packages/g6/src/transforms/collapse-expand-combo.ts, packages/g6/src/transforms/index.ts, packages/g6/src/transforms/types.ts, packages/g6/src/transforms/update-related-edge.ts, packages/g6/src/types/change.ts, packages/g6/src/utils/change.ts, packages/g6/src/utils/extension.ts
- 新增 `Transform Controller`
- 抽取已实现的数据转换函数 `arrangeDrawOrderFlow`,`collapseExpand`,`updateRelatedEdge`  为内置 transform 插件，并设置成 required
=> feat(runtime): add transform controller

packages/g6/__tests__/demos/graph-to-data-url.ts, packages/g6/__tests__/main.ts, packages/g6/src/runtime/canvas.ts
* 修复导出 DataURL 时`背景`丢失的问题
* 修复导出 DataURL 时`图片`丢失的问题
---
* Fixed `background` loss when exporting DataURL 
* Fixed `image` loss when exporting DataURL
=> fix: fix issue appearing when export data url

packages/g6/src/runtime/graph.ts, packages/g6/tsdoc.json, packages/site/src/MarkdownDocumenter.ts, packages/site/src/constants/api-category.ts, packages/site/src/markdown/CustomMarkdownEmitter.ts, packages/site/src/utils/Utilities.ts, packages/site/src/utils/parser.ts
**options**
**api**
**properties**
=> feat(doc-pipeline): add scripts to generate graph api docs

packages/site/.dumi/global.less, packages/site/.dumirc.ts, packages/site/.gitignore, packages/site/package.json, packages/site/scripts/clear-doc.ts, packages/site/src/setting.ts
* 添加脚本用于清理自动生成的文档
```shell
pnpm doc:clear
```
* 调整文档目录结构
* 样式调整
---
* Add scripts to clean up automatically generated documents
```shell
pnpm doc:clear
```
* Adjust docs structure
* Add style for summary tag
=> feat(docs): add clear script, adjust docs structure

packages/g6/__tests__/demos/behavior-scroll-canvas.ts, packages/g6/__tests__/unit/behaviors/scroll-canvas.spec.ts, packages/g6/src/behaviors/scroll-canvas.ts
* 调整 ScrollCanvas 代码
---
* Adjust code of ScrollCanvas
=> refactor(behaviors): adjust scroll-canvas

packages/g6/src/exports.ts, packages/g6/src/plugins/bubble-sets.ts, packages/g6/src/plugins/camera-setting.ts, packages/g6/src/plugins/contextmenu.ts, packages/g6/src/plugins/grid-line.ts, packages/g6/src/plugins/history/events.ts, packages/g6/src/plugins/history/index.ts, packages/g6/src/plugins/history/utils.ts, packages/g6/src/plugins/hull/index.ts, packages/g6/src/plugins/index.ts, packages/g6/src/plugins/legend.ts, packages/g6/src/plugins/toolbar/index.ts, packages/g6/src/plugins/toolbar/util.ts, packages/g6/src/plugins/tooltip.ts, packages/g6/src/plugins/watermark.ts, packages/g6/src/types/event.ts
BubbleSets 气泡集:
相机设置：
Contextmenu菜单：
GridLine 网格线：
legend图例：
tooltip提示：
waterMaker水印：
=> chore: add some doc api for plugins

packages/g6/package.json
=> chore: add missing dev deps

packages/g6/src/runtime/element.ts, packages/site/examples/animation/basic/demo/update.js, packages/site/examples/animation/viewport/demo/rotate.js, packages/site/examples/animation/viewport/demo/translate.js, packages/site/examples/animation/viewport/demo/zoom.js, packages/site/examples/behavior/focus/demo/basic.js, packages/site/examples/element/custom-combo/demo/extra-button.js, packages/site/examples/element/node/demo/donut.js, packages/site/examples/layout/dagre/demo/antv-dagre-combo.js, packages/site/examples/layout/dendrogram/demo/vertical.js, packages/site/examples/layout/force-directed/demo/3d-force.js, packages/site/examples/layout/force-directed/demo/collision.js, packages/site/examples/layout/force-directed/demo/d3-force.js, packages/site/examples/layout/force-directed/demo/force.js, packages/site/examples/layout/force-directed/demo/mesh.js, packages/site/examples/layout/fruchterman/demo/basic.js, packages/site/examples/layout/fruchterman/demo/cluster.js, packages/site/examples/layout/grid/demo/basic.js, packages/site/examples/layout/mds/demo/basic.js, packages/site/examples/layout/mechanism/demo/change-data.js, packages/site/examples/layout/mechanism/demo/switch.js, packages/site/examples/plugin/bubble-sets/demo/basic.js, packages/site/examples/plugin/hull/demo/basic.js
* 修复元素更新样式异常的问题
* 更新站点 Demo （部分 Demo 在升级 G 6.0 后需要改动，一部分适配动画变更）
---
* Fixed abnormal element update style 
* Update site Demo (part of Demo needs to be changed after G 6.0 upgrade, part of demo adapts to animation changes)
=> fix: fix demos

packages/g6/__tests__/bugs/element-edge-update-arrow.spec.ts, packages/g6/__tests__/snapshots/__tests__/bugs/element-edge-update-arrow/default.svg, packages/g6/__tests__/snapshots/__tests__/bugs/element-edge-update-arrow/update-arrow.svg, packages/g6/src/elements/edges/base-edge.ts
* 修复边上箭头无法更新的问题
---
* Fixed an issue where side arrows could not be updated
=> fix: fix issue that arrow cannot update

packages/g6/jest.config.js, packages/g6/src/elements/nodes/base-node.ts, packages/g6/src/types/node.ts
- 节点标签样式配置新增设置 `offsetX` 和 `offsetY`
=> feat: add node label offset config

packages/g6/__tests__/utils/create.ts, packages/g6/src/elements/combos/base-combo.ts, packages/g6/src/elements/combos/circle.ts, packages/g6/src/elements/nodes/base-node.ts, packages/g6/src/elements/nodes/circle.ts, packages/g6/src/elements/nodes/ellipse.ts, packages/g6/src/elements/nodes/html.ts, packages/g6/src/elements/nodes/star.ts, packages/g6/src/elements/nodes/triangle.ts, packages/g6/src/elements/shapes/base-shape.ts, packages/g6/src/utils/bbox.ts, packages/g6/src/utils/edge.ts, packages/g6/src/utils/element.ts
=> refactor(elements): remove getKey method on base-node

packages/g6/__tests__/unit/runtime/graph/graph.spec.ts, packages/g6/src/runtime/graph.ts
- 新增 graph api `getElementData(id: ID)`
=> feat: add getElementData api

packages/site/examples/algorithm/case/demo/label-propagation.js, packages/site/examples/algorithm/case/demo/louvain.js, packages/site/examples/algorithm/case/demo/pattern-matching.js, packages/site/examples/algorithm/case/demo/shortest-path.js
* 调整算法 Demo
---
* Adjust algorithm demo
=> docs(site): adjust algorithm demos

packages/g6/__tests__/snapshots/plugins/hull/plugin-hull/emptyMembers.svg, packages/g6/__tests__/unit/plugins/hull/plugin-hull.spec.ts, packages/g6/src/plugins/hull/index.ts
* 修复 Hull members 为空时异常的问题
---
* Fixed an issue where Hull members were null time exceptions
=> fix(plugins): fix error when members is empty

packages/g6/package.json, packages/g6/scripts/tips.mjs
* 调整版本号为 5.0.0
* 移除 beta 标签
* 添加 postinstall 提示
---
* Modify version to 5.0.0
* Remove beta tag 
* Add postinstall prompt
=> chore: update tab and postinstall script

packages/g6/__tests__/demos/layout-dendrogram-basic.ts, packages/g6/__tests__/demos/layout-dendrogram-tb.ts, packages/site/examples/layout/compact-box/demo/basic.js, packages/site/examples/layout/compact-box/demo/horizontal.js, packages/site/examples/layout/compact-box/demo/vertical.js, packages/site/examples/layout/dendrogram/demo/basic.js, packages/site/examples/layout/dendrogram/demo/vertical.js, packages/site/examples/layout/indented/demo/basic.js, packages/site/examples/layout/mindmap/demo/auto-side.js, packages/site/examples/layout/mindmap/demo/custom-side.js, packages/site/examples/layout/mindmap/demo/left-side.js, packages/site/examples/layout/mindmap/demo/right-side.js
* 调整树图相关 Demo
> 暂未给树图提供入场动画，因此临时关闭，后续完善后启用
---
* Adjust the tree related Demo
> The tree does not provide entrance animation, so it is temporarily closed, and will be enabled after further improvement
=> docs(site): update tree graph demo

packages/g6/src/elements/shapes/badge.ts, packages/g6/src/elements/shapes/icon.ts, packages/g6/src/elements/shapes/label.ts, packages/g6/src/exports.ts
* 导出基础复合图形 （徽标、图标、标签）
---
* Export basic composite shapes (Badge, Icon, Label)
=> refactor: export badge, icon, label shape

packages/g6/__tests__/snapshots/runtime/graph/add-children-data/add-children-data.svg, packages/g6/__tests__/snapshots/runtime/graph/add-children-data/default.svg, packages/g6/__tests__/unit/runtime/graph/add-children-data.spec.ts, packages/g6/src/runtime/data.ts, packages/g6/src/runtime/graph.ts
* 新增 addChildrenData API，用于向树节点下添加子节点
---
* Added the addChildrenData API to add children to the tree node
=> feat: add addChildrenData api

packages/g6/__tests__/demos/case-indented-tree.ts, packages/g6/__tests__/demos/index.ts, packages/g6/__tests__/demos/plugin-toolbar-iconfont.ts, packages/g6/__tests__/index.html, packages/g6/src/elements/shapes/base-shape.ts, packages/g6/src/index.ts, packages/g6/src/runtime/graph.ts, packages/site/examples/element/edge/demo/cubic.js, packages/site/examples/element/edge/demo/line.js, packages/site/examples/element/edge/demo/quadratic.js, packages/site/examples/element/node/demo/circle.js, packages/site/examples/element/node/demo/diamond.js, packages/site/examples/element/node/demo/donut.js, packages/site/examples/element/node/demo/ellipse.js, packages/site/examples/element/node/demo/hexagon.js, packages/site/examples/element/node/demo/image.js, packages/site/examples/element/node/demo/rect.js, packages/site/examples/element/node/demo/rounded-rect.js, packages/site/examples/element/node/demo/star.js, packages/site/examples/element/node/demo/triangle.js, packages/site/examples/scene-case/default/demo/indented-tree.js, packages/site/examples/scene-case/default/demo/meta.json
* 新增缩进树场景案例
---
* Add intended tree scene case
=> feat: add intended tree case

packages/g6/src/elements/effect.ts, packages/g6/src/elements/shapes/badge.ts, packages/g6/src/elements/shapes/icon.ts, packages/g6/src/elements/shapes/label.ts, packages/g6/src/exports.ts, packages/g6/src/runtime/canvas.ts, packages/g6/src/runtime/data.ts, packages/g6/src/runtime/graph.ts, packages/g6/src/types/data.ts, packages/g6/src/types/edge.ts, packages/g6/src/types/element.ts, packages/g6/src/utils/layout.ts, packages/g6/src/utils/style.ts, packages/site/src/MarkdownDocumenter.ts
* 导出一些类型，便于生成文档
* 完善注释
---
* Export some types for easy document generation 
* Perfect comments
=> refactor: exports type and add comments

packages/g6/__tests__/unit/behaviors/hover-activate.spec.ts, packages/g6/src/behaviors/drag-element.ts, packages/g6/src/behaviors/hover-activate.ts, packages/g6/src/runtime/data.ts, packages/g6/src/runtime/element.ts, packages/g6/src/runtime/graph.ts, packages/g6/src/themes/base.ts
* 优化交互性能，跳过一些交互的样式计算
---
* Optimize interaction performance by skipping some interaction style calculations
=> refactor: optimize behavior performance

packages/g6/__tests__/demos/plugin-contextmenu.ts, packages/g6/__tests__/unit/plugins/contextmenu.spec.ts, packages/g6/src/plugins/contextmenu/index.ts
* 修复 contextmenu
* 点击画布其他区域无法关闭的问题 https://github.com/antvis/G6/issues/5902
* 设置类名不生效的问题 https://github.com/antvis/G6/issues/5901
---
* fix contextmenu 
* click on the canvas other regions cannot be closed questions https://github.com/antvis/G6/issues/5902 
* set the name of the class is not effective https://github.com/antvis/G6/issues/5901
=> fix: fix issue about contextmenu

packages/g6/__tests__/bugs/behaviors-click-select.spec.ts, packages/g6/__tests__/snapshots/__tests__/bugs/behaviors-click-select/add-node-2.svg, packages/g6/__tests__/snapshots/__tests__/bugs/behaviors-click-select/click-node-2.svg, packages/g6/__tests__/snapshots/__tests__/bugs/behaviors-click-select/state-selected.svg, packages/g6/src/behaviors/click-select.ts
issue: https://github.com/antvis/G6/issues/5949
* 修复 ClickSelect 未同步由非交互操作导致的元素状态变更不同步的问题
---
* Fixed an issue where ClickSelect did not synchronize element state changes due to non-interactive operations
=> fix(behaviors): click-select sync state update by api

packages/site/docs/api/graphLayout/grid.en.md, packages/site/docs/api/graphLayout/grid.zh.md
G6 文档 图布局 Graph Layout 部分出现单词错误 #5977
=> fix: fix issue about site (#5977)

packages/g6/src/runtime/viewport.ts
* 修复 zoomRange 不生效的问题
---
* fix zoomRange invalid
issue: https://github.com/antvis/G6/issues/6019
=> fix: fix zoomRange invalid

packages/g6/__tests__/unit/behaviors/click-select.spec.ts, packages/g6/__tests__/unit/utils/state.spec.ts, packages/g6/src/behaviors/brush-select.ts, packages/g6/src/behaviors/click-select.ts, packages/g6/src/runtime/data.ts, packages/g6/src/runtime/graph.ts, packages/g6/src/utils/state.ts
* 重构 ClickSelect，解决数据同步、快速点击时异常等问题
---
* Refactoring ClickSelect to solve problems such as data synchronization and fast click exceptions
issue: https://github.com/antvis/G6/issues/6011
=> refactor: refactor click select

packages/cli/template-extension/__tests__/utils/create.ts, packages/cli/template-extension/__tests__/utils/to-match-svg-snapshot.ts, packages/g6-extension-3d/src/elements/base-node-3d.ts, packages/g6/__tests__/demos/case-indented-tree.ts, packages/g6/__tests__/main.ts, packages/g6/__tests__/unit/runtime/canvas.spec.ts, packages/g6/__tests__/unit/runtime/graph/graph.spec.ts, packages/g6/__tests__/utils/create.ts, packages/g6/__tests__/utils/to-match-svg-snapshot.ts, packages/g6/src/behaviors/drag-element.ts, packages/g6/src/elements/base-element.ts, packages/g6/src/elements/combos/base-combo.ts, packages/g6/src/elements/nodes/html.ts, packages/g6/src/global.d.ts, packages/g6/src/plugins/fullscreen/index.ts, packages/g6/src/runtime/canvas.ts, packages/g6/src/runtime/graph.ts, pnpm-workspace.yaml
* 重构 Canvas，支持动态切换渲染器
---
* Refactor Canvas to support switch renderer in runtime
=> refactor: refactor canvas, support switch renderer

packages/g6/__tests__/dataset/organization-chart.json, packages/g6/__tests__/demos/case-org-chart.ts, packages/g6/__tests__/demos/index.ts, packages/g6/src/runtime/graph.ts, packages/g6/src/runtime/viewport.ts, packages/site/examples/scene-case/default/demo/meta.json, packages/site/examples/scene-case/default/demo/organization-chart.js
=> docs: add level of detail demo

packages/g6/__tests__/bugs/element-orth-router.spec.ts, packages/g6/__tests__/snapshots/__tests__/bugs/element-orth-router/default.svg, packages/g6/src/utils/router/orth.ts
=> fix: fix polyline misalignment in orth router between nodes

.github/workflows/release-pr.yml, .github/workflows/release.yml, .github/workflows/version.yml, .husky/pre-commit, package.json, packages/g6/package.json
* husky will prevent when commit to master and v5 branches directly
* add release workflow
=> chore: update husky and add release workflow

packages/g6/__tests__/demos/element-label-oversized.ts, packages/g6/__tests__/snapshots/elements/label-oversized/default.svg, packages/g6/src/elements/shapes/label.ts
修复该问题 https://github.com/antvis/G6/issues/6051
=> fix: label background word wrap width

.eslintrc.js, .github/workflows/publish.yml, package.json, packages/g6-extension-3d/__tests__/.eslintrc, packages/g6-extension-react/__tests__/.eslintrc, packages/g6-extension-react/src/graph/graph.tsx, packages/g6/__tests__/.eslintrc, packages/g6/src/elements/shapes/base-shape.ts, packages/g6/src/utils/print.ts
* add no-console to eslint
* remove console.log
* adjust publish script
=> chore: config project

packages/g6/__tests__/bugs/element-node-update-badge.spec.ts, packages/g6/__tests__/snapshots/__tests__/bugs/element-node-update-badge/default.svg, packages/g6/__tests__/snapshots/__tests__/bugs/element-node-update-badge/update-node-badge.svg, packages/g6/src/themes/base.ts
- fixed https://github.com/antvis/G6/issues/6072
=> fix: the initial values of some nodes are not set by default

packages/g6/__tests__/bugs/behaviors-multiple-conflict.spec.ts, packages/g6/__tests__/snapshots/bugs/behaviors-multiple-conflict/default.svg, packages/g6/__tests__/snapshots/bugs/behaviors-multiple-conflict/drag-canvas.svg, packages/g6/__tests__/snapshots/bugs/behaviors-multiple-conflict/drag-element.svg, packages/g6/src/behaviors/drag-canvas.ts
* 修复 DragElement、DragCanvas 交互冲突问题
---
* fix drag element, drag canvas conflict
Issue: https://github.com/antvis/G6/issues/6124
=> fix(behaviors): fix drag element, drag canvas conflict

packages/g6/__tests__/demos/element-node-avatar.ts, packages/g6/__tests__/demos/index.ts, packages/g6/__tests__/snapshots/elements/nodes/avatar/default.svg, packages/g6/__tests__/snapshots/plugins/legend/click-again.svg, packages/g6/__tests__/snapshots/plugins/legend/click.svg, packages/g6/__tests__/snapshots/plugins/legend/mouseenter.svg, packages/g6/__tests__/snapshots/plugins/legend/mouseleave.svg, packages/g6/__tests__/snapshots/plugins/legend/normal.svg, packages/g6/__tests__/types.d.ts, packages/g6/__tests__/unit/elements/nodes/avatar.spec.ts, packages/g6/__tests__/unit/utils/shape.spec.ts, packages/g6/__tests__/utils/to-match-svg-snapshot.ts, packages/g6/src/elements/combos/base-combo.ts, packages/g6/src/elements/nodes/base-node.ts, packages/g6/src/elements/nodes/image.ts, packages/g6/src/elements/shapes/icon.ts, packages/g6/src/elements/shapes/image.ts, packages/g6/src/elements/shapes/index.ts, packages/g6/src/utils/shape.ts
* 实现 Image 图形，支持设置裁切半径
---
* Implement Image shape and support setting clip radius property
=> feat: implement image shape support radius

packages/site/.dumirc.ts, packages/site/docs/manual/faq.en.md, packages/site/docs/manual/faq.zh.md
* 补充 FAQ 问题
* 调整站点显示版本号
---
* Add FAQ questions 
* Adjust the site display version number
=> refactor: improve site docs

packages/g6/src/behaviors/drag-canvas.ts
Issue: https://github.com/antvis/G6/issues/6145
=> fix(behaviors): fix drag canvas unbind event

packages/g6/__tests__/bugs/plugin-history-align-fields.spec.ts, packages/g6/src/plugins/history/util.ts
=> fix: fix issue for null values in the alignFields util

CHANGELOG.md
fix spelling errors in CHANGELOG.md
=> [fix docs] spelling errors

.github/workflows/issue_translate.yml
When an issue is opened or edited, this action will automatically translate its title to english.
You can see an example at: https://github.com/Aarebecca/issue-translator/issues/1
=> chore: add github action to auto translate issue title

packages/g6/package.json, packages/site/.dumi/global.ts
Update `@antv/layout` version and add to site env.
=> chore: update layout version and add to site env

packages/g6/__tests__/demos/case-mindmap.ts, packages/site/examples/scene-case/default/demo/mindmap.js
- fixed: #6329
修复思维导图官网示例中无法展开收起。具体来说，在自定义交互中，用户需要点击节点上的小图标来触发展开和收起操作。然而，当鼠标悬停在节点上时，小图标没有出现
=> fix: fix issue of mindmap demo cannot collapse

packages/g6/__tests__/snapshots/behaviors/collapse-expand-node/collapse-A-0.svg, packages/g6/__tests__/snapshots/behaviors/collapse-expand-node/collapse-A-500.svg, packages/g6/__tests__/snapshots/behaviors/collapse-expand-node/expand-A-0.svg, packages/g6/__tests__/snapshots/behaviors/collapse-expand-node/expand-A-1000.svg, packages/g6/__tests__/snapshots/behaviors/collapse-expand-node/expand-A-500.svg, packages/g6/__tests__/snapshots/behaviors/collapse-expand-node/expand-B-again-0.svg, packages/g6/__tests__/snapshots/behaviors/collapse-expand-node/expand-B-again-1000.svg, packages/g6/__tests__/snapshots/behaviors/collapse-expand-node/expand-B-again-500.svg, packages/g6/__tests__/snapshots/behaviors/drag-element-combo/drag-combo-2-after-drop-into.svg, packages/g6/__tests__/snapshots/plugins/history/plugin-history/create-edge-redo.svg, packages/g6/__tests__/snapshots/plugins/history/plugin-history/create-edge-undo.svg, packages/g6/__tests__/snapshots/plugins/history/plugin-history/create-edge.svg, packages/g6/__tests__/snapshots/plugins/history/plugin-history/hideElement-redo.svg, packages/g6/__tests__/snapshots/plugins/history/plugin-history/hideElement-undo.svg, packages/g6/__tests__/snapshots/plugins/history/plugin-history/hideElement.svg, packages/g6/__tests__/snapshots/plugins/history/plugin-history/setElementZIndex-redo.svg, packages/g6/__tests__/snapshots/plugins/history/plugin-history/setElementZIndex-undo.svg, packages/g6/__tests__/snapshots/plugins/history/plugin-history/setElementZIndex.svg, packages/g6/__tests__/unit/plugins/history/plugin-history.spec.ts, packages/g6/__tests__/utils/dir.ts, packages/g6/src/runtime/data.ts, packages/g6/src/utils/visibility.ts
* fix: deduplicate multiple translations to the same node
* test: update zIndex related snapshots
* fix: deal with path seperator in Windows
=> fix: change zIndex in DataController (#6295)

packages/site/docs/manual/faq.en.md, packages/site/docs/manual/faq.zh.md
=> docs: update faq (#6371)

packages/g6/src/behaviors/fix-element-size.ts, packages/g6/src/plugins/edge-bundling/index.ts, packages/g6/src/plugins/fisheye/index.ts
- fixed: https://github.com/antvis/G6/issues/6416
=> fix: skip non-existent elements

README.en-US.md, README.md, packages/g6-extension-3d/README.md, packages/g6-extension-react/README.md, packages/site/.dumi/app.tsx, packages/site/.dumirc.ts, packages/site/docs/manual/faq.en.md, packages/site/docs/manual/faq.zh.md
=> refactor: adjust v5 site

packages/site/docs/manual/core-concept/element.zh.md
=> docs: update element.zh.md

packages/g6/__tests__/demos/element-edge-custom-arrow.ts, packages/g6/__tests__/snapshots/elements/edges/custom-arrow/default.svg, packages/site/examples/element/custom-edge/demo/custom-arrow.js
=> fix: correct offset issue with custom arrow

SECURITY.md
Request for maintainer to create and publish security.md and security policy.  In order to see security vulnerabilities, CVEs, and fixes, please publish a security policy with information on how to submit vulnerabilities, how to track CVEs and what users can expect in terms of remediation of vulnerabilities.
=> Request for maintainer to create and publish security.md and security policy.

packages/g6/__tests__/demos/case-unicorns-investors.ts, packages/g6/__tests__/snapshots/behaviors/auto-adapt-label/padding-60.svg, packages/g6/__tests__/snapshots/behaviors/auto-adapt-label/zoom-3.svg, packages/g6/src/behaviors/auto-adapt-label.ts, packages/g6/src/behaviors/fix-element-size.ts, packages/g6/src/elements/shapes/base-shape.ts, packages/g6/src/runtime/element.ts, packages/g6/src/runtime/graph.ts, packages/g6/src/utils/transform.ts
- Graph 声明周期事件抛出响应的 stage 信息
- AFTER_DRAW 事件抛出是否为首次渲染的信息
- 优化 AutoAdaptLabel 和 FixElementSize 性能
=> perf: optimize behaviors

packages/g6-extension-3d/src/elements/capsule.ts, packages/g6-extension-3d/src/elements/cone.ts, packages/g6-extension-3d/src/elements/cylinder.ts, packages/g6-extension-3d/src/elements/torus.ts, packages/g6-extension-3d/src/utils/material.ts, packages/g6-extension-3d/src/utils/texture.ts
=> fix: 3d scene error

packages/g6/__tests__/demos/perf-20000-elements.ts, packages/site/examples/behavior/inner-event/demo/basic.js, packages/site/examples/feature/default/demo/theme.js, packages/site/examples/performance/massive-data/demo/20000.js, packages/site/examples/performance/massive-data/demo/5000.js, packages/site/examples/performance/massive-data/demo/60000.js
> related issue: https://github.com/antvis/G6/issues/6474
---
> related issue: https://github.com/antvis/G6/issues/6474
=> fix: fix site demo

packages/g6/CHANGELOG.md, packages/g6/__tests__/unit/plugins/utils/dom.spec.ts, packages/g6/package.json, packages/g6/src/plugins/background/index.ts, packages/g6/src/plugins/grid-line.ts, packages/g6/src/plugins/utils/dom.ts, packages/g6/src/version.ts
=> fix: fix plugin style

packages/g6/src/runtime/graph.ts, packages/site/examples/plugin/minimap/demo/basic.js, packages/site/examples/plugin/minimap/demo/meta.json, packages/site/examples/plugin/minimap/index.en.md, packages/site/examples/plugin/minimap/index.zh.md
=> refactor: add minimap demo, update api doc

packages/g6/src/transforms/place-radial-labels.ts
=> fix: fallback handling to ignore invisible elements

packages/g6/__tests__/bugs/plugin-hull-three-collinear-dots.spec.ts, packages/g6/__tests__/snapshots/bugs/plugin-hull-three-collinear-dots/default.svg, packages/g6/src/plugins/hull/util.ts
=> fix(hull): fix issue with fully enclosing collinear tree nodes

packages/site/examples/scene-case/default/demo/meta.json, packages/site/examples/scene-case/default/demo/snake-flow-diagram.js
=> docs: add snake flow diagram

packages/bundle/index.html, packages/bundle/package.json, packages/bundle/rollup.config.mjs, packages/bundle/src/index.ts, packages/bundle/tsconfig.json, packages/bundle/vite.config.js, packages/bundle/webpack.config.js
=> feat: add bundle test env

packages/g6/__tests__/demos/index.ts, packages/g6/__tests__/demos/plugin-tooltip-dual.ts, packages/g6/src/plugins/tooltip.ts, packages/site/examples/plugin/tooltip/demo/dual.js, packages/site/examples/plugin/tooltip/demo/meta.json
=> feat(tooltip): support multiple tooltips for hover and click on the same element

packages/g6/package.json
fix: https://github.com/antvis/G6/issues/6605
=> fix: upgrade hull.js

packages/g6/__tests__/main.ts
=> chore: dev env support switch case and print time spend

packages/g6/src/behaviors/drag-element-force.ts, packages/site/examples/layout/force-directed/demo/bubbles.js, packages/site/examples/layout/force-directed/demo/drag-fixed.js, packages/site/examples/layout/force-directed/demo/functional-params.js, packages/site/examples/layout/force-directed/demo/meta.json, packages/site/examples/layout/force-directed/demo/prevent-overlap.js
=> docs: add force layout demos

packages/g6/src/runtime/layout.ts
* 修复布局时，连接到组合的边被过滤的问题
---
Fix edges which connect to combo were filtered in layout stage
=> fix: fix edges which connect to combo were filtered in layout stage

packages/g6/src/runtime/canvas.ts
=> refactor: disable dirty rectangle rendering

packages/g6/__tests__/demos/case-why-do-cats.ts, packages/g6/package.json, packages/site/examples/scene-case/default/demo/why-do-cats.js
解决 d3 包的 esm_required_error 问题
=> fix: replace d3 with @antv/vendor

.github/workflows/build.yml, README.md, README.zh-CN.md
=> docs: github update the action badge url

packages/site/.dumirc.ts
=> docs: add announcement for doc experience survey

.github/workflows/scripts/updateYuque.js, .github/workflows/update-yuque.yml, packages/site/docs/manual/behavior/build-in/ZoomCanvas.zh.md
- 添加 GtiHub Action 当文档相关 PR 被合并时同步上传到语雀知识库
- 修改 `zoom-canvas` 交互文档
=> docs: add github action to update yuque

packages/site/docs/manual/plugin/build-in/Legend.zh.md, packages/site/docs/manual/plugin/build-in/Minimap.zh.md, packages/site/docs/manual/plugin/build-in/Toolbar.zh.md
- fix issues with some pages not opening
- fixed #6836
=> docs: fix issues with some pages not opening

packages/site/docs/manual/behavior/overview.zh.md, packages/site/docs/manual/data.zh.md, packages/site/docs/manual/plugin/overview.zh.md
=> docs: update documentation for plugin overview

.github/ISSUE_TEMPLATE/3.docs_feedback.yml, .github/ISSUE_TEMPLATE/4.oscp.yml
=> feat: add oscp issue template

.github/ISSUE_TEMPLATE/4.oscp.yml
=> fix: oscp issue template

packages/site/docs/manual/layout/build-in/DendrogramLayout.zh.md
=> docs: 更新生态树布局文档

packages/g6/__tests__/demos/plugin-grid-line.ts, packages/g6/src/plugins/grid-line.ts, packages/site/docs/manual/plugin/build-in/GridLine.zh.md
=> feat: grid line plugin enhances canvas following

packages/site/docs/manual/layout/build-in/DagreLayout.zh.md
=> docs: 改造布局文档 - Dagre布局

packages/site/docs/manual/layout/build-in/D3Force3DLayout.zh.md, packages/site/docs/manual/layout/build-in/D3ForceLayout.zh.md
- fixed: #6935 
- fixed: #6907
=> docs: update d3-force and d3-force-3d layout docs

packages/site/common/api/plugins/snapline.md, packages/site/docs/manual/plugin/build-in/Snapline.en.md, packages/site/docs/manual/plugin/build-in/Snapline.zh.md
=> docs: 改造Snapline插件文档

packages/site/common/api/behaviors/focus-element.md, packages/site/docs/manual/behavior/build-in/FocusElement.en.md, packages/site/docs/manual/behavior/build-in/FocusElement.zh.md
=> docs: 更新 FocusElement 交互文档，增加概述、使用场景及基本用法说明

packages/site/docs/manual/plugin/build-in/Tooltip.zh.md
=> docs: 改造文档「插件 - 内置插件 - Tooltip 提示框」

packages/g6/src/plugins/fisheye/index.ts
=> fix: 修复Fisheye在update时，未更新this.r/this.d

packages/site/docs/manual/layout/build-in/AntvDagreLayout.zh.md
=> docs: 改造文档布局文档-AntvDagre

packages/site/docs/manual/behavior/build-in/CreateEdge.zh.md
=> docs(CreateEdge): 改造文档 [交互 - 内置交互 - CreateEdge 创建边]

packages/site/.dumirc.ts, packages/site/.gitignore, packages/site/mako.config.json, packages/site/package.json
https://g6-site-pre.alipay.com/api/data
=> chore(site): optimize ssr in production env

packages/site/common/angular-snippet.md, packages/site/common/react-snippet.md, packages/site/common/vue-snippet.md, packages/site/docs/manual/getting-started/integration/angular.en.md, packages/site/docs/manual/getting-started/integration/angular.zh.md, packages/site/docs/manual/getting-started/integration/react.en.md, packages/site/docs/manual/getting-started/integration/react.zh.md, packages/site/docs/manual/getting-started/integration/vue.en.md, packages/site/docs/manual/getting-started/integration/vue.zh.md
=> docs: update demo links from Codesandbox to Stackblitz

packages/g6-extension-3d/package.json, packages/g6-extension-react/__tests__/graph.tsx, packages/g6-extension-react/__tests__/unit/attribute-changed-callback.spec.tsx, packages/g6-extension-react/package.json, packages/g6-extension-react/rollup.config.mjs, packages/g6-extension-react/src/react-node/render.ts, packages/g6-ssr/package.json, packages/g6-ssr/src/index.ts, packages/g6/package.json, packages/g6/src/plugins/edge-filter-lens/index.ts, packages/g6/src/version.ts, packages/site/.dumi/global.ts, packages/site/common/angular-snippet.md, packages/site/common/api/plugins/edge-filter-lens.md, packages/site/common/react-snippet.md, packages/site/common/vue-snippet.md, packages/site/docs/manual/getting-started/integration/angular.en.md, packages/site/docs/manual/getting-started/integration/angular.zh.md, packages/site/docs/manual/getting-started/integration/react.en.md, packages/site/docs/manual/getting-started/integration/react.zh.md, packages/site/docs/manual/getting-started/integration/vue.en.md, packages/site/docs/manual/getting-started/integration/vue.zh.md, packages/site/docs/manual/plugin/build-in/EdgeFilterLens.en.md, packages/site/docs/manual/plugin/build-in/EdgeFilterLens.zh.md, packages/site/docs/manual/plugin/build-in/Hull.zh.md, packages/site/examples/plugin/fisheye/demo/custom.js, packages/site/package.json
=> docs: 改造内置插件Hull文档

packages/g6-extension-3d/package.json, packages/g6-extension-react/__tests__/graph.tsx, packages/g6-extension-react/__tests__/unit/attribute-changed-callback.spec.tsx, packages/g6-extension-react/package.json, packages/g6-extension-react/rollup.config.mjs, packages/g6-extension-react/src/react-node/render.ts, packages/g6-ssr/package.json, packages/g6-ssr/src/index.ts, packages/g6/package.json, packages/g6/src/behaviors/drag-element.ts, packages/g6/src/plugins/edge-filter-lens/index.ts, packages/g6/src/version.ts, packages/site/.dumi/global.ts, packages/site/common/angular-snippet.md, packages/site/common/api/plugins/edge-filter-lens.md, packages/site/common/react-snippet.md, packages/site/common/vue-snippet.md, packages/site/docs/manual/getting-started/integration/angular.en.md, packages/site/docs/manual/getting-started/integration/angular.zh.md, packages/site/docs/manual/getting-started/integration/react.en.md, packages/site/docs/manual/getting-started/integration/react.zh.md, packages/site/docs/manual/getting-started/integration/vue.en.md, packages/site/docs/manual/getting-started/integration/vue.zh.md, packages/site/docs/manual/plugin/build-in/BubbleSets.zh.md, packages/site/docs/manual/plugin/build-in/EdgeFilterLens.en.md, packages/site/docs/manual/plugin/build-in/EdgeFilterLens.zh.md, packages/site/examples/plugin/fisheye/demo/custom.js, packages/site/package.json
=> docs: 改造内置插件BubbleSets文档
