plugins/behaviour.analysis/index.js, src/controller/event.js
在这个更改后 https://github.com/antvis/g6/commit/9219f47ac7d86f0825f7410637cf9e354dc30924 , `behaviour.analysis` 里的 `wheelZoom` 在 Chrome 下就不起作用了。 `mousewheel` 和 `wheel` 都提供，Chrome 选择了监听标准的 `wheel` 事件。
所以可以去掉 `mousewheel`.
https://developer.mozilla.org/en-US/docs/Web/Events/mousewheel
https://developer.mozilla.org/en-US/docs/Web/Events/wheel
=> fix: fix wheelZoom behaviour by removing the deprecated mousewheel event

plugins/behaviour.analysis/index.js
Checklist
[√ ] npm test passes
[ √] commit message follows commit guidelines
Description of change
对于官方指定行为‘panNode’中方法 会保留不会随着mode更改而改变
https://github.com/antvis/g6/issues/544
CodePen Link: https://codepen.io/anon/pen/KrGwKz
所以可以可以把panNode中的graph.on替换为graph.behaviourOn.
=> 修复 mode更改是如果有官方panNode则panNode中方法会保留

plugins/behaviour.analysis/index.js
panNode、panBlank 同时使用，单击空白区时，会触发 `mousedown`，但是不会触发 `dragend`、`canvas:mouseleave` ，导致 lastPoint 存在未清除的值，影响下一次节点拖动，使画布出现不期望的同时拖动。
=> fix: 修复 panNode、panBlank 同时使用冲突的问题

demos/custom-node-card.html, src/behavior/drag-node.js
修复当自定义节点时，x和y坐标不为中心点时，拖动过程中delegate错位的问题。
=> 修复当自定义的节点中心位置不在中心点时delegate错位的问题

src/graph/controller/view.js
If the type of item for graph.focusItem(item) is string, the function cannot work properly. The reason is that `this.graph.findById(item)` was written as `this.graph.findById[item]` by mistake in `\g6\src\graph\controller\view.js` at line 68.
=> Fix: graph.focusItem(item) not working if item is a string

.gitignore, demos/fix-behavior.html, demos/internal-edges.html, src/behavior/brush-select.js, src/shape/edges/polyline.js
- 布局支持回调函数；
- 类型文件 export item；
- 修复 polyline 不支持 options 中配置的样式问题。
=> fix: polyline not support options styles

demos/layout-preset-change-data.html, src/graph/controller/layout.js, src/graph/graph.js, test/unit/layout/circular-web-worker-spec.js, test/unit/layout/force-web-worker-spec.js, test/unit/layout/preset-spec.js, test/unit/layout/web-worker-spec.js
-  bugfix： 如果是用户没有指定layout，并且数据中节点都有x, y坐标，调用graph.changeData方法后，没有刷新画布（graph.paint方法没有被调用）。
- 把web worker单测重新加回来。
=> Fix an issue that graph is not refreshed when calling graph.changeData method

docs/api/Shape.en.md, docs/api/Shape.zh.md, docs/manual/FAQ/gradient.en.md, docs/manual/FAQ/gradient.zh.md, docs/manual/FAQ/texture.en.md, docs/manual/FAQ/texture.zh.md, docs/manual/FAQ/transform.en.md, docs/manual/FAQ/transform.zh.md, docs/manual/advanced/keyconcept/shape-and-properties.zh.md, docs/manual/middle/elements/anchorpoint.en.md, docs/manual/middle/elements/anchorpoint.zh.md, docs/manual/middle/elements/shape-keyshape.en.md, docs/manual/middle/elements/shape-keyshape.zh.md, package.json, src/interface/item.ts, src/item/edge.ts, src/item/item.ts, src/item/node.ts, src/plugins/bundling/index.ts, src/shape/edge.ts, src/shape/shape.ts, src/shape/shapeBase.ts, tests/unit/graph/graph-spec.ts, tests/unit/graph/tree-graph-spec.ts, tests/unit/layout/force-spec.ts, tests/unit/plugins/bundling-spec.ts, tests/unit/plugins/minimap-spec.ts, tsconfig.json, types/index.ts, webpack.config.js
- 为了避免 G6 中的元素和 G 中 Shape 的混淆，节点和边的类型支持通过type字段定义，以后会废弃shape字段；
- 高级指引中的图 Shape 及属性文档中增加通用方法；
- 核心概念中删除关键概念目录，将anchorPoint和keyShape文档移动到节点和边中；
- FAQ 中增加 渐变和纹理文档。
=> feat：supports elements type by type

src/interface/graph.ts
解决如下类型定义问题：
../../node_modules/@antv/g6/types/index.d.ts:325:5 - error TS2411: Property 'default' of type 'IModeType[] | undefined' is not assignable to string index type 'IModeType[]'.
325     default?: IModeType[]
=> fix: update IMode define

src/interface/item.ts, src/item/edge.ts, src/item/item.ts, src/item/node.ts, src/types/index.ts
针对 src/item 下 TS strict 模式下的错误进行了修复。
在修改这个 PR 的问题时，需要在 tsconfig 中加上 `"strict": true`。在修改时才能看到报错。
strict 模式下主要的几类问题：
+ implict any，就是函数入参或者变量声明没有指明类型，这个时候默认是 any，严格模式下要求必须声明类型
+ strictNullCheck，有可能为 null 或者 undefined 的值，调这个值的方法，就会报错。简单的说就是 null 和 undefined 会是单独的类型，和其他值区分开来。所以这要求我们在代码里需要做一些判断，或者给默认值，这样可以很大程度避免 JS 动态特性带来的空值报错问题。
如果不能理解改动的原因，可以在 master 分支上打开 `"strict": true` 看一下具体的报错。
=> 修复 strict: true 下 TS 错误：src/item

docs/manual/FAQ/upgradeGuide.en.md, docs/manual/FAQ/upgradeGuide.zh.md, package.json, src/behavior/collapse-expand.ts, src/graph/tree-graph.ts, src/shape/shape.ts, tests/unit/graph/tree-graph-spec.ts, tests/unit/shape/findByClassName-spec.ts, tests/unit/shape/register-spec.ts
- feat: compatibility of group.findByClassName which is removed by G 4.0. 
- fix: collapse-expand behavior bug. 
- test: findByClassName-spec. 
- docs: update upgrade guide. 
- fix: compatibility for changeLayout and refreshLayout of TreeGraph. 
- fix: must rewrite draw function when register node or edge without extended shape problem
=> fix: compatibility for G6 3.3

src/index.ts
原来的导出方式 G6 本身是一个对象，无法当做命名空间来使用，导致类型用起来比较复杂。新的方式可以只解决导出类型，对 tree shaking 也比较友好。只是新增不会造成任何 break change
=> refactor: fix TypeScript type error

CHANGELOG.md, docs/api/Graph.en.md, docs/api/Graph.zh.md, docs/manual/introduction.en.md, docs/manual/introduction.zh.md, docs/manual/middle/states/defaultBehavior.zh.md, package.json, site/locale.json, site/pages/index.zh.tsx, src/behavior/zoom-canvas.ts, src/global.ts, src/interface/graph.ts, src/item/item.ts, src/shape/shapeBase.ts, stories/Issues/attrs/index.tsx, stories/Issues/changeData/data.js, stories/Issues/changeData/index.tsx, stories/Issues/issues.stories.tsx, tests/unit/behavior/zoom-spec.ts, tests/unit/graph/graph-spec.ts, tests/unit/state/update-element-states-spec.ts
1. zoom-canvas 时支持隐藏非 keyShape 元素，支持配置：
- enableOptimize：是否开启，默认为false；
- optimizeZoom：enableOptimize 为 true 时生效，表示当缩放比例小于该值时，自动隐藏非 keyShape 元素，默认值为 0.7。
2. 修复 changeData 问题，https://github.com/antvis/G6/issues/1323
=> feat：缩放画布时支持隐藏除keyShape外的元素

CHANGELOG.md, package.json, src/behavior/behavior.ts, src/behavior/click-select.ts, src/global.ts, src/types/index.ts
1. BehaviorOption 类型支持用户继承，添加了 [key:string]: unknow；
2. click-select Behavior 支持通过按住 ctrl 多选。
=> Fix behavior types & click-select Behavior support ctrl key

src/behavior/edge-tooltip.ts, src/behavior/tooltip-base.ts, src/behavior/tooltip.ts
#1347 #1409 
允许用户自己设置tooltip的offset的值。
考虑过当处于右下角区域时，x和y都再减去offset，但是实际测试时发现展示效果变化比较大，所以没有更新上去。建议团队考虑下要不要这样做。
=> feat: set offset as a option in tooltip

CHANGELOG.md, docs/manual/FAQ/set-label-bg.en.md, docs/manual/FAQ/set-label-bg.zh.md, examples/shape/labelBg/demo/edgeBg.js, examples/shape/labelBg/demo/meta.json, examples/shape/labelBg/demo/nodeBg.js, examples/shape/labelBg/index.en.md, examples/shape/labelBg/index.zh.md, src/shape/edge.ts, src/shape/node.ts, src/shape/shapeBase.ts, src/types/index.ts, stories/label/component/edge-label-background.tsx
1. 支持设置节点或边上label的背景；
2. 修复 changeData 后原有的 state 没有清除的问题；
3. 修复当不设置默认文本样式时，setItemState 后恢复不了文本原始样式问题。
=> feat: support set the background of the label

.gitignore, package.json, src/behavior/drag-combo.ts, src/graph/controller/item.ts, src/graph/graph.ts, src/interface/graph.ts, src/types/index.ts, src/util/graphic.ts, stories/Case/component/tutorial.tsx, stories/Combo/combo.stories.tsx, stories/Combo/component/combo-example.tsx, stories/Combo/component/combo-layout-collapse-expand.tsx, stories/Issues/attrs/index.tsx, stories/Issues/component/dagre-arrow.tsx, stories/Issues/ggeditorNode/baseNode.ts, stories/Issues/ggeditorNode/index.tsx, stories/Issues/issues.stories.tsx, stories/Tree/component/self-tree.tsx, stories/Tree/tree.stories.tsx, tests/unit/behavior/drag-combo-spec.ts
渲染
✅渲染空分组：
✅支持 Circle 及 Rect 两种默认类型，使用默认样式及配置；
✅设置空分组样式、标题；
✅渲染自定义空分组。
✅渲染单层分组：
✅能够渲染 Circle、Rect 两种默认 Combo，使用默认样式；
✅设置标题、边框及填充色；
✅能够设置 Combo 中的间距；
✅能够渲染单层自定义 Combo。
✅渲染嵌套分组：
✅能够设置嵌套分组的类型，比如 Circle Combo 中能嵌套 Rect Combo；
✅设置指定 Combo 的标题、边框及填充色；
✅能够设置 Combo 中的间距；
✅能够渲染嵌套的自定义 Combo。
🔲支持渲染默认收起的分组：需要提供配置项配置是否默认收起。
自定义分组：
✅支持自定义分组，能够指定大小、标题及样式；
创建组合拆分组：
✅创建组：选定元素，生成一个组，可以指定组的类型；
✅选中组，进行拆分，拆分后，删除 combo 数据，但 Combo 中的元素保留。
分组关系（适用于单层及嵌套分组）：
✅分组中节点与节点关系；
✅不同分组中节点的关系；
✅分组收起后分组外的节点连接到分组上；
✅支持分组与分组之间连接；
✅支持分组与节点之间连接；
✅嵌套分组中，收起内部分组后，再收起最外层分组，然后展开外层分组后，内部的保持收起状态；
✅动态改变分组与分组、分组与节点之间的连接。
拖出分组：
✅将子分组拖出父分组；
✅将节点拖出父分组；
✅被拖出元素的父分组高亮；
✅将图元素拖出分组后，支持保留空分组；
✅将节点或分组拖出父分组后，父分组自动改变大小；
🔲动态改变分组大小：提供配置项，拖动分组中节点时是拖出分组还是动态改变分组大小；
拖入分组：
✅将节点拖入到分组中；
✅将分组拖入到分组中；
✅将节点或分组拖入分组结束后，动态改变分组大小；
✅拖入时目标分组高亮。
分组交互：
✅收起分组：隐藏分组中的图元素； …
=> Test combo 20200424

src/behavior/click-select.ts, src/behavior/drag-combo.ts, src/behavior/drag-node.ts, src/graph/graph.ts, src/types/index.ts, tests/unit/behavior/drag-combo-spec.ts
1. drag-node behavior 中支持用户配置选中状态的状态值，默认为 selected；
2. drag-node behavior 中支持用户配置拖动节点时 combo 高亮的状态值，默认为空；
3. drag-node behavior 支持用户配置，拖动节点是将节点拖出 combo 还是 combo 动态变化。
=> fix: drag-node behavior supports selected states

CHANGELOG.md, docs/api/Graph.en.md, docs/api/Graph.zh.md, package.json, src/global.ts, webpack.config.js
1. 修复 webpack 配置，处理 build 产物中的 ES6 代码；
2. 修改 Graph API 文档中 plugin 的示例代码 。
=> fix: transplie d3-force to support ie11

global.d.ts, package.json, src/layout/mds.ts, src/layout/radial/mds.ts, tests/unit/graph/svg-spec.ts
Currently, g6 uses [numericjs](https://github.com/sloisel/numeric/) for the mds layouting algorithm.
This library has the following issues:
- it is not maintained since 8 years
- it often uses the `Function` constructor, which is prohibited by applications using CSP unless `unsafe-eval` is set, which is not recommended
- it has 19 open PRs that are unaddressed
- the author himself says that he doesn't have time to fix certain issues
- the SVD algorithm from numericjs that is used by G6 can return incorrect `NaN` outputs: https://github.com/sloisel/numeric/issues/75
We propose to use [ml-matrix](https://www.npmjs.com/package/ml-matrix) instead of numericjs.
This library is actively maintained, also provides the SVD algorithm, and has typescript support.
This pull request implements using …
=> refactor: use ml-matrix for the mds layout instead of numericJS

src/graph/controller/item.ts, src/graph/graph.ts, src/shape/shapeBase.ts, tests/unit/combo-issue-spec.ts, tests/unit/shape/combo-spec.ts
在默认的 setState 方法中限制不存在的 state，允许用户自定义 setState 方法。
https://github.com/antvis/G6/issues/1661
=> fix:在setState方法中限制不存在的状态

docs/api/Custom.en.md, docs/api/Custom.zh.md, docs/api/Group.en.md, docs/api/Group.zh.md, docs/api/nodeEdge/Item.en.md, docs/api/nodeEdge/Item.zh.md, docs/api/nodeEdge/shapeProperties.en.md, docs/api/nodeEdge/shapeProperties.zh.md, docs/manual/advanced/custom-combo.en.md, docs/manual/advanced/custom-combo.zh.md, docs/manual/advanced/custom-node.en.md, docs/manual/advanced/custom-node.zh.md, docs/manual/advanced/keyconcept/graphics-group.en.md, docs/manual/advanced/keyconcept/graphics-group.zh.md
1. 订正Graphics group的文档：去掉new Group()；
2. 增加shape上的setClip方法说明。
=> docs: fix graphics group doc; add setClip method in doc

package.json, src/behavior/drag-node.ts, src/graph/controller/item.ts, tests/unit/behavior/drag-node-spec.ts
fix #1787 
- 调用addItem新增节点时，若没有指定x,y怎默认为0
- drag节点时，若model.x, model.y未定义则默认为0
=> fix: drag new node without initial position

docs/manual/middle/states/defaultBehavior.en.md, docs/manual/middle/states/defaultBehavior.zh.md, package.json, src/behavior/drag-canvas.ts, src/graph/controller/event.ts, tests/unit/behavior/index-spec.ts
drag-canvas Behavior 增加 enableOptimize 配置项，开启后拖动画布过程中隐藏所有的边及节点上非 keyShape 部分，默认开启。
=> feat: hide edge & label when drag canvas

package.json, src/algorithm/connected-component.ts, src/algorithm/detect-cycle.ts, src/algorithm/index.ts, tests/unit/algorithm/connected-component-spec.ts, tests/unit/algorithm/detect-cycle-spec.ts
1. 提供支持寻找图中所有环路的函数 。对有向图来说返回所有**简单环**；对于无向图来说，返回所有**基本环**。可以传入一个节点为参数，则返回包含该节点的所有环。
```
/**
* 查找图中所有满足要求的圈
* @param graph 
* @param directed 是否为有向图
* @param nodeIds 节点 ID 的数组，若不指定，则返回图中所有的圈
* @param include 包含或排除指定的节点 
* @return [{[key: string]: Node}] 包含所有环的数组，每个环用一个Object表示，其中key为节点id，value为该节点在环中指向的下一个节点
*/
detectAllCycles(graph: IGraph, directed?: boolean, node?: INode)
```
使用时从Algorithm下导出 `import { detectAllCycles } = Algorithm`
2. 由于检测有向图所有环基于检测有向图的强连通分量，因此也支持了检测图的连通分量的算法。
`getConnectedComponents(graph: IGraph, directed?: boolean)`
=> feat: add detect all cycles for undirected and directed graph

src/plugins/menu/index.ts
1. handleMenuClick listerner not removed on menu hide
=> fix: handleMenuClick trigger multiple times

src/shape/xml.ts, stories/Shape/component/xml.tsx, tests/unit/shape/nodes/xml-spec.ts
- [x ] `npm test` passes
- [x ] tests and/or benchmarks are included
- [x ] commit message follows commit guidelines
XML定义节点现在支持style默认加入keyshape的style，style中的name指定style，加入name相符shape的style里面
=> feat: xml node adapt named style

package.json, src/graph/graph.ts, src/item/hull.ts, src/shape/hull/bubbleset.ts, src/shape/hull/convexHull.ts, src/types/index.ts, src/util/math.ts, src/util/path.ts, stories/Hull/component/hull.tsx, stories/Hull/component/interactiveHull.tsx, stories/Hull/hull.stories.tsx, tests/unit/graph/graph-hull-spec.ts
增加hull功能（graph.addHull(cfg: HullCfg)）：根据传入的节点数组，添加包裹轮廓。 
支持的配置项如下：
```
HullCfg {
id: string,
members?: Item[] | string[], // 节点实例或节点 Id 数组
nonMembers?: Item[] | string[], 
type?: string, // 'round-convex' /'smooth-convex' / 'bubble'
name?: string,
padding?: number,
style?: {
fill?: string,
stroke?: string,
opacity?: number
},
update?: string, // 'auto' / 'drag' / 'none' : 自动更新/ 拖拽调整member / 不更新
bubbleCfg?: BubblesetCfg
}
```
Hull的形状支持`round-convex` / `smooth-convex` / `bubble` 三种类型，默认为`round-convex`类型。`round-convex`为圆角凸包轮廓，`smooth-convex` 为平滑曲线凸包轮廓，这两种凸包轮廓不可绕开nonMembers；`bubble` 为自由凹包轮廓，可以绕开nonMembers。
下图中，蓝色为 `bubble` 类型轮廓， 绿色为`round-convex`类型轮廓。
hull实例可用的方法：
```
/**
* 更新数据
*/
public updateData(members: Item[] | string[], nonMembers: string[] | Item[])
/**
* 更新样式
*/
public …
```
=> feat: add hull to support using contour to include some items

examples/item/customNode/demo/pieChart.js
large arc flag and the y coordinate of the end position are wrong.
Current rendering:
Correct rendering:
=> fix: custom node "pieChart" demo

src/behavior/drag-canvas.ts
Avoid enabling drag when the non-left mouse button is pressed, causing optimization to be enabled.
Right click before fix：
Right click after fix：
=> fix: unnecessary mousedown.

examples/item/customNode/demo/jsxNode.js, examples/item/customNode/demo/jsxNodeWithAnimate.js, src/shape/xml.ts
1.修复 父节点存在marginLeft时，子元素定位异常
2.修复节点存在inline属性时，后续无inline元素排版错误
3.修复 水平inline元素中，高度不同时，下一个块级元素纵向偏移计算错误
4.text元素shapeHeight根据fontSize动态计算
Closes #2375
=>  fix: jsx node relative positioning error 

src/types/index.ts
=> fix: add missing `inactiveState` field in type `ModeOption`

src/algorithm/structs/queue/index.ts, src/graph/graph.ts, tsconfig.json
1. 删除combo 中的节点之前，先更新 Combo 的结构。
=> fix: update combo tree before remove item

src/types/index.ts, tests/unit/graph/controller/mode-spec.ts
Added `sensitivity` property to `ModeOption` interface as it was missing, but mentioned in [Official Documentation](https://g6.antv.vision/en/docs/manual/middle/states/defaultBehavior/#zoom-canvas) for `zoom-canvas` built-in behavior.
Also added a test suite, that covers that property.
=> fix(typings): add sensitivity prop to ModeOption \n\n\n Closes #2433

packages/site/examples/case/australiaFire/demo/index.js, packages/site/examples/case/edgeBundling/demo/index.js, packages/site/examples/case/largeGraph/demo/index.js, packages/site/examples/net/dagreFlow/demo/basicDagre.js, packages/site/examples/tool/contextMenu/demo/contextMenu.js, packages/site/examples/tool/toolbar/demo/self-toolbar.js, packages/site/examples/tool/toolbar/demo/toolbar.js, packages/site/examples/tool/tooltip/demo/tooltip.js, packages/site/examples/tool/tooltip/demo/tooltipLocalCustom.js, packages/site/examples/tool/tooltip/demo/tooltipPlugin.js, packages/site/examples/tool/tooltip/demo/tooltipPluginLocal.js
Delete the redundant comments for insertCss in demos.
These comments would be added automatically.
Check: 
- https://github.com/antvis/gatsby-theme-antv/blob/bcaa24f24310e8c97ffb89cf494d78b9db5b25e0/%40antv/gatsby-theme-antv/site/components/MdPlayground.tsx#L65
- https://github.com/antvis/gatsby-theme-antv/blob/bcaa24f24310e8c97ffb89cf494d78b9db5b25e0/%40antv/gatsby-theme-antv/site/components/PlayGround.tsx#L117
Since you also added them manually, these comments would be added twice.
Check: https://g6.antv.vision/en/examples/case/largeGraph#index
=> fix: remove redundant comments in demos

packages/plugin/.npmignore, packages/plugin/package.json
`@antv/plugin` 的 `.npmignore` 里面指定了发布 npm 包时忽略 `lib` 和 `es` 文件夹。我不知道为什么发布后 `lib` 文件夹还在，但是 `es` 文件夹的确没了
但是 `package.json` 里面指定了 `"module": "es/index.ts"`
https://github.com/antvis/G6/blob/d923571707b6c7882f9443fa0744c14b1724831e/packages/plugin/package.json#L6
这就导致一些检查严格的编译工具/脚手架（例如vite）报错
另外 package.json 里面永远应该导出 js 文件而不是 ts
=> fix(plugin): don't ignore `lib` `es` folder when publishing, also export `js` not `ts`

packages/plugin/src/menu/index.ts
=> fix: show menu when triggered by click

packages/site/package.json
简而言之，吾辈使用 windows 启动 website 模块的本地服务器时，会因为无法使用 `GATSBY=true` 的方式设置环境变量而失败，所以吾辈使用了跨平台的 cross-env 设置环境变量。
另外，启动之前似乎还需要在根目录运行 `build:all`，但会失败（mobile 模块），但之后可以运行 website 了，如果可能，希望将之添加到项目的构建文档中。
=> docs(site): 修复 site 模块在_windows_上本地启动无法设置环境变量的问题，使用通用的 cross-env 包

packages/site/docs/manual/middle/elements/combos/defaultCombo.en.md, packages/site/docs/manual/middle/elements/combos/defaultCombo.zh.md, packages/site/docs/manual/middle/elements/methods/elementIndex.en.md, packages/site/docs/manual/middle/elements/methods/elementIndex.zh.md
---
另外，强烈建议添加 cli 检查引用关系，毕竟只针对变动的文件 + worker_threads 性能上也并非无法接受的，总比现在这种只有有人碰到了才能发现问题更好
个人推荐 [remark.js](https://remark.js.org/) 系列工具包，处理 markdown ast 非常方便
=> docs(site): 修复节点分组 Combo 和 图形分组 Group 引用链接的错误

packages/core/src/graph/graph.ts, packages/core/src/util/math.ts
This adds an option to perform an animated zoom.
The only "issue" I see with this implementation is that the zoom function will return true/false before the animation conclusion, but it seems this is a common issue with several other functions
Close https://github.com/antvis/G6/issues/3233
=> feat: add zoom animation

packages/core/src/util/graphic.ts
setItemState will change shape.attrs.path  into a object
cloneBesidesImg 在复制类型为 path 的 subShape 的 attrs 时会把 path 改变为对象，导致该 subShape 消失。当 item 有两个或以上的 state 时，且 stateStyles 都包含 subShape 的 style，取消某个 state 会导致该现象出现。
=> fix: fix path shape will disappear after setItemState

packages/core/src/graph/graph.ts
In my previous PR adding the animated zoom, I forgot one use case where the event was not emitted.
=> fix: missing event with animated zoom

packages/core/src/graph/graph.ts, packages/core/tests/unit/graph/graph-spec.ts
This fix allows enabling the stack operations at runtime, in use cases where the user wants to have control over the undo/redo functionality
=> fix: allow enabling stack operations at runtime

packages/core/src/types/index.ts
按照官网实例使用 shortcuts-call ，发现类型错误
=> fix: 修复G6内置 shortcuts-call behavior 类型错误

packages/plugin/src/tooltip/index.ts, packages/site/docs/manual/middle/elements/advanced-style/set-label-bg.en.md, packages/site/docs/manual/middle/elements/advanced-style/set-label-bg.zh.md, packages/site/package.json
使 tooltip 插件的 className 配置支持空格分割的多个class，例如：`g6-tooltip tooltip-1`
修改前会生成：`<div class="g6-tooltip" tooltip-1></div>`
=> fix: [tooltip plugin] wrap className in quotes when createDom to support multi classname

packages/plugin/src/toolBar/index.ts, packages/site/docs/api/Plugins.en.md, packages/site/docs/api/Plugins.zh.md
1. 将 toolbar 的默认操作抽离成函数，更加原子化，这样以便于用户初始化是配置 handleClick 时可以使用
2. 将 handleDefaultOperator 由 private 改为 public，这样用户如果只是想修改一个事件的默认行为，直接根据 code 判断，不修改的直接调用这个方法即可，目前需要用户全盘更改，非常麻烦
3. 更新使用文档
这是我在工作中实际的一个例子，现在的版本只能这么做，且在ts中会报lint 错误
```js
export const toolbar = new G6.ToolBar({
position: { x: 400, y: 20 },
handleClick: function(code, graph) {
if(['redo', 'undo'].includes(code)) {
toolbar[code]()
// 这在 g6 是一个私有函数，不能直接调用
toolbar.handleDefaultOperator?.('autoZoom', graph);
return
}
toolbar.handleDefaultOperator?.(code, graph)
},
});
```
这个变更后能力可原子化调用，上面的例子可以改为：
```js
export const toolbar = new G6.ToolBar({
position: { x: 400, y: 20 },
handleClick: function(code, graph) {
if(['redo', 'undo'].includes(code)) {
toolbar[code]()
// 这在 g6 是一个私有函数，不能直接调用
toolbar.autoZoom()
return
} …
```
=> refactor: 将 toolbar plugin 的默认操作函数抽离

packages/core/src/element/node.ts, packages/core/src/interface/shape.ts, packages/core/src/types/index.ts, packages/core/src/util/graphic.ts, packages/core/tests/unit/shape/node-spec.ts, packages/core/tests/unit/util/graphic-spec.ts
This PR introduces `truncateLabelByLength` - a utility function which can be used to shorten a label by a specific character length. If the target label is shorter than the specified length, an ellipsis is added. The `maxLength` property of a label's style is what can be used to specify the desired length.
=> Truncate node labels

packages/core/src/item/item.ts
`uniqueId` should be used only when `id` is undefined.
Then case `id === 0` can be user configurable, instead of be changed with item-typed uniqueId:
=> fix: only regenerate id when id is undefined

packages/core/src/graph/graph.ts, packages/core/src/interface/graph.ts, packages/core/tests/unit/graph/graph-spec.ts
This PR introduces `additionalFilter` parameter on `findAllByState`. This allows for extra filtering e.g don't select nodes with `visible: false`.
=> fix: findAllByState should not select hidden nodes

packages/react-node/README.md, packages/react-node/docs/index.en-US.md, packages/react-node/docs/index.md, packages/react-node/src/API/rect.en-US.md, packages/react-node/src/API/rect.md, packages/react-node/src/ReactNode/Group.tsx, packages/react-node/src/ReactNode/Shape/Rect.tsx, packages/react-node/src/ReactNode/Shape/Text.tsx
1. `React.FC` (which is used by all the shapes) got [`children` props removed](https://stackoverflow.com/questions/71788254/react-18-typescript-children-fc/71800185#71800185) since `React v18`. Adding `children` in [common](https://github.com/antvis/G6/blob/5a7681c85f891ecb50e458034c1545d3c9bbdbd5/packages/react-node/src/ReactNode/Group.tsx#L5-L43) `Shape` props shouldn't break it for past `React` versions but would add compatibility with the latest.
2. (non-ts) [Examples](https://github.com/antvis/G6/blob/5a7681c85f891ecb50e458034c1545d3c9bbdbd5/packages/react-node/docs/index.md?plain=1#L22) have `Rect` as a container with no `style` property. `Rect` does have non-optional (i.e. required) `style` which means it should've been used with `style` containing at least an empty object like …
=> fix: react node typings inaccuracy

packages/core/src/graph/controller/view.ts, packages/core/src/graph/graph.ts, packages/core/src/interface/graph.ts, packages/core/tests/unit/graph/controller/view-spec.ts
This PR implements the `fitItems` function. This allows to fit a subset of the graph, eg: fit only the selected items.
This is useful with big graphs, where you want to have a closer look at a bunch of nodes.
In this example I'm using the `fitItems` function on the selected nodes via a keyboard shortcut:
`animate` false
https://user-images.githubusercontent.com/2861371/182404337-01167ecc-acfc-4ec2-98ce-c9af4da3b1e7.mp4
`animate` true
https://user-images.githubusercontent.com/2861371/182404386-77fbaccb-3fdb-4167-9bc6-ff2735257def.mp4
=> feat: fitItems function

packages/core/src/types/index.ts, packages/pc/src/behavior/brush-select.ts, packages/pc/tests/unit/behavior/brush-select-spec.ts, packages/site/docs/manual/middle/states/defaultBehavior.en.md
This PR adds support for selecting combos using the "brush-select" behavior. A new "includeCombos" parameter is added (default = `false`) to explicitly enable this effect.
Combos are selected when their midpoint is included in the rectangular brush area (similarly to edges) - most obvious when the combo is expanded:
https://user-images.githubusercontent.com/16387428/193301708-6ba683f4-e7e8-4f6a-9007-f512b5597494.mp4
=> feat: add combo support in brush-select behavior

packages/site/docs/api/shapeProperties.en.md, packages/site/docs/manual/middle/elements/shape/shape-and-properties.en.md
Update typo in `endArrow` docs
=> docs: Update typo in docs

packages/core/src/graph/controller/item.ts
This PR fixes the animate property initialization for new combos, which should be inherited from the graph rather than just set to false.
Suppose I created a graph with `animate: true`. Then I try to make a combo to group some nodes:
Before the fix
https://user-images.githubusercontent.com/16387428/195822382-3a5f42b8-bb32-4275-902f-8fb683789060.mp4
After the fix
https://user-images.githubusercontent.com/16387428/195824011-34dbc32b-f3e8-41ea-9c12-11897f10eb3d.mp4
=> fix: Fix combos to inherit animation setting from graph

packages/core/src/graph/graph.ts, packages/core/src/util/graphic.ts, packages/core/tests/unit/graph/graph-combo-spec.ts, packages/core/tests/unit/state/image-state-spec.ts, packages/pc/tests/unit/graph/graph-combo-spec.ts, packages/site/docs/api/Util.en.md
This PR fixes the update of the `comboTrees` structure involved in a `createCombo()` call. In particular:
- Combos moved inside the newly create combo were not removed from the `comboTrees`, which means they ended up duplicated (in the original place and under the new combo)
- Combos moved inside the new combo had no children
Before the fix:
https://user-images.githubusercontent.com/16387428/195824784-cdfda271-ad60-495a-9562-591f2331d5c9.mp4
After the fix:
https://user-images.githubusercontent.com/16387428/195824847-fdb3fece-6b69-4db3-ba08-f5005a7b4732.mp4
=> fix: createCombo didn't update the "comboTrees" correctly

packages/pc/src/behavior/drag-combo.ts, packages/pc/src/behavior/drag-node.ts
This PR improves combo resizing when using the `drag-node` and `drag-combo` behaviors with `onlyChangeComboSize=true`, so that it happens while dragging and not only when dropping the dragged item
Before: 
https://user-images.githubusercontent.com/2861371/215104957-9adc785f-e119-41e7-9f23-969b2df4dd64.mp4
After:
https://user-images.githubusercontent.com/2861371/215105004-0969f44f-4f4e-4491-84a8-a0648b6b43ab.mp4
=> feat: resize combos when dragging contained elements

packages/g6/src/runtime/controller/layout.ts, packages/g6/src/runtime/graph.ts, packages/g6/src/types/index.ts, packages/g6/src/types/layout.ts, packages/g6/tests/unit/layout-spec.ts
#4339 
* 关闭 G 的样式解析以提升性能
* 增加 spec 中未指定 `layout` 的处理：
```js
// 初始化时未指定布局
graph = new G6.Graph({
container,
width: 500,
height: 500,
type: 'graph',
data,
});
```
此时应用默认值的逻辑如下：
* `data` 数据中所有节点都不包含用户指定的 `x/y`，应用 grid 布局
* `data` 数据中有部分节点指定了 `x/y`，不使用任何内置布局，认为是用户自定义布局，此时未指定的坐标默认为 0
测试用例：https://github.com/antvis/G6/pull/4345/files#diff-1ebcdba2da6b0c76dd377fd9d508056cd4a8e3952ae22594d176dab467ac799cR10-R120
=> 支持更多场景下的布局过渡动画

packages/element/src/nodes/donut.ts
This fixes a bug that was introduced in [this PR](https://github.com/antvis/G6/commit/a94c50a7989fb2915fad17bf2f5598a4bd367670#diff-084ec8a46f517a9858a776d184208fe0a59b13d3a65c84f21d10be7c8349c486). The problem is that the `isBig` variable can be a boolean, when it should only be a number, so that it can be correctly included in the fan path. When using the SVG renderer, this can cause invalid SVGs to be generated, which the browser does not render, so the donuts do not appear.
=> fix: donut rendering - isBig must be number for use in path

packages/g6/src/runtime/controller/index.ts, packages/g6/src/runtime/controller/item.ts, packages/g6/src/runtime/controller/viewport.ts, packages/g6/src/runtime/graph.ts, packages/g6/src/types/animate.ts, packages/g6/src/types/graph.ts, packages/g6/src/types/hook.ts, packages/g6/src/types/view.ts, packages/g6/src/util/shape.ts, packages/g6/tests/unit/view-spec.ts
#4344 
TODO：
```js
graph.getZoom(); // 当前缩放等级，例如 2
graph.getCameraRoll(); // 当前相机旋转角度，例如 30 度
graph.getCameraPosition(); // 当前相机在 Canvas 坐标系下的位置
```
=> 使用相机实现视口相关功能

packages/pc/src/behavior/drag-combo.ts, packages/pc/src/behavior/drag-node.ts, packages/site/.dumi/pages/largegraph.en.tsx, packages/site/.dumi/pages/largegraph.zh.tsx, packages/site/package.json, packages/site/pages/canvas-menu.tsx, packages/site/pages/large-graph-register.tsx, packages/site/pages/largegraph.tsx, packages/site/pages/legend-panel.tsx
After these changes, the initial cursor position for the `drag-node` behaviour is saved on the initial mouse down instead of after the first drag event, so the cursor and dragged node don't missalign when dragging starts.
=> fix: Node dragging starting one event too late.

packages/g6/package.json, packages/g6/src/item/combo.ts, packages/g6/src/item/edge.ts, packages/g6/src/item/item.ts, packages/g6/src/item/node.ts, packages/g6/src/runtime/controller/interaction.ts, packages/g6/src/runtime/controller/item.ts, packages/g6/src/runtime/graph.ts, packages/g6/src/stdlib/behavior/click-select.ts, packages/g6/src/stdlib/behavior/drag-node.ts, packages/g6/src/stdlib/index.ts, packages/g6/src/types/hook.ts, packages/g6/src/util/canvas.ts, packages/g6/src/util/item.ts, packages/g6/tests/unit/drag-node-spec.ts, packages/g6/tsconfig.json
Breaking changes:
1. ⭐️ 拖动过程可以按下 ESC 来取消拖动！
2. ⭐️ delegate 在交互层渲染，性能更好！
3. ⭐️ 新增 enableTransient ，复杂图形下性能更好，默认开启
4. 不再根据 lock 数据锁定，用户通过 shouldEnable 处理
5. 去掉 updateEdge 选项，为了性能可以用 enableTransient 或 enableDelegate
6. enableDebounce 改为 debounce ，可指定毫秒
7. enableOptimize 改为 hideRelatedEdges ，语义明确
其他模块改动：
1. 实现 hide/show item
2. 实现 drawTransient 对 item 的支持
=> feat: add drag-node behavior

.github/workflows/issue_hunt_replay.yml, ISSUEHUNT.en-US.md, ISSUEHUNT.md
Github Workflow 对引号内冒号敏感
之前的标签名为 `IH: Reward/悬赏` 会有异常，因此改为 `Reward/悬赏`
=> fix: fix issue that cause workflow failed

ISSUEHUNT.en-US.md, ISSUEHUNT.md
`IH: Reward/悬赏` -> `Reward/悬赏` 后忘更新链接了
=> docs: fix issue hunt description typos

packages/site/docs/api/Items/comboMethods.en.md, packages/site/docs/api/Items/comboMethods.zh.md, packages/site/docs/api/Items/edgeMethods.en.md, packages/site/docs/api/Items/edgeMethods.zh.md, packages/site/docs/api/Items/nodeMethods.en.md, packages/site/docs/api/Items/nodeMethods.zh.md, packages/site/docs/manual/middle/elements/combos/defaultCombo.en.md, packages/site/docs/manual/middle/elements/combos/defaultCombo.zh.md
- [ x] commit message follows commit guidelines
（一）在文档发现几处Demo的URL点击报错404，此PR解决中文与英文文档中的404 not found 错误。经过查看example，发现这个错误是由于URL中没有加上锚点“#”导致的。根据example中的对应地址修改了几处URL。
修改了以下pages：
1.  /manual/middle/elements/combos/default-combo
2. /api/items/combo-methods
3. /api/items/edge-methods
4. /api/items/node-methods
（二）在以下pages中发现有几处笔误，已修改
1. /api/items/combo-methods。将自定义节点与内置节点修改为自定义Combo与内置Combo
2. /api/items/edge-methods。 将自定义节点修改为自定义边
经查阅，仅中文文档出现错误，英文文档无误。
=> Fix issue#4552, another 404 not found and  typo errors

packages/core/src/interface/graph.ts
Graph.d.ts 类型定义修改：off 方法参数可选，不传入参数的时候，代表移除所有事件监听
=> fix(typings): graph off 方法支持不传入参数，会移除所有事件监听

packages/g6/src/stdlib/item/node/base.ts, packages/g6/tests/intergration/demo/bugReproduce.ts
In the badge function,G6 v5 allows users to pass in `rightTop`, `leftTop`,`topLeft`,`bottomLeft`,`leftBottom`, etc., but not `topRight`. In my opinion, That would be better to add a `topRight` position configuration. 
- old version
```typescript
case 'rightTop':
pos.x = keyShapeBBox.max[0] - bgHeight / 2 + offsetX;
pos.y = keyShapeBBox.min[1] + size / 4 + offsetY;
break;
```
- new version
```typescript
case 'rightTop':
case 'topRight':
pos.x = keyShapeBBox.max[0] - bgHeight / 2 + offsetX;
pos.y = keyShapeBBox.min[1] + size / 4 + offsetY;
break;
```
=> Feat: add  'topRight'  position configuration in BadgesShapes

packages/g6/src/stdlib/item/edge/base.ts, packages/g6/tests/intergration/demo/bugReproduce.ts
The reason for this bug is that `Boolean(labelShapeProps)` is always **true** value, so the below code snippet always enters `if` block and never turn to the `else` block. 
When the users do not set `labelShape` but `iconShape`, `referShape` is `undefined`, then throw the error.
- old version:
```typescript
if (labelShapeProps) {
const referShape = labelBackgroundShape || labelShape;
const referBounds =
this.boundsCache.labelBackgroundShapeGeometry ||
this.boundsCache.labelShapeGeometry ||
referShape.getGeometryBounds();
}else{
//...
}
```
I replace `labelShapeProps` with `labelShape` to fix the bug. When the user hasn't set `labelShape` configuration, it will turn to `else` block to handle this.
```typescript
if (labelShape) {
const referShape = labelBackgroundShape || labelShape;
const …
```
=> V5 fix label shape error

packages/site/docs/api/Items/comboMethods.zh.md
- [x ] tests and/or benchmarks are included
G6官网文档格式有误，位置在API/元素方法和配置/combo实例方法，问题截图如下：
把packages/site/docs/api/Items/comboMethods.zh.md中的格式问题修复正确。
=> G6官网文档格式错误修复 （文档位置：API/元素方法和配置/combo实例方法）

packages/g6/src/item/item.ts, packages/g6/tests/intergration/demo/bugReproduce.ts
Sometimes, in the data, The users may made an error in the `type` attribute or passed in an unregistered shape by mistake, like this:
```typescript
const data = {
nodes: [
{
id: 1,
data: {
x: 100,
y: 100,
type: 'circle-node',
},
},
{
id: 2,
data: {
x: 200,
y: 100,
type: 'star-node',
},
},
],
edges: [
{
id: 'edge1',
source: 1,
target: 2,
data: {
type: 'custom-edge'
}
}
]
};
```
If the `star-node` and `custom-edge` haven't been registered, An error message will be :"TypeError: RenderExtension is not a constructor." 
It seems be better to make this error message more readable to remind users of where is the original error from, making it easier for users to troubleshoot and modify.
```typescript
const lodStrategy = modelLodStrategy
? formatLodStrategy(modelLodStrategy)
: theme.lodStrategy; …
```
=> chore: make the error message more readable

packages/g6/src/stdlib/index.ts, packages/g6/src/stdlib/item/edge/index.ts, packages/g6/src/stdlib/item/edge/quadratic.ts, packages/g6/tests/intergration/demo/quadratic.ts, packages/g6/tests/intergration/index.ts, packages/g6/tests/unit/quadratic-spec.ts
- [ x ] `npm test` passes
- [ x ] tests and/or benchmarks are included
- [ x ] commit message follows commit guidelines
- 沿用了v4的参数，`curvePosition`,`controlPoints`,`curveOffset`。
- curvePosition：表示要在线段的百分之几位置添加控制点，是一个0-1的数
- controlPoints：具体的控制点，因为是二次贝塞尔曲线，因此只允许添加一个组坐标（如果需要多个控制点可以使用cubic）
- curveOffset：控制点距离两端点连线的距离，可理解为控制边的弯曲程度
- 添加了单元测试
1. 完成了基本功能的迁移，但是类型没有加上，因为我发现类似于`LineStyleProps`,`PathStyleProps`都写在了@antv/g-lite里面，必须继承`BaseStyleProps`。
3. 我直接在代码中使用了as any来逃避了类型检查，请问我这边应该如何加上这个`QuadraticStyleProps` interface 呢？
4. keyShape中还需要有其他的参数吗？
5. 可以帮忙review一下，我会按照你们的建议进行修改
=> feat: v5-quadratic

packages/g6/src/stdlib/index.ts, packages/g6/src/stdlib/plugin/tooltip/index.ts, packages/g6/tests/intergration/demo/tooltip.ts, packages/g6/tests/intergration/index.ts, packages/g6/tests/unit/plugins/tooltip-spec.ts
#4578 
- fixToNode
- 不fixToNode 
- 支持动态传入数据，`getContent(e)` 函数目前支持返回` HTMLDivElement | string | Promise<HTMLDivElement | string>`，getContent 变为异步函数，当返回Promise<>类型时，会使用await拿到其中的值，这点与v4不同。初次之外，为了减轻服务器压力，代码中避免了重复fetch。
- 单测测了使用不同配置`getContent`的情况，如果不齐全可以再补 :)
=> feat: v5-plugin-tooltip

.github/workflows/weekly.yml
每周日晚上20点统计每周活跃情况，报告默认会存到 `workflows/weekly-stats` 分支下，以当日日期命名
报告示例：
=> chore: add weekly stats

packages/g6/src/item/combo.ts, packages/g6/src/item/edge.ts, packages/g6/src/item/item.ts, packages/g6/src/item/node.ts, packages/g6/src/runtime/controller/item.ts, packages/g6/src/stdlib/behavior/drag-node.ts, packages/g6/src/stdlib/item/node/base.ts, packages/g6/src/types/theme.ts, packages/g6/src/util/event.ts, packages/g6/src/util/zoom.ts, packages/g6/tests/demo/demo/rect.ts
- fix: halo styles for rect node
Actual attributes in the keyShape have higher priority than the style config props of keyShape. The wrong style:
Correct style:
- fix: number id of nodes and edges cause item not found problem in item update functions;
=> fix: halo styles for rect node

packages/g6/src/runtime/controller/item.ts, packages/g6/src/util/item.ts, packages/g6/tests/integration/layouts-dagre.spec.ts
chore: use map instead of object to cache the items.
Fix the problem that the Object.keys converts all the keys in itemMap object into strings, leading to wrong number type id of nodes and edges.
=> chore: use map instead of object to cache the items

packages/g6/src/runtime/controller/data.ts, packages/g6/src/stdlib/data/validateData.ts
fix: data validate with data update
之前数据校验仅检查了增量数据部分，没有结合已有数据。导致如果增量加的边的起点和终点在已有数据中，会被判断为非法的边
=> fix: data validate with data update

packages/g6/src/runtime/graph.ts, packages/g6/tests/index.html, packages/g6/tests/main.ts
在 v5 实现四个 API：
graph.downloadImage 画布导出图片，图片仅包含画布可见区域部分内容
graph.downloadFullImage 导出包含全图的图片(graph 内容可能超出视口范围)
graph.toDataURL 返回可见区域的图的 dataUrl，用于生成图片
graph.toFullDataURL 返回整个图（包括超出可见区域的部分）的 dataUrl，用于生成图片
在preview界面新增了下载图片选项，用于调用api下载当前图片
=> feat: add graph download api

packages/site/examples/item/customNode/demo/scrollNode.js
1. `npm test` failed on the latest master due to `tests/unit/shape/combo-collapsed-pos-spec.ts`.
2. The site doesn't have any existing tests, so I cannot add test case for the fix.
In the demo page https://g6.antv.antgroup.com/en/examples/item/customNode#scrollNode, it will crash after you drag the node.
This pr fixed it.
=> fix: scrollNode demo crash

packages/g6/src/item/edge.ts, packages/g6/src/item/item.ts, packages/g6/src/item/node.ts, packages/g6/src/runtime/controller/data.ts, packages/g6/src/runtime/controller/item.ts, packages/g6/src/runtime/graph.ts, packages/g6/src/stdlib/behavior/drag-canvas.ts, packages/g6/src/stdlib/behavior/index.ts, packages/g6/src/stdlib/behavior/zoom-canvas.ts, packages/g6/src/stdlib/data/mapNodeSize.ts, packages/g6/src/stdlib/data/transformV4Data.ts, packages/g6/src/stdlib/data/validateData.ts, packages/g6/src/stdlib/item/edge/base.ts, packages/g6/src/types/graph.ts, packages/g6/src/types/view.ts, packages/g6/src/util/event.ts, packages/g6/src/util/layout.ts, packages/g6/src/util/point.ts, packages/g6/src/util/shape.ts, packages/g6/tests/demo/combo/combo-basic.ts, packages/g6/tests/demo/data/graphCore.ts, packages/g6/tests/demo/index.ts, packages/g6/tests/demo/layouts/circular.ts, packages/g6/tests/demo/layouts/dagre-update.ts, packages/g6/tests/demo/performance/performance.ts, packages/g6/tests/demo/tree/treeGraph.ts, packages/g6/tests/integration/behaviors-create-edge.spec.ts, packages/g6/tests/unit/view-spec.ts, packages/site/examples/feature/features/demo/itemAnimates.js, packages/site/examples/scatter/changePosition/demo/viewAnimates.js
- chore: remove userGraphCore
之前已经将数据处理流程（transform）提前到 userGraphCore 读取数据前，目的是保证 userGraphCore 读取到的是正确的数据格式。这样一来，userGraphCore 没有存在的必要，数据流程可简化为：
用户输入数据 - transformers -> graphCore - mapper -> display data
简化数据流，便于维护和问题定位，减少不必要的数据存储和计算开销。
- fix: edge update problems;
- fix: autoFit at first render and layout
布局完成后的屏幕适配，此时可能因为有动画，还没有完成图的更新。应当根据布局完成后节点的位置范围，进行图适配的计算；
- fix: nodes visibility problem while tree graph collapse and expand
树图收起后快速展开，可能出现子节点未正确显示的问题
=> chore: remove userGraphCore

packages/g6/src/runtime/graph.ts
`position: fixed` will make a lot of problems especially when page gets scrolled, so `absolute` is a better choice.
Sigma.js also arrange canvases like this:
=> fix: use position absolute instead of fixed to make canvases overlap each other

packages/g6/src/util/shape.ts, packages/g6/src/util/shape3d.ts
dagre 例子中切换布局，在 Canvas 渲染器下会出现已失效的边又被渲染出来的情况。
按照 DOM API 的说明，对于一个已有父节点的子节点，appendChild 会首先从父节点上移除它，再添加。
updateShapes 方法中会重复 appendChild 子节点到同一个父节点上，此时会造成多余的移除和添加，即使父子关系都没有发生改变。
修改方式在 G6 这边需要判断下 newShape 当前的父节点是不是已经为 group 了，此时也不需要调用 appendChild 了。但这个逻辑不能实现在 appendChild 方法内部，基于以上说明。
修复后效果如下，切换布局后也不会出现多余的边了：
=> fix: avoid reappending exited shape

.github/workflows/deploy.yml, README.en-US.md, README.md, package.json
* 修复了 deploy workflow
* 修改了 Readme 文档
=> chore: update deploy workflow

packages/site/docs/apis/graph/Graph.en.md, packages/site/docs/apis/graph/Graph.zh.md, packages/site/docs/apis/graph/Specification.en.md, packages/site/docs/apis/graph/Specification.zh.md
=> docs: update graph instance methods docs

packages/pc/src/graph/controller/event.ts
`case "dragend"` already exists above:
https://github.com/antvis/G6/blob/304db350dcb05e4a6e1b341a1465e3c27facc699/packages/pc/src/graph/controller/event.ts#L91
this extra line will result to esbuild warning:
```
(esbuild plugin) [esbuild] (.nuxt/dist/server/_nuxt/electronic-372bd534.js:31248:13) This case clause will never be evaluated because it duplicates an earlier case clause
```
=> fix: remove duplicated dragend case

packages/g6/src/stdlib/index.ts, packages/g6/src/stdlib/item/node/index.ts, packages/g6/src/stdlib/item/node/plane.ts, packages/g6/src/util/shape3d.ts, packages/site/docs/apis/shape/PlaneGeometryProps.en.md, packages/site/docs/apis/shape/PlaneGeometryProps.zh.md, packages/site/examples/feature/features/demo/layerTopology.js, packages/site/examples/feature/features/demo/meta.json
feat: 新增plane平面节点
feat: 添加demo案例
[screenity.webm](https://github.com/antvis/G6/assets/39400058/b7bffa50-0baf-4adf-8817-56ec4473095e)
=> feat: add plane-node for v5 

packages/core/src/element/combo.ts, packages/core/src/element/edge.ts, packages/core/src/element/hull/bubbleset.ts, packages/core/src/element/xml.ts, packages/core/src/graph/controller/item.ts, packages/core/src/graph/controller/layout.ts, packages/core/src/interface/graph.ts, packages/core/src/item/node.ts, packages/core/src/util/path.ts
=> chore(core): fix typo

packages/g6/src/item/edge.ts
修复官网元素 demo 边标签错位的问题
画布加载时，若元素未设置默认位置而是采用 layout，dataOriginPosition 为 `{x: 0, y: 0}` 会聚集在左上角
修复前
修复后
=> fix: fix incorrect label position on edges

packages/g6/src/item/item.ts, packages/g6/src/plugin/register.ts, packages/g6/src/runtime/controller/item.ts, packages/g6/src/runtime/controller/theme.ts, packages/g6/tests/unit/register.spec.ts
调整了 getPlugins 的返回值类型，调整前返回的是一个数据，需要遍历查找，调整后是一个 object，可以直接通过 `key` 取到对应的插件
> Adjusted the return value type of getPlugins. Before adjustment, the returned value is a data, which needs to be searched through traversal; after adjustment, it is an object, which can be directly obtained from the corresponding plug-in through the key
=> refactor(register): adjust getPlugins returns type

packages/g6/__tests__/demo/static/index.ts, packages/g6/__tests__/demo/static/node-circle.ts, packages/g6/__tests__/demo/static/shape-icon.ts, packages/g6/__tests__/integration/snapshots/static/node-circle.svg, packages/g6/__tests__/integration/snapshots/static/shape-icon.svg, packages/g6/__tests__/unit/utils/element.spec.ts, packages/g6/__tests__/unit/utils/prefix.spec.ts, packages/g6/src/elements/nodes/circle.ts, packages/g6/src/elements/nodes/index.ts, packages/g6/src/elements/shapes/base-shape.ts, packages/g6/src/elements/shapes/icon.ts, packages/g6/src/elements/shapes/index.ts, packages/g6/src/types/node.ts, packages/g6/src/utils/element.ts, packages/g6/src/utils/prefix.ts
```ts
const style = {
// key
cx: 100,
cy: 100,
fill: 'red',
r: 40,
// label
labelText: 'circle node',
labelFontSize: 14,
labelFill: 'pink',
labelPosition: 'bottom',
// badge
badgeOptions: [],
// anchor
anchorOptions: [],
// icon
iconSrc: 'https://gw.alipayobjects.com/zos/basement_prod/012bcf4f-423b-4922-8c24-32a89f8c41ce.svg',
iconWidth: 32,
iconHeight: 32,
// halo
haloOpacity: 0.4,
}
const circle = new Circle({ style });
```
=> feat: add circle node element

packages/g6/__tests__/unit/runtime/data.spec.ts, packages/g6/__tests__/unit/utils/change.spec.ts, packages/g6/__tests__/unit/utils/data.spec.ts, packages/g6/src/constants/change.ts, packages/g6/src/constants/index.ts, packages/g6/src/runtime/data.ts, packages/g6/src/types/change.ts, packages/g6/src/types/index.ts, packages/g6/src/utils/change.ts, packages/g6/src/utils/data.ts
初版 G6 5.0 的更新机制是基于 graphlib `change` 事件驱动的，但与 G6 数据结构并非完全匹配，且需要依赖 Graph 进行事件监听和调度，提高了 Graph 的复杂度，其更新机制如下（以 `addData` 为例：）
1. addData 方法中添加一次性 graphlib `change` 事件监听
2. 触发 data controller `datachange` 事件，操作数据
3. 操作数据后触发 `change` 事件，回调中触发 `itemchange` 事件，更新元素
变更后，由 data controller 维护数据变更，更新机制如下（以 `setData` 为例）：
1. setData 中调用 data controller setData 方法
2. data controller 处理数据，并提交数据变更任务
3. element controller 接受数据变更任务
4. 绘制阶段：element controller 合并数据变更任务队列，更新元素
---
The update mechanism of the initial version G6 5.0 is driven by the graphlib change event, but it is not fully compatible with the G6 data structure. It requires reliance on the Graph for event monitoring and scheduling, increasing the complexity of the Graph. The update mechanism is as follows (using addData as an example):
1. Add …
=> refactor: data controller support collect changes

packages/g6/__tests__/demo/animation/edge-cubic.ts, packages/g6/__tests__/demo/animation/index.ts, packages/g6/__tests__/demo/static/edge-cubic-horizontal.ts, packages/g6/__tests__/demo/static/edge-cubic-vertical.ts, packages/g6/__tests__/demo/static/edge-cubic.ts, packages/g6/__tests__/demo/static/index.ts, packages/g6/__tests__/integration/animation.spec.ts, packages/g6/__tests__/integration/snapshots/animation/edge-cubic-0(1_3).svg, packages/g6/__tests__/integration/snapshots/animation/edge-cubic-1000(3_3).svg, packages/g6/__tests__/integration/snapshots/animation/edge-cubic-500(2_3).svg, packages/g6/__tests__/integration/snapshots/static/edge-cubic-horizontal.svg, packages/g6/__tests__/integration/snapshots/static/edge-cubic-vertical.svg, packages/g6/__tests__/integration/snapshots/static/edge-cubic.svg, packages/g6/__tests__/integration/snapshots/static/edge-line.svg, packages/g6/__tests__/integration/snapshots/static/edge-quadratic.svg, packages/g6/__tests__/integration/snapshots/static/layered-canvas.svg, packages/g6/__tests__/integration/snapshots/static/node-circle.svg, packages/g6/__tests__/integration/snapshots/static/shape-badge.svg, packages/g6/__tests__/integration/snapshots/static/shape-icon.svg, packages/g6/__tests__/integration/snapshots/static/shape-label.svg, packages/g6/__tests__/integration/static.spec.ts, packages/g6/__tests__/main.ts, packages/g6/src/elements/edges/cubic-horizontal.ts, packages/g6/src/elements/edges/cubic-vertical.ts, packages/g6/src/elements/edges/cubic.ts, packages/g6/src/elements/edges/index.ts, packages/g6/src/utils/edge.ts
`cubic`
`cubic-horizontal`
`cubic-vertical`
```ts
type CubicKeyStyleProps = PathStyleProps & {
/**
* <zh/> 边的起点
* <en/> The source point. Represents the start of the edge
*/
sourcePoint: Point;
/**
* <zh/> 边的终点
* <en/> The target point. Represents the end of the edge
*/
targetPoint: Point;
/**
* <zh/> 控制点数组，用于定义曲线的形状。如果不指定，将会通过`curveOffset`和`curvePosition`来计算控制点
* <en/> Control points. Used to define the shape of the curve. If not specified, it will be calculated using `curveOffset` and `curvePosition`.
*/
controlPoints?: [Point, Point];
/**
* <zh/> 控制点在两端点连线上的相对位置，范围为`0-1`
* <en/> The relative position of the control point on the line, ranging from `0-1`
*/
curvePosition?: number | [number, number];
/**
* <zh/> 控制点距离两端点连线的距离，可理解为控制边的弯曲程度
* <en/> The distance of the control point from the …
```
=> feat(edge): add cubic edge element and its vertical and. horizontal variants

packages/g6/tsconfig.json
如图所示，指定 `baseUrl` 会导致 `vscode` 提示路径使用简写路径，移除后提示为正常相对路径
---
As shown in the figure, specifying `baseUrl` causes `vscode` to prompt the path to use the abbreviated path, which prompts the normal relative path when removed
移除前 / Before remove
移除后 / After remove
=> chore: update tsconfig

packages/g6/__tests__/demo/static/controller-layout-circular.ts, packages/g6/__tests__/demo/static/controller-layout-compact-box.ts, packages/g6/__tests__/demo/static/controller-layout-d3-force.ts, packages/g6/__tests__/demo/static/controller-layout-dagre.ts, packages/g6/__tests__/demo/static/controller-layout-dendrogram.ts, packages/g6/__tests__/demo/static/controller-layout-force.ts, packages/g6/__tests__/demo/static/controller-layout-forceatlas2-wasm.ts, packages/g6/__tests__/demo/static/controller-layout-fruchterman-gpu.ts, packages/g6/__tests__/demo/static/controller-layout-fruchterman-wasm.ts, packages/g6/__tests__/demo/static/controller-layout-grid.ts, packages/g6/__tests__/demo/static/controller-layout-indented.ts, packages/g6/__tests__/demo/static/controller-layout-mindmap.ts, packages/g6/__tests__/demo/static/controller-layout-radial.ts, packages/g6/src/runtime/element.ts, packages/g6/src/runtime/graph.ts, packages/g6/src/runtime/layout.ts, packages/g6/src/runtime/viewport.ts, packages/g6/src/types/viewport.ts, packages/g6/src/utils/data.ts, packages/g6/src/utils/element.ts
* 调整 Graph API  render，draw 实现
* 移除 element controller 中 init 对于 canvas.init 的等待，因为已经在 Graph render、draw 等待完成
* 变更了平移、缩放 API 的参数顺序
---
* Adjust Graph API render to draw implementation 
* Remove init's wait for canvas.init in element controller, because Graph render and draw has been waited
* Changed the translate and zoom API parameter order
=> refactor: adjust render and draw async invoke

package.json, packages/g6/vite.config.js
1. 新增 `dev`、`watch` scripts 用于简化启动流程
2. 修复 dev 启动 `gl-matrix` 错误
=> fix: dev scripts

packages/g6/src/elements/combos/base-combo.ts, packages/g6/src/elements/combos/circle.ts, packages/g6/src/elements/edges/index.ts, packages/g6/src/elements/nodes/base-node.ts, packages/g6/src/elements/nodes/circle.ts, packages/g6/src/elements/nodes/ellipse.ts, packages/g6/src/elements/nodes/image.ts, packages/g6/src/elements/nodes/polygon.ts, packages/g6/src/elements/nodes/rect.ts, packages/g6/src/elements/shapes/base-shape.ts, packages/g6/src/runtime/element.ts, packages/g6/src/types/element.ts
* 调整元素类型定义
* 放宽基类类型限制，放到子类中进行
* BaseNode 不再需要范型 KeyShape 和 KeyShapeStyleProps, 现在传入节点 StyleProps 即可
* BaseCombo 同 BaseNode
---
* Adjust element type definitions
* Relax the base class type restrictions and move them to subclasses
* BaseNode no longer requires generic KeyShape and KeyShapeStyleProps, now passing node StyleProps is sufficient
* BaseCombo is the same as BaseNode
=> refactor(elements): adjust element type definitions

packages/g6/src/behaviors/drag-canvas.ts
* 修复 `DragCanvas` 移除问题
> 问题原因：使用指针拖拽时，会时时更新相机位置，此时不应该启用动画
---
* Fixed `DragCanvas` removal issue 
* > Cause of issue: When using pointer drag, the camera position is constantly updated, and animation should not be enabled at this time
=> fix(behaviors): fix issue that cannot drag canvas when animation is enabled

packages/g6/__tests__/snapshots/behaviors/behavior-zoom-canvas/default.svg, packages/g6/__tests__/unit/behaviors/behavior-zoom-canvas.spec.ts, packages/g6/src/behaviors/zoom-canvas.ts
* 优化 `ZoomCanvas` 交互
---
* Optimize `ZoomCanvas` Experience
=> refactor(behavior): optimize zoom canvas experience

packages/g6/__tests__/unit/behaviors/behavior-collapse-expand.spec.ts, packages/g6/__tests__/unit/behaviors/behavior-drag-canvas.spec.ts, packages/g6/__tests__/unit/behaviors/behavior-drag-element-combo.spec.ts, packages/g6/__tests__/unit/behaviors/behavior-drag-element.spec.ts, packages/g6/__tests__/unit/behaviors/behavior-zoom-canvas.spec.ts, packages/g6/__tests__/unit/elements/change-type.spec.ts, packages/g6/__tests__/unit/elements/combo.spec.ts, packages/g6/__tests__/unit/elements/edge-polyline.spec.ts, packages/g6/__tests__/unit/elements/port.spec.ts, packages/g6/__tests__/unit/elements/position-combo.spec.ts, packages/g6/__tests__/unit/elements/position.spec.ts, packages/g6/__tests__/unit/elements/state.spec.ts, packages/g6/__tests__/unit/elements/visibility.spec.ts, packages/g6/__tests__/unit/elements/z-index.spec.ts, packages/g6/__tests__/unit/plugins/plugin-grid-line.spec.ts, packages/g6/__tests__/unit/runtime/element.spec.ts, packages/g6/__tests__/unit/runtime/graph/graph.spec.ts, packages/g6/__tests__/unit/runtime/viewport.spec.ts, packages/g6/__tests__/unit/spec/theme.spec.ts, packages/g6/package.json, packages/g6/src/elements/shapes/base-shape.ts, packages/g6/src/plugins/tooltip.ts, packages/g6/src/registry/extension/index.ts, packages/g6/src/runtime/behavior.ts, packages/g6/src/runtime/canvas.ts, packages/g6/src/runtime/data.ts, packages/g6/src/runtime/element.ts, packages/g6/src/runtime/graph.ts, packages/g6/src/runtime/layout.ts
* 修复潜在导致内存泄漏的问题
* 销毁彻底，没有完全释放对象
* 测试用例完成后为进行销毁
> 仍存在的内存泄漏问题：`g` 未释放动画执行对象，导致图形被持有无法释放 @xiaoiver 
---
* Fixed potential memory leak issues 
* Completely destroyed, not completely released objects 
* Destroyed after the test case is completed 
> Memory leak problem still exists: 'g' did not release animation execution object, resulting in the graph being held and unable to release @xiaoiver
=> fix: fix issue that cause memory leak

packages/g6/__tests__/unit/runtime/graph/get-plugin-instantce.spec.ts, packages/g6/src/runtime/graph.ts, packages/g6/src/runtime/plugin.ts
* 新增 `getPluginInstance` API，用于获取插件实例并提供插件 API 调用
---
* Added `getPluginInstance` API to get plug-in instances and provide plug-in API calls
```ts
const graph = new Graph({
// ...
plugin: [{key: 'history', type: 'history'}]
});
const history = graph.getPluginInstance<History>('history');
history.undo();
```
=> feat(runtime): add getPluginInstance API

package.json, scripts/contribute.mjs
* 添加了一个脚本用于切换到贡献者所在分支上进行查看
使用方法：
1. 执行 `npm run contribute`
2. 输入贡献者代码分支
> 例如：https://github.com/vaynevayne/G6/tree/feat/minimap
3. 确认后切换到该分支
4. 进行查看与变更
5. 完成/提交后移除远程源并删除分支
=> chore: add script to help checkout contributor branch

packages/site/docs/api/TreeGraph.en.md, packages/site/docs/api/TreeGraph.zh.md, packages/site/docs/api/treeGraphLayout/guide.en.md, packages/site/docs/api/treeGraphLayout/guide.zh.md
修改layout里的type参数indeted拼写错误 应为indented
=> 修改layout里的type参数indeted拼写错误 应为indented

packages/g6/__tests__/demos/graph-to-data-url.ts, packages/g6/__tests__/snapshots/elements/position-combo/default.svg, packages/g6/__tests__/snapshots/layouts/combo-layout/combined.svg, packages/g6/__tests__/snapshots/layouts/compact-box/left-align.svg, packages/g6/__tests__/snapshots/layouts/compact-box/top-to-bottom.svg, packages/g6/__tests__/snapshots/layouts/dagre/antv-flow-combo.svg, packages/g6/__tests__/snapshots/layouts/mindmap/h-left.svg, packages/g6/__tests__/snapshots/layouts/mindmap/h-right.svg, packages/g6/__tests__/snapshots/plugins/tooltip/edge.svg, packages/g6/__tests__/snapshots/plugins/tooltip/hover.svg, packages/g6/__tests__/snapshots/plugins/tooltip/node.svg, packages/g6/__tests__/snapshots/plugins/tooltip/show-tooltip-by-id.svg, packages/g6/__tests__/unit/runtime/graph/graph.spec.ts, packages/g6/src/runtime/canvas.ts, packages/g6/src/runtime/graph.ts
> Graph
> Export
* `toDataURL` 支持导出全图模式
---
* `toDataURL` support export overall mode
=> refactor: toDataURL support export overall mode

packages/g6-extension-3d/src/elements/base-node-3d.ts, packages/g6/__tests__/demos/combo-expand-collapse.ts, packages/g6/__tests__/demos/layout-compact-box-basic.ts, packages/g6/__tests__/demos/layout-compact-box-left-align.ts, packages/g6/__tests__/demos/layout-compact-box-top-to-bottom.ts, packages/g6/__tests__/demos/layout-dendrogram-basic.ts, packages/g6/__tests__/demos/layout-dendrogram-tb.ts, packages/g6/__tests__/demos/layout-indented.ts, packages/g6/__tests__/demos/layout-mindmap-h-custom-side.ts, packages/g6/__tests__/demos/layout-mindmap-h-left.ts, packages/g6/__tests__/demos/layout-mindmap-h-right.ts, packages/g6/__tests__/demos/layout-mindmap-h.ts, packages/g6/__tests__/demos/plugin-history.ts, packages/g6/__tests__/unit/behaviors/drag-element-combo.spec.ts, packages/g6/__tests__/unit/plugins/history/plugin-history.spec.ts, packages/g6/__tests__/unit/runtime/data.spec.ts, packages/g6/src/behaviors/collapse-expand.ts, packages/g6/src/exports.ts, packages/g6/src/runtime/graph.ts
* 调整导出内容，所有导出项平铺导出
* 调整 API 命名
* `collapse`-> `collapseElement`
* `expand` -> `expandElement`
---
* The whole exported content, all exported items tiled export
* Adjust API naming
* `collapse`-> `collapseElement`
* `expand` -> `expandElement`
=> refactor: adjust exports and api

packages/g6/src/runtime/graph.ts
原因为 
原有的默认 height: 400 , width: 600 被删除。
setSize 中 当 height 或者 width 被配置时 对 height width 默认为 0 的处理。
在 Canvas 中的 width ?? containerSize[0] ,height ?? containerSize[1] 中就导致 配置了 height 或者 width ，另一个会为 0 的情况。从而导致报错。
=> fix(graph): width,height bug fix

packages/g6/__tests__/demos/index.ts, packages/g6/__tests__/demos/layout-custom-horizontal.ts, packages/g6/__tests__/demos/layout-custom-iterative.ts, packages/g6/__tests__/demos/layout-force-collision.ts, packages/g6/__tests__/snapshots/layouts/combo-layout/combined.svg, packages/g6/__tests__/snapshots/layouts/custom-layout-horizontal/default.svg, packages/g6/__tests__/snapshots/layouts/d3-force-collision/default.svg, packages/g6/__tests__/snapshots/layouts/fruchterman/cluster.svg, packages/g6/__tests__/snapshots/layouts/grid/sortby-default.svg, packages/g6/__tests__/snapshots/plugins/tooltip/edge.svg, packages/g6/__tests__/snapshots/plugins/tooltip/hover.svg, packages/g6/__tests__/snapshots/plugins/tooltip/node.svg, packages/g6/__tests__/snapshots/plugins/tooltip/show-tooltip-by-id.svg, packages/g6/__tests__/unit/layouts/custom-layout-horizontal.spec.ts, packages/g6/__tests__/unit/runtime/graph/graph.spec.ts, packages/g6/__tests__/unit/spec/layout.spec.ts, packages/g6/__tests__/unit/utils/layout.spec.ts, packages/g6/src/animations/types.ts, packages/g6/src/behaviors/drag-element-force.ts, packages/g6/src/exports.ts, packages/g6/src/layouts/base-layout.ts, packages/g6/src/layouts/index.ts, packages/g6/src/layouts/types.ts, packages/g6/src/registry/types.ts, packages/g6/src/runtime/layout.ts, packages/g6/src/types/index.ts, packages/g6/src/types/layout.ts, packages/g6/src/utils/layout.ts
* 定义 G6 的布局标准接口，如下 / Define the layout standard interfaces for G6 as follows
```ts
interface BaseLayout {
execute(model: GraphData, options?: STDLayoutOptions): Promise<GraphData>;
// suitable for iterative layouts
stop?: () => void;
tick?: (data: GraphData) => void;
}
```
* 适配 @antv/layout 为 G6 布局 / Adapt @antv/layout to G6 layout
* 流水线布局属性 `nodesFilter` 变更为 `nodeFilter`  / The property of pipeline layout `nodesFilter` is renamed to `nodeFilter`
* 添加了自定义布局示例 / Add demo that custom layout
=> refactor: propose G6 layout standard and adapt antv/layout 

packages/g6/__tests__/unit/runtime/data.spec.ts, packages/g6/src/runtime/data.ts, packages/g6/src/runtime/element.ts, packages/g6/src/runtime/graph.ts
* getElementData -> getElementDataById
> 根据 ID 获取该元素数据，而不用考虑元素类型
> Get the element data based on its ID, regardless of the element type
* getElementData -> getElementsDataByType:
> 获取给定类型的所有元素数据
> Gets all element data for a given type
=> refactor(runtime): rename some api name of data controller

.github/workflows/build.yml, .github/workflows/deploy.yml, packages/g6/__tests__/bugs/element-combo-drag.spec.ts, packages/g6/__tests__/snapshots/__tests__/bugs/element-combo-drag/collapse-combo-0.svg, packages/g6/__tests__/snapshots/__tests__/bugs/element-combo-drag/default.svg, packages/g6/__tests__/snapshots/__tests__/bugs/element-combo-drag/drag-combo-0.svg, packages/g6/__tests__/snapshots/__tests__/bugs/element-combo-drag/drag-node-2.svg, packages/g6/__tests__/unit/runtime/data.spec.ts, packages/g6/__tests__/unit/utils/edge.spec.ts, packages/g6/src/runtime/data.ts, packages/g6/src/runtime/element.ts, packages/g6/src/runtime/graph.ts, packages/g6/src/transforms/collapse-expand-combo.ts, packages/g6/src/utils/edge.ts, packages/site/docs/manual/contribute.zh.md
基于 / Based on: https://github.com/antvis/G6/pull/5725
* 修复连接到收起的 combo 内的子节点时，边更新异常的问题
---
* Fixed an exception in edge update when connecting to a child node in a collapsed combo
=> fix(runtime): fix incorrect combo connect

packages/g6/src/elements/nodes/base-node.ts, packages/site/docs/manual/further-reading/iconfont.en.md, packages/site/docs/manual/further-reading/iconfont.zh.md
=> docs: add iconfont tutorial

packages/g6/src/elements/shapes/base-shape.ts, packages/g6/src/runtime/element.ts
=> refactor: composite shapes animation

packages/cli/template-extension/package.json, packages/g6/src/behaviors/hover-element.ts, packages/site/package.json, packages/site/scripts/generate-api.ts
- 修复 `hover-element` 和 `drag-element` 交互共用时冲突问题
- 新增脚本  `npm run doc:dev` 支持本地生成api文档（由于 reference 文件过多，dumi启动慢，本地先删除 reference）
=> fix: fix the conflict issue of hover-element and drag-element

packages/g6-extension-react/__tests__/demos/react-node.tsx, packages/g6-extension-react/src/elements/react/node.tsx, packages/g6/src/behaviors/drag-canvas.ts, packages/g6/src/elements/base-element.ts, packages/g6/src/elements/combos/base-combo.ts, packages/g6/src/elements/edges/base-edge.ts, packages/g6/src/elements/nodes/base-node.ts, packages/g6/src/elements/nodes/html.ts
* 修复 React 节点销毁时逻辑
---
* Fixed React node destruction logic
=> fix: fix react node destruction logic

packages/g6/__tests__/utils/create.ts
* 修复开发环境异常的 Canvas 初始化参数
createGraphCanvas 被同时用于测试环境和开发环境的画布，测试环境在 node 中执行，因此需要传入 document 和 offscreenCanvas，但开发环境是在浏览器中执行，传入这两个参数会导致事件拾取异常。
---
* Fixed abnormal Canvas initialization parameters in the development environment
createGraphCanvas is used as a canvas for both the test environment and the development environment. The test environment is executed in node, so it needs to pass document and offscreenCanvas, but the development environment is executed in the browser, passing these two parameters will cause an event pickup exception.
=> fix: fix exceptional canvas options when init in dev env

packages/g6/__tests__/unit/behaviors/drag-element.spec.ts, packages/g6/src/behaviors/drag-element.ts, packages/g6/src/runtime/behavior.ts, packages/g6/src/runtime/canvas.ts
* 在抓取过程中设置指针样式
---
* Set the pointer cursor during grabbing
=> refactor(behaviors): drag-element can set pointer cursor

packages/core/src/element/node.ts, packages/core/src/graph/graph.ts, packages/pc/src/graph/controller/layout.ts, packages/pc/tests/unit/element/edge-label-back-spec.ts, packages/pc/tests/unit/graph/updateLayout-align-spec.ts, packages/pc/tests/unit/issues-loop-spec.ts
With a test graph with over 2k nodes we noticed a reduction in the computation time from over 5 seconds to less than 1.
Additionally this PR fixes a bunch of punctuation bits
=> feat: improve diffItems performance

packages/g6/src/behaviors/lasso-select.ts, packages/g6/src/elements/base-element.ts, packages/g6/src/elements/combos/base-combo.ts, packages/g6/src/elements/edges/base-edge.ts, packages/g6/src/elements/nodes/base-node.ts, packages/g6/src/exports.ts, packages/g6/src/runtime/data.ts, packages/g6/src/runtime/element.ts, packages/g6/src/runtime/graph.ts, packages/g6/src/types/element.ts, packages/g6/src/types/index.ts, packages/g6/src/types/point.ts, packages/g6/src/types/position.ts, packages/g6/src/utils/element.ts, packages/g6/src/utils/path.ts, packages/g6/src/utils/position.ts
* 调整元素类型定义
* 调整前：元素类型由对应的类进行约束，例如 `type Node = BaseNode<any>`，这要求所有的节点都继承自 `BaseNode`
* 调整后：通过类型进行约束
* 移除类型：Points, Position
---
* Adjusted element type definition 
* Before: The element type is constrained by the corresponding class, such as' type Node = BaseNode<any> ', which requires that all nodes inherit from 'BaseNode' 
* Adjusted: constrained by type
* Remove types: Points, Position
=> refactor: adjust element type definition

packages/g6/__tests__/snapshots/behaviors/click-select-catch/clear.svg, packages/g6/__tests__/snapshots/behaviors/click-select-catch/deleted.svg, packages/g6/__tests__/snapshots/behaviors/click-select-catch/selected.svg, packages/g6/__tests__/unit/behaviors/click-select-catch.spec.ts, packages/g6/src/behaviors/click-select.ts
* 调整 `ClickSelect` 交互以适应特定情形
> 当选中元素被删除时，继续交互会导致找不到被删除的元素进而引发异常
---
* Adapting the `ClickSelect` interaction to suit specific situations
> If the selected element is deleted, continuing the interaction will cause the deleted element not to be found and an exception will be raised
=> refactor(behaviors): refactor click-select in abnormal environment

packages/g6/__tests__/bugs/tree-update-collapsed-node.spec.ts, packages/g6/__tests__/snapshots/__tests__/bugs/tree-update-collapsed-node/default.svg, packages/g6/__tests__/snapshots/__tests__/bugs/tree-update-collapsed-node/update collapsed node.svg, packages/g6/src/runtime/element.ts, packages/g6/src/transforms/collapse-expand-node.ts
* 修复树图中，更新父节点为一个收起的节点时，子节点无法收起的问题
---
* Fixed an issue in the tree diagram where child nodes could not be collapsed when the parent node was updated to a collapsed node
=> fix(transforms): fix mistake when connect to a collapsed node

packages/g6/__tests__/bugs/render-change-combo.spec.ts, packages/g6/__tests__/bugs/render-deleted-data.spec.ts, packages/g6/src/elements/combos/base-combo.ts, packages/g6/src/runtime/data.ts
* 修复操作数据过程中可能导致异常的问题
a. 树图中删除节点后重绘提示找不到节点
b. 更新节点 combo 时删除原 combo 抛出异常
c. 收起仅包含一个元素的 combo 时导致异常
---
* Faults that may occur during operation data restoration 
a. A message indicating that a node cannot be found after being deleted from the tree 
b. When node combo is updated, an exception is thrown when the original combo is deleted
c. An exception occurs when a combo containing only one element is collapsed
https://github.com/antvis/G6/issues/5889 https://github.com/antvis/G6/issues/5885
=> fix: fix error when manipulate data

.github/workflows/build.yml, .vscode/settings.json, packages/g6/__tests__/demos/index.ts, packages/g6/__tests__/demos/layout-custom-dagre.ts, packages/g6/__tests__/snapshots/layouts/custom-dagre/default.svg, packages/g6/__tests__/unit/layouts/custom-dagre.spec.ts, packages/g6/__tests__/unit/utils/layout.spec.ts, packages/g6/package.json, packages/g6/src/layouts/base-layout.ts, packages/g6/src/runtime/layout.ts, packages/g6/src/utils/layout.ts, packages/site/package.json
- 将 context 透传到 layout 类。从而满足自定义布局中使用 @antv/layout 中的布局计算元素位置
=> refactor: pass context in layout

packages/g6/__tests__/demos/layout-compact-box-basic.ts, packages/g6/package.json, packages/g6/src/runtime/graph.ts, packages/site/.dumi/global.ts, packages/site/package.json
* Graphlib 修复了删除节点后 getChildren 不正确的问题 https://github.com/antvis/graphlib/pull/13
---
* Graphlib fixes an issue where getChildren gets incorrect results after removing nodes https://github.com/antvis/graphlib/pull/13
=> chore: update graphlib version

packages/g6/src/runtime/behavior.ts
* 标记为待销毁或已销毁的元素不会触发事件
---
* An element marked for destruction or destroyed does not trigger an event
=> refactor(behavior): destroyed element wont dispatch event

packages/core/src/util/validation.ts
From my tests on a 3k nodes graph, the execution time of this function went from 400ms down to 1ms
=> feat: improve dataValidation function

.github/workflows/build.yml, .github/workflows/deploy.yml, packages/g6/__tests__/bugs/behaviors-collapse-expand.spec.ts, packages/g6/__tests__/demos/layout-antv-dagre-flow-combo.ts, packages/g6/src/utils/animation.ts
* 修复 preprocessKeyframes 问题
> 当传入关键帧被全部过滤清空后，不会执行动画而是直接结束，如果是退场动画则会直接销毁该元素，此时如果有其他相关元素正在执行动画，会导致找不到该元素。
---
* Fixed the preprocessKeyframes issue
> When the incoming key frame is cleared by all filters, the animation is not executed but directly ended. If it is an exit animation, the element is directly destroyed. At this time, if other related elements are performing animation, the element cannot be found.
ISSUE: https://github.com/antvis/G6/issues/5951
=> fix(animation): fix preprocessKeyframes

packages/g6/__tests__/bugs/focus-element.spec.ts, packages/g6/__tests__/demos/behavior-drag-canvas.ts, packages/g6/__tests__/unit/behaviors/drag-canvas.spec.ts, packages/g6/src/behaviors/drag-canvas.ts, packages/g6/src/runtime/viewport.ts
* 修复 DragCanvas onFinish 调用时机不正确的问题
---
* Fixed the incorrect timing of DragCanvas onFinish call
=> fix(behaviors): fix drag-canvas

packages/g6/src/plugins/contextmenu/index.ts
* 修复 trigger 为 click 时 contextmenu 无法唤起的问题
> graph node:click 和 document click 事件同时触发，导致打开菜单栏后立即被关闭
---
* Fix to contextmenu not evoking when trigger is click
> graph node:click and document click events fire at the same time, causing the menu bar to be closed immediately after opening
ISSUE: https://github.com/antvis/G6/issues/6005
=> fix: fix click connot trigger context menu

packages/g6/src/plugins/contextmenu/index.ts
* 修改 contextmenu 使用 getContent 定制内容时重复渲染的问题
---
* Fixed an issue where contextmenu used getContent to customize content with repeated rendering
issue: https://github.com/antvis/G6/issues/5965
=> fix(plugins): fix contextmenu getContent repetitive render

packages/g6/src/elements/shapes/base-shape.ts, packages/g6/src/runtime/animation.ts
* 释放动画对象内存
> G 图形示例会存储动画对象，这在 G6 中并没有什么作用，当动画播放次数较多时，会创建大量的动画对象，导致内存持续增长，使得交互过程卡顿
> 目前在 G6 中手动对相关动画对象进行清理
---
* Release animation object memory 
> G graphics example will store animation objects, which does not have any effect in G6, when the animation is played more times, a large number of animation objects will be created, resulting in continuous memory growth, making the interaction process stuck
> The relevant animation objects are currently cleaned manually at G6
issue: https://github.com/antvis/G/issues/1731
=> perf(animation): optimize animation object memory

packages/g6/__tests__/unit/registry.spec.ts, packages/g6/src/registry/index.ts
* `register` 方法支持传入 `override` 参数来覆盖同名扩展
---
* the `register` method support override exists extension by pass `override`
=> refactor(registry): register support override

packages/g6/__tests__/unit/plugins/history/plugin-history.spec.ts, packages/g6/src/plugins/history/index.ts
- fixed #5935
- fixed #5924
确保当 beforeAddCommand 返回 false 时，命令不会被加入历史记录。 
移除 isFirstDraw 逻辑，以确保每次数据更新都会被记录到历史堆栈中。
=> fix: fix issue that history beforeAddCommand returns false

packages/g6/__tests__/snapshots/behaviors/behavior-create-edge-click/click-edge1-move.svg, packages/g6/__tests__/snapshots/behaviors/behavior-create-edge-drag/drag-edge1-move.svg, packages/g6/__tests__/snapshots/plugins/history/plugin-history/create-edge-redo.svg, packages/g6/__tests__/snapshots/plugins/history/plugin-history/create-edge-undo.svg, packages/g6/__tests__/snapshots/plugins/history/plugin-history/create-edge.svg, packages/g6/__tests__/unit/plugins/history/plugin-history.spec.ts, packages/g6/src/behaviors/create-edge.ts
=> feat: create-edge behavior supports history tracking

packages/g6/__tests__/unit/utils/bbox.spec.ts, packages/g6/src/utils/bbox.ts, packages/g6/src/utils/router/orth.ts
- fixed #5952
调整 polyline 正交路由算法，以便在结合 dagre 布局时优化路径绘制效果
=> fix: improve polyline orth routing for rendering with dagre layout

packages/g6/src/behaviors/hover-activate.ts
- fixed: #6063
当 hover-activate 和 collapse-expand 两种交互同时开启时，如果在展开或收起 combo 的过程中，鼠标移动导致触发悬停效果，将会引起动画冲突。解决方案：在 combo 展开或收起的过程中禁用悬停触发
=> fix: resolve animation conflict between hover-activate and collapse-expand

packages/g6/src/runtime/canvas.ts
* 修复 resize 后画布位置异常的问题
> 问题原因： g canvas resize 后会重置相机位置
---
* Fixed abnormal canvas position after resize 
> Cause of problem: g canvas resize will reset the camera position
issue: https://github.com/antvis/G6/issues/5854
=> fix(runtime): fix camera position lost after canvas resize

packages/g6/__tests__/bugs/element-port-rotate.spec.ts, packages/g6/__tests__/snapshots/__tests__/bugs/element-port-rotate/default.svg, packages/g6/src/elements/nodes/base-node.ts
* 修复设置节点旋转的情况下，连接桩位置不准确的问题
---
* Fixed an issue where the position of the connecting piles was not accurate when the node rotation was set
issue: https://github.com/antvis/G6/issues/5946
=> fix(elements): fix incorrect ports position when rotate node

packages/g6/__tests__/bugs/focus-element.spec.ts, packages/g6/__tests__/snapshots/behaviors/drag-canvas/drag-on-element-default.svg, packages/g6/__tests__/snapshots/behaviors/drag-canvas/drag-on-element.svg, packages/g6/__tests__/unit/behaviors/drag-canvas.spec.ts, packages/g6/__tests__/utils/canvas.ts, packages/g6/__tests__/utils/index.ts, packages/g6/src/behaviors/drag-canvas.ts
* Drag Canvas 交互能够在元素上触发
> 过去，DragCanvas 只能在指针位于画布空白处时才能触发，无法在位于元素上方时触发
> 现在只需要将 `enable` 置为 `true`，即可在任意位置激活拖动画布交互
```typescript
{
type: 'drag-canvas',
enable: true
}
```
> ⚠️ 警告：该配置项下默认情况下会和 `DragElement` 交互有冲突，建议通过更多事件参数进行条件区分
---
* Drag Canvas can be triggered on elements
> In the past, DragCanvas could only be triggered when the pointer was in a blank area of the canvas, not when it was above an element 
> Now just need to set `enable` to `true` to activate drag-canvas behavior anywhere
> ⚠️ Warning: This options item conflicts with `DragElement` behavior by default. It is recommended to use more event parameters to distinguish conditions
=> refactor: drag canvas can be triggered on elements

packages/g6/src/runtime/graph.ts, packages/site/docs/manual/further-reading/coordinate.en.md, packages/site/docs/manual/further-reading/coordinate.zh.md
* 添加坐标系文档
---
* Add a coordinate document
=> docs: add coordinate docs

packages/g6/__tests__/bugs/plugin-minimap-combo-collapsed.spec.ts, packages/g6/__tests__/snapshots/bugs/plugin-minimap-combo-collapsed/default.svg, packages/g6/__tests__/snapshots/bugs/plugin-minimap-combo-collapsed/update collapsed combo.svg, packages/g6/src/plugins/minimap/index.ts
https://github.com/antvis/G6/issues/6119
=> fix(minimap): fix collapsed combo childrenNode getShape not found

packages/g6/__tests__/snapshots/layouts/compact-box/basic.svg, packages/g6/__tests__/snapshots/layouts/compact-box/left-align.svg, packages/g6/__tests__/snapshots/layouts/compact-box/top-to-bottom.svg, packages/g6/__tests__/snapshots/layouts/dendrogram/basic.svg, packages/g6/__tests__/snapshots/layouts/dendrogram/tb.svg, packages/g6/__tests__/snapshots/layouts/mindmap/h-custom-side.svg, packages/g6/__tests__/snapshots/layouts/mindmap/h-left.svg, packages/g6/__tests__/snapshots/layouts/mindmap/h-right.svg, packages/g6/__tests__/snapshots/layouts/mindmap/h.svg, packages/g6/__tests__/snapshots/runtime/graph/add-children-data/add-children-data.svg, packages/g6/__tests__/snapshots/runtime/graph/add-children-data/default.svg, packages/g6/src/runtime/layout.ts
After:
Before:
* 优化树图入场布局效果
---
* Optimize the tree entry layout effect
=> refactor(layout): optimize tree entry layout effect

packages/g6/__tests__/bugs/element-node-icon-switch.spec.ts, packages/g6/__tests__/snapshots/bugs/element-node-icon-switch/image-icon.svg, packages/g6/__tests__/snapshots/bugs/element-node-icon-switch/text-icon.svg, packages/g6/src/elements/shapes/base-shape.ts, packages/g6/src/elements/shapes/icon.ts
* 修复 Icon 图形切换 src/text 后无法更新的问题
---
* Fixed Icon graphics cannot be updated after switching src/text 
Issue: https://github.com/antvis/G6/issues/6123
=> fix: destroy shape after change icon type

packages/g6/src/behaviors/drag-canvas.ts
Fix the issue that when enable is true, the drag canvas does not trigger on the node element.
=> fix(behaviors): fix drag-canvas event listener type

packages/g6/__tests__/bugs/element-custom-state-switch.spec.ts, packages/g6/__tests__/snapshots/bugs/element-custom-state-switch/multiple-select.svg, packages/g6/__tests__/snapshots/bugs/element-custom-state-switch/multiple-unselect.svg, packages/g6/__tests__/snapshots/bugs/element-custom-state-switch/multiple.svg, packages/g6/__tests__/snapshots/bugs/element-custom-state-switch/single-select.svg, packages/g6/__tests__/snapshots/bugs/element-custom-state-switch/single.svg, packages/g6/src/behaviors/click-select.ts
Fix the issue that when setting states in data, once the states are set by the click select behavior, the preset states are lost.
issue: https://github.com/antvis/G6/issues/6154
=> fix(behaviors): fix click-select lost preset states

packages/g6/__tests__/demos/element-visibility-part.ts, packages/g6/__tests__/demos/index.ts, packages/g6/__tests__/snapshots/behaviors/behavior-create-edge-click/click-edge1-move.svg, packages/g6/__tests__/snapshots/behaviors/behavior-create-edge-drag/drag-edge1-move.svg, packages/g6/__tests__/snapshots/elements/visibility/default.svg, packages/g6/__tests__/snapshots/elements/visibility/hide-single.svg, packages/g6/__tests__/snapshots/elements/visibility/hide.svg, packages/g6/__tests__/snapshots/elements/visibility/show-and-hide.svg, packages/g6/__tests__/snapshots/elements/visibility/show-single.svg, packages/g6/__tests__/snapshots/elements/visibility/show.svg, packages/g6/__tests__/unit/utils/visibility.spec.ts, packages/g6/src/behaviors/optimize-viewport-transform.ts, packages/g6/src/elements/shapes/base-shape.ts, packages/g6/src/exports.ts, packages/g6/src/utils/style.ts, packages/g6/src/utils/visibility.ts
Fix the issue that the `setVisibility` utility method cannot be set correctly.
=> fix: fix setVisibility util

packages/g6/__tests__/demos/animation-element-edge-line.ts, packages/g6/__tests__/demos/canvas-cursor.ts, packages/g6/__tests__/demos/index.ts, packages/g6/__tests__/unit/runtime/canvas.spec.ts, packages/g6/src/runtime/graph.ts, packages/g6/src/spec/canvas.ts
Now you can set and update pointer cursor:
```ts
const graph = new Graph({
// ... other options
cursor: 'progress'
});
graph.setOptions({
cursor: 'pointer'
});
```
=> feat: support specific and set cursor

packages/g6/src/plugins/contextmenu/index.ts
- adjust contextmenu onclick params
before
```
onClick?: (value: string, target: HTMLElement) => void;
```
after
```
onClick?: (value: string, target: HTMLElement, current: Element) => void;
```
=> fix: adjust contextmenu onclick params to get element

packages/g6/__tests__/bugs/element-orth-router.spec.ts, packages/g6/__tests__/demos/case-org-chart.ts, packages/g6/__tests__/demos/element-edge-polyline-astar.ts, packages/g6/__tests__/demos/element-edge-polyline.ts, packages/g6/__tests__/demos/index.ts, packages/g6/__tests__/snapshots/elements/edges/polyline-astar/default.svg, packages/g6/__tests__/snapshots/elements/edges/polyline-astar/left-left.svg, packages/g6/__tests__/snapshots/elements/edges/polyline-astar/obstacle-move-node-1.svg, packages/g6/__tests__/snapshots/elements/edges/polyline-astar/obstacle-move-node-2.svg, packages/g6/__tests__/snapshots/elements/edges/polyline-astar/obstacle-move-node-3.svg, packages/g6/__tests__/snapshots/elements/edges/polyline-astar/obstacle-move-node-4.svg, packages/g6/__tests__/unit/elements/edges/polyline-animation.spec.ts, packages/g6/__tests__/unit/elements/edges/polyline-astar.spec.ts, packages/g6/__tests__/unit/utils/router.spec.ts, packages/g6/src/elements/edges/base-edge.ts, packages/g6/src/elements/edges/polyline.ts, packages/g6/src/plugins/grid-line.ts, packages/g6/src/types/index.ts, packages/g6/src/types/router.ts, packages/g6/src/utils/bbox.ts, packages/g6/src/utils/router/orth.ts, packages/g6/src/utils/router/shortest-path.ts, packages/g6/src/utils/text.ts, packages/site/common/api/elements/edges/polyline.md, packages/site/examples/element/edge/demo/polyline-orth-with-cps.js, packages/site/examples/element/edge/demo/polyline-orth.js, packages/site/examples/layout/dagre/demo/dagre.js, packages/site/examples/scene-case/default/demo/organization-chart.js
=> feat: use a-star pathfinding algorithm to draw polyline

packages/g6/__tests__/bugs/utils-set-visibility.spec.ts, packages/g6/__tests__/snapshots/bugs/utils-set-visibility/default.svg, packages/g6/__tests__/snapshots/bugs/utils-set-visibility/hidden.svg, packages/g6/__tests__/snapshots/bugs/utils-set-visibility/visible.svg, packages/g6/__tests__/unit/utils/visibility.spec.ts, packages/g6/src/behaviors/optimize-viewport-transform.ts, packages/g6/src/elements/shapes/base-shape.ts, packages/g6/src/runtime/element.ts, packages/g6/src/utils/visibility.ts
Fixed issue where when animation was enabled, some shapes were lost when elements were hidden and displayed again
> The main reason for this is that the composite shapes set the visibility without considering whether the visibility style was set manually or inherited
=> fix: fix part of element lost when set visibility in animation

packages/g6/__tests__/unit/behaviors/drag-canvas.spec.ts, packages/g6/src/behaviors/drag-canvas.ts
Add a new option which allows specifying the allowed direction for `drag-canvas` behavior.
=> feat: support direction for drag-canvas behavior

packages/g6/__tests__/demos/plugin-snapline.ts, packages/g6/__tests__/snapshots/behaviors/brush-select/brush-selecting-zoom.svg, packages/g6/__tests__/snapshots/plugins/snapline/zoom-5.svg, packages/g6/__tests__/unit/behaviors/brush-select.spec.ts, packages/g6/__tests__/unit/plugins/snapline.spec.ts, packages/g6/__tests__/unit/utils/shortcut.spec.ts, packages/g6/src/behaviors/brush-select.ts, packages/g6/src/plugins/snapline/index.ts, packages/g6/src/runtime/viewport.ts
* The lineWidth of snapline and box of brush-select won't affected by canvas zoom
* Fix trigger brush select, 'Shift' + 'drag' operation won't trigger 'drag'
=> refactor: snapline and brush-select keep lineWidth after canvas zoom

packages/g6/src/behaviors/scroll-canvas.ts, packages/g6/src/behaviors/zoom-canvas.ts
zoom canvas and scroll canvas add `preventDefault` options
relative issue: https://github.com/antvis/G6/issues/6167
=> refactor: behaviors support preventDefault options

package.json, packages/g6/__tests__/perf-report/9821ed36_2024-08-19_16:33:46.json, packages/g6/__tests__/perf/data.perf.ts, packages/g6/__tests__/perf/draw.perf.ts, packages/g6/perf.config.js
Performance testing based on [iperf](https://github.com/Aarebecca/performance) framework
=> test: config perf test env, add perf test case and report

packages/g6/src/plugins/snapline/index.ts
Sometimes, the horizontal line or vertical line may not have been created, the destroy method is undefined.
This pull request adds optional chain check.
=> fix(plugins): fix error when destroy snapline plugin

packages/g6/__tests__/demos/behavior-optimize-viewport-transform.ts, packages/g6/__tests__/snapshots/behaviors/optimize-viewport-transform/after-viewport-change.svg, packages/g6/__tests__/snapshots/behaviors/optimize-viewport-transform/default.svg, packages/g6/__tests__/snapshots/behaviors/optimize-viewport-transform/viewport-change.svg, packages/g6/src/behaviors/optimize-viewport-transform.ts
Fix the issue that when drag canvas, the arrow of edges does't hide
related issue: https://github.com/antvis/G6/issues/6211
=> fix(behaviors): fix optimize viewport transform does not hide edge arrow

packages/g6-extension-react/__tests__/demos/g-node.tsx, packages/g6-extension-react/src/elements/g/node.tsx, packages/g6/__tests__/unit/elements/shape.spec.ts, packages/g6/src/elements/shapes/base-shape.ts, packages/g6/src/exports.ts
* BaseShape upsert method support hook callbacks (e.t. beforeCreate, afterCreate)
* Fix issue when update styles of node, it's react node does't update.
related issue: https://github.com/antvis/G6/issues/6192
> note: this pull request depends on https://github.com/antvis/G/pull/1757
=> fix: when update styles of node, it's react node does't update.

packages/g6/__tests__/unit/runtime/graph/get-plugin-instantce.spec.ts, packages/g6/src/runtime/plugin.ts
In a generic situation, it should pass a exact key to `getPluginInstance`, but sometimes it may be a little bit verbose when setting the plugin in options. Now `getPluginInstance` will try to find the instance after finding by the key.
Graph options:
```ts
plugins: ['fullscreen']
```
Get instance:
```ts
graph.getPluginInstance('fullscreen');
```
> ⚠️ Note: this is just a fallback plan, and if a plugin is configured multiple times, it only returns the first instance.
=> refactor: getPluginInstance allow match by type secondary

packages/g6-extension-3d/src/elements/base-node-3d.ts, packages/g6-extension-3d/src/elements/capsule.ts, packages/g6-extension-3d/src/elements/cone.ts, packages/g6-extension-3d/src/elements/cube.ts, packages/g6-extension-3d/src/elements/cylinder.ts, packages/g6-extension-3d/src/elements/plane.ts, packages/g6-extension-3d/src/elements/sphere.ts, packages/g6-extension-3d/src/elements/torus.ts, packages/g6/__tests__/unit/registry.spec.ts, packages/g6/src/constants/registry.ts, packages/g6/src/elements/shapes/base-shape.ts, packages/g6/src/registry/build-in.ts, packages/g6/src/registry/store.ts, packages/g6/src/registry/types.ts
Now G6 support shape type extension, you can register or get by as follows:
```ts
import { register, getExtension, ExtensionCategory } from '@antv/g6';
import { Circle } from '@antv/g';
register(ExtensionCategory.Shape, 'circle', Circle);
const CircleCtor = getExtension(ExtensionCategory.Shape, 'circle');
```
The `upsert` method also support specific registered shape type instead of class.
```ts
import { Circle } from '@antv/g';
this.upsert('shape-key', Circle, { r: 10 }, container); // General
this.upsert('shape-key', 'circle', { r: 10 }, container); // ✅ Both Ok
```
=> feat: support shape type extension

packages/g6/__tests__/snapshots/plugins/edge-filter-lens/lens-style.svg, packages/g6/__tests__/unit/plugins/edge-filter-lens.spec.ts, packages/g6/src/plugins/edge-filter-lens/index.ts, packages/site/examples/plugin/edge-filter-lens/demo/basic.js
- Modify edge filter lens plugin options. Configuration naming to be consistent with fisheye
Change
```ts
{ scaleRByWheel?: boolean }
```
to
```ts
{ scaleRBy?:'wheel' | 'unset' }
```
=> refactor: adjust edge filter lens plugin options

packages/g6/__tests__/bugs/api-expand-element-z-index.spec.ts, packages/g6/__tests__/demos/element-html-sub-graph.ts, packages/g6/__tests__/demos/index.ts, packages/g6/__tests__/snapshots/behaviors/collapse-expand-combo/collapse-combo-1-expand-combo-2-0.svg, packages/g6/__tests__/snapshots/behaviors/collapse-expand-combo/collapse-combo-1-expand-combo-2-1000.svg, packages/g6/__tests__/snapshots/behaviors/collapse-expand-combo/collapse-combo-1-expand-combo-2-500.svg, packages/g6/__tests__/snapshots/behaviors/collapse-expand/expand-combo-1.svg, packages/g6/__tests__/snapshots/plugins/history/plugin-history/expand.svg, packages/g6/__tests__/unit/utils/dom.spec.ts, packages/g6/src/elements/effect.ts, packages/g6/src/elements/nodes/html.ts, packages/g6/src/exports.ts, packages/g6/src/plugins/contextmenu/index.ts, packages/g6/src/runtime/element.ts, packages/g6/src/utils/dom.ts, packages/site/examples/scene-case/default/demo/meta.json, packages/site/examples/scene-case/default/demo/sub-graph.js
Add sub graph demo which implement by custom combo and node.
Bugfix:
* Fix issue that after after expand element, which descendants may have wrong zIndex
* Correct html bounds with dx, dy
* HTML forward event only enable when canvas renderer is used
* fix contextmenu container zIndex
=> docs: add sub graph demo

package.json, packages/g6/__tests__/demos/element-html-sub-graph.ts, packages/g6/__tests__/perf-report/9821ed36_2024-08-29_11:11:17.json, packages/g6/__tests__/perf-report/9821ed36_2024-08-29_13:24:51.json, packages/g6/__tests__/perf/update-state.perf.ts, packages/g6/src/elements/combos/base-combo.ts, packages/g6/src/elements/edges/base-edge.ts, packages/g6/src/elements/effect.ts, packages/g6/src/elements/nodes/base-node.ts, packages/g6/src/elements/shapes/base-shape.ts, packages/g6/src/exports.ts
Replace type of  the `effect` from decorator to function to reduce the time of style calculating
Optimized Result (left before, right after): 
> The average performance improved by more than 30%.
=> perf: optimize element dependencies effect trace performance

packages/g6/__tests__/bugs/element-node-collapse.spec.ts, packages/g6/src/runtime/element.ts
If there are not changes to update, the `computeChangesAndDrawData` will return null, any uncheck will cause an exception.
Related issue: https://github.com/antvis/G6/issues/6250
=> fix(runtime): fix issue that try to expand or collapse a node may cause exception

packages/g6/src/behaviors/drag-element.ts
During the drag element process, once the contextmenu or blur event is triggered, the process will be interrupted.
=> fix(behaviors): contextmenu and blur events will interrupt drag process

packages/g6/__tests__/unit/behaviors/drag-canvas.spec.ts, packages/g6/__tests__/unit/behaviors/scroll-canvas.spec.ts, packages/g6/src/behaviors/drag-canvas.ts, packages/g6/src/behaviors/scroll-canvas.ts
For the scroll-canvas behavior, specifying a range of 0.5 results in the effect demonstrated in the GIF. Similarly, the same applies to the drag-canvas behavior.
=> feat(behavior): scroll-canvas/drag-canvas support range

packages/g6/__tests__/perf-report/9821ed36_2024-09-03_10:33:27.json
Add the performance report before the massive scene optimization is performed, and the left is after optimized, right is before optimized.
=> perf: add report before massive optimize

packages/g6/__tests__/demos/plugin-tooltip.ts, packages/g6/src/plugins/tooltip.ts
Fixed when pointing out of enabled elements, tooltip will not hide.
会中文，可以用中文评论。
Reproduce: [Tooltip API](https://g6-next.antv.antgroup.com/api/plugins/tooltip) Change enable to node or edge only and then hover on those nodes or edges to see the tooltip isn't hide correctly
=> fix: correctly hide tooltip when point out

packages/g6/__tests__/snapshots/elements/combo/combo-with-position.svg, packages/g6/__tests__/unit/elements/combo.spec.ts, packages/g6/__tests__/unit/utils/position.spec.ts, packages/g6/src/elements/combos/base-combo.ts, packages/g6/src/utils/position.ts
After this adjustment, the computation logic of combo can be summarized as:
1. If the combo has no children, use its position which is specified in the data style
2. If the combo is collapsed, and its children have position specified in the data style, compute the average position of children nodes.
3. Compute the position by the bounds box of children nodes
=> refactor(elements): adjust the computation logic of combo

packages/g6/src/elements/nodes/html.ts
When pointer moves to the object which was created by the html node, it shouldn't emit the pointerupoutside event.
=> fix(elements): fix the issue that html node cannot catch click event

packages/g6-extension-react/__tests__/demos/performance-diagnosis.tsx, packages/g6/__tests__/bugs/focus-element.spec.ts, packages/g6/__tests__/unit/behaviors/hover-activate.spec.ts, packages/g6/src/behaviors/hover-activate.ts
修正 `hover-activate` 交互绑定的监听事件 
- pointerover 👉 pointerenter
- pointerout 👉 pointerleave
- fixed: https://github.com/antvis/G6/issues/6303
=> fix: correct hover-activate event listeners

packages/g6/__tests__/demos/plugin-minimap.ts, packages/g6/src/plugins/minimap/index.ts
In some situation, drag canvas or hover element may cause minimap blink, 
This pull request fixed above problem by replacing throttle with debounce and add wait time to reduce update times.
=> refactor(plugins): adjust minimap to avoid flash in some scene

packages/g6/__tests__/bugs/element-set-position-to-origin.spec.ts, packages/g6/src/elements/shapes/base-shape.ts
Fix issue that element cannot set position to origin point`(0, 0)`
=> fix(elements): fix element cannot translate to origin point

packages/g6/__tests__/snapshots/behaviors/drag-element-combo/drag-combo-2-after-drop-into.svg, packages/g6/__tests__/snapshots/plugins/history/plugin-history/create-edge-redo.svg, packages/g6/__tests__/snapshots/plugins/history/plugin-history/create-edge-undo.svg, packages/g6/__tests__/snapshots/plugins/history/plugin-history/create-edge.svg, packages/g6/__tests__/snapshots/plugins/history/plugin-history/hideElement-redo.svg, packages/g6/__tests__/snapshots/plugins/history/plugin-history/hideElement-undo.svg, packages/g6/__tests__/snapshots/plugins/history/plugin-history/hideElement.svg, packages/g6/__tests__/snapshots/plugins/history/plugin-history/setElementZIndex-redo.svg, packages/g6/__tests__/snapshots/plugins/history/plugin-history/setElementZIndex-undo.svg, packages/g6/__tests__/snapshots/plugins/history/plugin-history/setElementZIndex.svg, packages/g6/__tests__/unit/plugins/history/plugin-history.spec.ts, packages/g6/__tests__/utils/dir.ts, packages/g6/src/runtime/data.ts, packages/g6/src/utils/visibility.ts
* fix(DataController): after calling graph.addChildrenData(nodeInCombo,  [nodeNotInCombo]), can not listen click event of added node. 
* fix(DataController): translateComboBy will make twice tranlations to the same child node of a combo
=> fix: update zIndex while calling setParent & deduplicate while translating.

packages/g6/src/runtime/layout.ts, packages/g6/src/utils/layout.ts
Fix the issue that when disable the enter animation of element, the autoFit will not effect.
=> fix: fix auto fit not effect when disable element animation

packages/g6/__tests__/unit/runtime/graph/graph.spec.ts, packages/g6/src/runtime/graph.ts
- 透出 `getDescendantsData` api，适用于 tree、combo 数据
=> feat: expose getDescendantsData api

packages/cli/CHANGELOG.md, packages/cli/package.json, packages/cli/template-extension/tsconfig.json, packages/g6-extension-3d/package.json, packages/g6-extension-react/package.json, packages/g6/CHANGELOG.md, packages/g6/package.json, packages/g6/src/version.ts, packages/site/docs/manual/feature-common/webpack4.md, packages/site/docs/manual/further-reading/bundle.en.md, packages/site/docs/manual/further-reading/bundle.zh.md, tsconfig.json
* set build target to es6
* update publish version
* update webpack4 config docs
=> chore: update build target and version

packages/g6/__tests__/demos/case-mindmap.ts, packages/g6/__tests__/unit/utils/tree.spec.ts, packages/g6/src/spec/data.ts, packages/g6/src/types/tree.ts, packages/g6/src/utils/tree.ts, packages/site/examples/scene-case/default/demo/mindmap.js
- Assign `depth` values when using `treeToGraphData`
=> feat: tree depth

packages/site/docs/manual/getting-started/extensions.zh.md
fix typos in packages/site/docs/manual/getting-started/extensions.zh.md
=> docs: fix typos

packages/g6/__tests__/snapshots/behaviors/behavior-create-edge-click/click-edge1-move.svg, packages/g6/__tests__/snapshots/behaviors/behavior-create-edge-drag/drag-edge1-move.svg, packages/g6/src/behaviors/create-edge.ts
fix target node position error https://github.com/antvis/G6/issues/6367
=> fix: target node position error when create edge

packages/g6/src/runtime/behavior.ts
fixed [#6377](https://github.com/antvis/G6/issues/6377)
=> fix: error targetType when pointer leave (#6377)

packages/g6/__tests__/demos/case-fishbone.ts, packages/g6/__tests__/demos/index.ts, packages/site/examples/scene-case/default/demo/fishbone.js, packages/site/examples/scene-case/default/demo/meta.json
=> docs: add fishbone diagram demo

packages/g6/src/elements/nodes/base-node.ts
=> fix: destroy substitute shape after measure bounds

packages/g6/src/animations/types.ts, packages/g6/src/runtime/animation.ts, packages/g6/src/runtime/element.ts
> 20000 节点场景下，渲染时长从 1.27s 下降至 1.13 (11%)
---
> In the 20,000-node scene, the rendering duration decreased from 1.27s to 1.13s (11%)
=> perf: skip infer style when disable animation

packages/g6/__tests__/unit/utils/element.spec.ts, packages/g6/__tests__/unit/utils/event.spec.ts, packages/g6/src/elements/base-element.ts, packages/g6/src/elements/combos/base-combo.ts, packages/g6/src/elements/edges/base-edge.ts, packages/g6/src/elements/nodes/base-node.ts, packages/g6/src/elements/shapes/base-shape.ts, packages/g6/src/exports.ts, packages/g6/src/global.d.ts, packages/g6/src/runtime/element.ts, packages/g6/src/types/element.ts, packages/g6/src/utils/style.ts
=> refactor(elements): move context from style to config

.changeset/healthy-penguins-study.md, .github/workflows/ci.yml, packages/g6/__tests__/demos/element-node-html-2.ts, packages/g6/__tests__/demos/index.ts, packages/g6/src/elements/nodes/html.ts
---
related issue: https://github.com/antvis/G6/issues/6541
=> fix: html node only render key shape

packages/g6/__tests__/unit/utils/visibility.spec.ts, packages/g6/src/behaviors/optimize-viewport-transform.ts, packages/g6/src/elements/shapes/base-shape.ts, packages/g6/src/utils/visibility.ts
简化 `setVisibility` 逻辑，不再考虑元素默认可见性
---
Simplified the 'setVisibility' logic to no longer consider the default visibility of elements
Related Issue: https://github.com/antvis/G6/issues/6559
=> refactor: simplify visibility logic

packages/g6/__tests__/demos/behavior-expand-collapse-node.ts, packages/g6/src/behaviors/collapse-expand.ts, packages/g6/src/exports.ts, packages/g6/src/runtime/element.ts, packages/g6/src/runtime/graph.ts, packages/g6/src/runtime/viewport.ts
开启该选项时，展开收起操作始终保持目标元素位置不变（避免丢失目标）
---
When this option is on, the Expand and Collapse action always keeps the target element position unchanged
Relative Issue: https://github.com/antvis/G6/issues/6494
开启效果：
关闭效果：
=> refactor: collapse-expand support align option

packages/g6/__tests__/bugs/model-remove-parent.spec.ts, packages/g6/__tests__/snapshots/bugs/model-remove-parent/default.svg, packages/g6/__tests__/snapshots/bugs/remove-parent.svg, packages/g6/package.json, packages/g6/src/runtime/data.ts, packages/g6/src/spec/data.ts, packages/site/docs/manual/faq.en.md, packages/site/docs/manual/faq.zh.md
---
Related Issue: https://github.com/antvis/G6/issues/6539
```typescript
graph.updateNodeData([{ id: "node-id", combo: null }]);
```
=> fix: fix removing parent combo of node not effect

packages/site/.dumirc.ts, packages/site/package.json
- 根据自定义优先级对搜索结果排序，希望用户优先查看使用文档而不是开发者 TS 文档
|before |after |
| ----- | ---- |
| <img width="300" src="https://github.com/user-attachments/assets/4a1bb042-6392-4191-83ce-d968ab14f36e"/> | <img width="300" src="https://github.com/user-attachments/assets/ff69ec5c-ec2b-4a8a-915d-a8c254d9b1fb"/> |
| <img width="300" src="https://github.com/user-attachments/assets/f3e8ee62-9481-4c4e-90ab-419d88e77f77"/>|  <img width="300" src="https://github.com/user-attachments/assets/60ff9fb8-1cdb-44ca-bbf1-085ff2dbeaa6"/>|
- 标签页标题与文章标题联动
=> docs: sort search results by custom priority

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/docs-feedback.yml, .github/ISSUE_TEMPLATE/feature.yml, .github/workflows/no-response.yml
新增 issue labels：`status: waiting for maintainer` 和 `status: waiting for author`
后续 issue 处理分为两个阶段：
- 第一阶段：了解诉求
1. issue 被创建时会被标记为 `status: waiting for maintainer`
2. 如果开发者希望进一步了解细节，可以进行回复并手动切换为 `status: waiting for author`
3. 如果已经完全了解，能评估出此 issue 是 bug 还是 feature，则删除这两个标记，并进入第二阶段。
4. 有时效性，如果挂有 `status: waiting for author` 标记七天内没有用户回复，会自动关闭此 issue
- 第二阶段：解决问题
1. 需要精细化设置标签。例如，如果 issue 描述了拖拽画布交互的 bug，则对应标签为 `behavior: drag-canvas`、`behavior`、`bug`、`v5`。方便用户检索历史 issue
=> chore: update issue template and add conversion workflow

packages/g6-extension-react/README.md
Simple fix for `packages/g6-extension-react/README.md`:
=> fix: packages/g6-extension-react/README.md Usage description

packages/g6/__tests__/bugs/element-set-position-to-origin.spec.ts, packages/g6/__tests__/demos/case-unicorns-investors.ts, packages/g6/__tests__/demos/layout-dendrogram-tb.ts, packages/g6/__tests__/snapshots/layouts/compact-box/left-align.svg, packages/g6/__tests__/snapshots/layouts/dendrogram/tb.svg, packages/g6/src/animations/executor.ts, packages/g6/src/elements/shapes/base-shape.ts, packages/g6/src/utils/element.ts, packages/g6/src/utils/transform.ts
> 对于大部分 G6 样式，直接拷贝至内置 attributes 对象性能会比 setAttribute API 更好
优化结果：（以 perf20000Elements 用例为基准）
首屏渲染时长
优化前：930 ms
优化后：900 ms
提升约：3.2%
=> perf: avoid unnecessary transform updates to improve performance

packages/g6/__tests__/bugs/behaviors-click-select-drag-node.spec.ts, packages/g6/__tests__/main.ts, packages/g6/__tests__/snapshots/bugs/behaviors-click-select-drag-node/click-node-1-node-2.svg, packages/g6/__tests__/snapshots/bugs/behaviors-click-select-drag-node/click-node-1.svg, packages/g6/__tests__/snapshots/bugs/behaviors-click-select-drag-node/drag-node-1-node-2.svg, packages/g6/__tests__/snapshots/bugs/behaviors-click-select-drag-node/drag-node-2.svg, packages/g6/src/behaviors/drag-element.ts
当启用 `ClickSelect` 时，如果当前拖拽的节点未被选中，则不会同时拖拽其他选中节点。
---
When `ClickSelect` is enabled, if the currently dragged node is not selected, other selected nodes will not be dragged simultaneously.
=> refactor(behaviors): optimize drag-element behavior

packages/g6/src/runtime/element.ts, packages/g6/src/spec/theme.ts, packages/g6/src/utils/animation.ts
=> perf: optimize performance when disable animation

packages/g6-extension-3d/package.json, packages/g6-extension-react/package.json, packages/g6-ssr/package.json, packages/g6/package.json, packages/g6/src/version.ts
Revert https://github.com/antvis/G6/pull/6609. 
For security reasons, installing dependencies from GitHub isn't supported
=> Revert "feat: upgrade hull.js"

packages/g6-extension-3d/package.json, packages/g6-extension-react/__tests__/unit/attribute-changed-callback.spec.tsx, packages/g6-extension-react/jest.config.js, packages/g6-extension-react/package.json, packages/g6-extension-react/src/elements/react/node.tsx, packages/g6-ssr/package.json, packages/g6/__tests__/demos/case-language-tree.ts, packages/g6/__tests__/demos/case-unicorns-investors.ts, packages/g6/package.json, packages/g6/src/utils/element.ts, packages/g6/src/version.ts
> 系 https://github.com/antvis/G6/pull/6619 导致 component 更新未触发 attributeChangedCallback 方法所致
=> fix(react): fix react component update not effect

packages/g6-ssr/README.md, packages/g6-ssr/package.json, packages/g6-ssr/src/index.ts
=> chore: export g6 getExtension, getExtensions and register from ssr

packages/g6/__tests__/demos/perf-20000-elements.ts, packages/g6/src/elements/combos/base-combo.ts, packages/g6/src/elements/edges/base-edge.ts, packages/g6/src/elements/effect.ts, packages/g6/src/elements/nodes/base-node.ts, packages/g6/src/runtime/element.ts, packages/g6/src/utils/style.ts
以 2W 元素为基准测试
> 优化前 `1175 ms`
整体时长缩短 `361 ms` (`30%`)
=> perf: optimize performance

package.json, packages/g6/__tests__/main.ts
=> refactor: dev env add fps monitor

packages/g6/src/plugins/utils/canvas.ts
=> refactor: minimap wont override specified container style

PUBLISH.md, package.json, packages/g6-extension-3d/package.json, packages/g6-extension-react/package.json, packages/g6-ssr/package.json, packages/g6/package.json, packages/g6/src/version.ts, scripts/version.sh
- add version shell
- update version
=> chore: update version

packages/site/.dumirc.ts, packages/site/package.json, packages/site/src/markdown/CustomMarkdownEmitter.ts, packages/site/src/nodes/DocPageTitle.ts
- Allow users to provide feedback directly on the G6 official website
=> docs: support user feedback on G6 site

packages/g6/__tests__/snapshots/runtime/layout/empty.svg, packages/g6/__tests__/snapshots/runtime/layout/extra.svg, packages/g6/__tests__/snapshots/runtime/layout/layout-array.svg, packages/g6/__tests__/snapshots/runtime/layout/other-type.svg, packages/g6/__tests__/snapshots/runtime/layout/recover.svg, packages/g6/__tests__/unit/runtime/layout.spec.ts, packages/g6/src/runtime/graph.ts, packages/g6/src/runtime/layout.ts, packages/site/examples/layout/mechanism/demo/switch.js
Allow users to configure the `layoutOptions` parameter when calling the `layout` function to perform the layout, and this layout will not modify the default configuration.
=> feat: add parameter config support to layout function

packages/g6/__tests__/unit/behaviors/drag-canvas.spec.ts, packages/g6/src/behaviors/drag-canvas.ts
support drag canvas on mobile device, which is resolved by adapting the mobile offset
Demo:  https://github.com/user-attachments/assets/54155ebb-3bc7-4e06-8400-c149e365bb91
=> feat: support drag canvas on mobile device

packages/g6-extension-3d/package.json, packages/g6-extension-react/package.json, packages/g6-ssr/package.json, packages/g6/package.json, packages/g6/src/version.ts
publish 5.0.43 version, includes: 
1. support config options when call layout functions
2. support behaviors of zoom-canvas and drag-canvas on mobile
=> chore: publish 5.0.43 version for g6

packages/g6/src/layouts/types.ts
Ref:
- https://g6.antv.antgroup.com/manual/getting-started/extensions#布局
- `packages/g6/sr/registry/build-in.ts`
=> Fix wrong layout names in layouts/types.ts

packages/g6/src/runtime/graph.ts
* Optimize `getNodeData`、`getEdgeData`、`getComboData` API performance
* Improve above APIs docs
Relative Issue: https://github.com/antvis/G6/issues/6784
=> refactor(graph): optimize graph api, improve docs

packages/g6-extension-react/package.json
release 0.2.0 version of g6-extension-react, remove react-g node
=> refactor: release 0.2.0 version of g6-extension-react

packages/g6/src/runtime/graph.ts
The function's signature claims to return a `Promise<Void` but forgets to add `await`
=> fix: add missing await in Graph's async absolute zoom function

packages/site/docs/manual/element/node/custom-node.zh.md
=> docs: update custom-node.zh.md

packages/g6/src/runtime/layout.ts, packages/g6/src/utils/edge.ts, packages/g6/src/utils/element.ts
Unlike badges (whose placement is handled by `getTextStyleByPlacement()`, which supports `CornerPlacement`), ports don't support `CornerPlacement` like `top-left`. This PR fixes this by adding keys in `CornerPlacement` to `PORT_MAP`.
Also, document related to ports is missing content. It don't mention its `key` and `placement` prop:
https://g6.antv.antgroup.com/api/elements/nodes/base-node#连接桩样式-ports
Readers can only guess the `placement` prop from the document about badges beside it.
**This fix don't calculate the position with node border. Thus it only works well for the corner of rect-shaped nodes.** Better note about this when adding document about ports.
---
The 2nd commits improves `packages/g6/src/utils/element.ts` with:
- rename param for `PORT_MAP` from `ports` to the more …
=> fix: support CornerPlacement for port

packages/g6/src/plugins/minimap/index.ts
This pr addresses an issue in the Minimap plugin where the render process is delayed due to the use of the immediate parameter in the debounce function.
The use of the immediate parameter in the debounce function was causing the render function to execute immediately on the first call, rather than waiting for subsequent debounce triggers. This led to render delays, especially in scenarios where frequent changes are detected.
To observe the issue, visit the following link: [Minimap Example](https://g6.antv.antgroup.com/examples/plugin/minimap#basic).
- Quickly drag one of the nodes or "balls" in the main graph area.
- You will notice that the Minimap's updates seem to lag behind the main graph visualization, reflecting changes slower than expected.
=> fix: removing immediate parameter from debounce

packages/site/.dumirc.ts, packages/site/docs/manual/data.zh.md, packages/site/docs/manual/theme/custom-theme.zh.md, packages/site/docs/manual/theme/overview.zh.md
- fixed: #6937 
- fixed: #6938
=> docs: update theme overview and custom theme docs

packages/site/package.json
dumi 2.4.20 会导致 ob 代码块运行错误，先锁一下版本
=> chore: pin dumi version to 2.4.17

packages/g6/src/plugins/edge-filter-lens/index.ts
- fix: 当EdgeFilterLens触发update时，`options.r`未赋值给`this.r`，导致此配置未生效；
此问题与之前修复的[fisheye plugins的问题](https://github.com/antvis/G6/pull/6956)类似，我是在编写在线体验时发现：
- fix: 更新EdgeFilterLens的`style` option的ts类型，应该使用`Partial<CircleStyleProps>`更合适；
=> fix: EdgeFilterLens在触发update时，options.r未赋值给this.r，导致配置未生效；fix: style option的ts类型应该使用CircleStyleProps

packages/site/common/api/plugins/edge-filter-lens.md, packages/site/docs/manual/plugin/build-in/EdgeFilterLens.en.md, packages/site/docs/manual/plugin/build-in/EdgeFilterLens.zh.md
=> docs: 优化EdgeFilterLens边过滤镜文档，更新中英文手册内容

packages/site/examples/plugin/fisheye/demo/custom.js
**问题**
https://g6.antv.antgroup.com/examples/plugin/fisheye#custom 我发现这个fisheye的demo， 放大镜的`fill`/`stroke`，都被设置成`transparent`了，这导致用户看不到放大镜，且与左侧缩略图上的效果也不一致，如图：
**解决方案**
改为与缩略图的style保持一致
=> fix: 更新fisheye demo里的style属性，与缩略图保持一致

packages/pc/src/behavior/drag-combo.ts, packages/pc/tests/unit/behavior/drag-combo-spec.ts
This PR ports the support for locked combos/nodes from the `drag-node` behavior.
Works exactly as for nodes
=> feat: Support locked combos in drag-combo behavior
